Function revival0()
    ActiveWindow.DisplayGridlines = False
    Cells(1, 1) = "02_ファイル仕分けv2.5"
    Cells(1, 1).Font.Size = 18
    Cells(1, 1).Font.Name = "メイリオ"
    Cells(1, 1).Font.Bold = True
    Cells(1, 2).Font.Name = "メイリオ"
    Cells(1, 3).Font.Name = "メイリオ"
    Cells(1, 4).Font.Name = "メイリオ"
    Cells(1, 5).Font.Name = "メイリオ"
    Cells(1, 6).Font.Name = "メイリオ"
    Cells(1, 7).Font.Name = "メイリオ"
    Cells(1, 8).Font.Name = "メイリオ"
    Cells(1, 9).Font.Name = "メイリオ"
    Cells(1, 10).Font.Name = "メイリオ"
    Cells(1, 11).Font.Name = "メイリオ"
    Cells(1, 12).Font.Name = "メイリオ"
    Cells(1, 13).Font.Name = "メイリオ"
    Cells(1, 14).Font.Name = "メイリオ"
    Cells(1, 15).Font.Name = "メイリオ"
    Cells(1, 16).Font.Name = "メイリオ"
    Cells(2, 1).Font.Size = 18
    Cells(2, 1).Font.Name = "メイリオ"
    Cells(2, 1).Font.Bold = True
    Cells(2, 2) = "ー概要ー"
    Cells(2, 2).Font.Name = "メイリオ"
    Cells(2, 2).Font.Bold = True
    Cells(2, 3).Font.Name = "メイリオ"
    Cells(2, 4).Font.Name = "メイリオ"
    Cells(2, 5).Font.Name = "メイリオ"
    Cells(2, 6).Font.Name = "メイリオ"
    Cells(2, 7).Font.Name = "メイリオ"
    Cells(2, 8).Font.Name = "メイリオ"
    Cells(2, 9).Font.Name = "メイリオ"
    Cells(2, 10).Font.Name = "メイリオ"
    Cells(2, 11).Font.Name = "メイリオ"
    Cells(2, 12).Font.Name = "メイリオ"
    Cells(2, 13).Font.Name = "メイリオ"
    Cells(2, 14).Font.Name = "メイリオ"
    Cells(2, 15).Font.Name = "メイリオ"
    Cells(2, 16).Font.Name = "メイリオ"
    Cells(3, 1).Font.Size = 18
    Cells(3, 1).Font.Name = "メイリオ"
    Cells(3, 1).Font.Bold = True
    Cells(3, 2) = "対象ブックフォルダに格納されている複数のファイルを、当シートで指定した内容に応じて、任意のフォルダに移動 or コピーする。"
    Cells(3, 2).Font.Name = "メイリオ"
    Cells(3, 2).Font.Bold = True
    Cells(3, 2).HorizontalAlignment = -4131
    Cells(3, 2).IndentLevel = 1
    Cells(3, 3).Font.Name = "メイリオ"
    Cells(3, 4).Font.Name = "メイリオ"
    Cells(3, 5).Font.Name = "メイリオ"
    Cells(3, 6).Font.Name = "メイリオ"
    Cells(3, 7).Font.Name = "メイリオ"
    Cells(3, 8).Font.Name = "メイリオ"
    Cells(3, 9).Font.Name = "メイリオ"
    Cells(3, 10).Font.Name = "メイリオ"
    Cells(3, 11).Font.Name = "メイリオ"
    Cells(3, 12).Font.Name = "メイリオ"
    Cells(3, 13).Font.Name = "メイリオ"
    Cells(3, 14).Font.Name = "メイリオ"
    Cells(3, 15).Font.Name = "メイリオ"
    Cells(3, 16).Font.Name = "メイリオ"
    Cells(4, 1).Font.Size = 18
    Cells(4, 1).Font.Name = "メイリオ"
    Cells(4, 1).Font.Bold = True
    Cells(4, 2) = "移動元フォルダはオプションで再帰処理を指定できる。また、対象とする拡張子の指定も可。"
    Cells(4, 2).Font.Name = "メイリオ"
    Cells(4, 2).Font.Bold = True
    Cells(4, 2).HorizontalAlignment = -4131
    Cells(4, 2).IndentLevel = 1
    Cells(4, 3).Font.Name = "メイリオ"
    Cells(4, 4).Font.Name = "メイリオ"
    Cells(4, 5).Font.Name = "メイリオ"
    Cells(4, 6).Font.Name = "メイリオ"
    Cells(4, 7).Font.Name = "メイリオ"
    Cells(4, 8).Font.Name = "メイリオ"
    Cells(4, 9).Font.Name = "メイリオ"
    Cells(4, 10).Font.Name = "メイリオ"
    Cells(4, 11).Font.Name = "メイリオ"
    Cells(4, 12).Font.Name = "メイリオ"
    Cells(4, 13).Font.Name = "メイリオ"
end Function
Function revival1()
    Cells(4, 14).Font.Name = "メイリオ"
    Cells(4, 15).Font.Name = "メイリオ"
    Cells(4, 16).Font.Name = "メイリオ"
    Cells(5, 1).Font.Size = 18
    Cells(5, 1).Font.Name = "メイリオ"
    Cells(5, 1).Font.Bold = True
    Cells(5, 2) = "ファイル名を条件にかける際、拡張子を含むかどうかの指定も可。"
    Cells(5, 2).Font.Name = "メイリオ"
    Cells(5, 2).Font.Bold = True
    Cells(5, 2).HorizontalAlignment = -4131
    Cells(5, 2).IndentLevel = 1
    Cells(5, 3).Font.Name = "メイリオ"
    Cells(5, 4).Font.Name = "メイリオ"
    Cells(5, 5).Font.Name = "メイリオ"
    Cells(5, 6).Font.Name = "メイリオ"
    Cells(5, 7).Font.Name = "メイリオ"
    Cells(5, 8).Font.Name = "メイリオ"
    Cells(5, 9).Font.Name = "メイリオ"
    Cells(5, 10).Font.Name = "メイリオ"
    Cells(5, 11).Font.Name = "メイリオ"
    Cells(5, 12).Font.Name = "メイリオ"
    Cells(5, 13).Font.Name = "メイリオ"
    Cells(5, 14).Font.Name = "メイリオ"
    Cells(5, 15).Font.Name = "メイリオ"
    Cells(5, 16).Font.Name = "メイリオ"
    Cells(6, 1).Font.Size = 18
    Cells(6, 1).Font.Name = "メイリオ"
    Cells(6, 1).Font.Bold = True
    Cells(6, 2) = "ファイルのコピー時にブランクで置換したい文字列も指定できる。"
    Cells(6, 2).Font.Name = "メイリオ"
    Cells(6, 2).Font.Bold = True
    Cells(6, 2).HorizontalAlignment = -4131
    Cells(6, 2).IndentLevel = 1
    Cells(6, 3).Font.Name = "メイリオ"
    Cells(6, 4).Font.Name = "メイリオ"
    Cells(6, 5).Font.Name = "メイリオ"
    Cells(6, 6).Font.Name = "メイリオ"
    Cells(6, 7).Font.Name = "メイリオ"
    Cells(6, 8).Font.Name = "メイリオ"
    Cells(6, 9).Font.Name = "メイリオ"
    Cells(6, 10).Font.Name = "メイリオ"
    Cells(6, 11).Font.Name = "メイリオ"
end Function
Function revival2()
    Cells(6, 12).Font.Name = "メイリオ"
    Cells(6, 13).Font.Name = "メイリオ"
    Cells(6, 14).Font.Name = "メイリオ"
    Cells(6, 15).Font.Name = "メイリオ"
    Cells(6, 16).Font.Name = "メイリオ"
    Cells(7, 1).Font.Size = 18
    Cells(7, 1).Font.Name = "メイリオ"
    Cells(7, 1).Font.Bold = True
    Cells(7, 2) = "仕分け方法の条件はファイル名に対して複数パターン指定できる。処理対象ファイルが重複する場合は上書きされる点、要注意（次への課題かな・・）。"
    Cells(7, 2).Font.Name = "メイリオ"
    Cells(7, 2).Font.Bold = True
    Cells(7, 2).HorizontalAlignment = -4131
    Cells(7, 2).IndentLevel = 1
    Cells(7, 3).Font.Name = "メイリオ"
    Cells(7, 4).Font.Name = "メイリオ"
    Cells(7, 5).Font.Name = "メイリオ"
    Cells(7, 6).Font.Name = "メイリオ"
    Cells(7, 7).Font.Name = "メイリオ"
    Cells(7, 8).Font.Name = "メイリオ"
    Cells(7, 9).Font.Name = "メイリオ"
    Cells(7, 10).Font.Name = "メイリオ"
    Cells(7, 11).Font.Name = "メイリオ"
    Cells(7, 12).Font.Name = "メイリオ"
    Cells(7, 13).Font.Name = "メイリオ"
    Cells(7, 14).Font.Name = "メイリオ"
    Cells(7, 15).Font.Name = "メイリオ"
    Cells(7, 16).Font.Name = "メイリオ"
    Cells(8, 1).Font.Size = 18
    Cells(8, 1).Font.Name = "メイリオ"
    Cells(8, 1).Font.Bold = True
    Cells(8, 2) = "エラーチェックはしていないから、無理めなINPUTで実行するとだいたい落ちる。要注意。"
    Cells(8, 2).Font.Name = "メイリオ"
    Cells(8, 2).Font.Bold = True
    Cells(8, 2).HorizontalAlignment = -4131
    Cells(8, 2).IndentLevel = 1
    Cells(8, 3).Font.Name = "メイリオ"
    Cells(8, 4).Font.Name = "メイリオ"
    Cells(8, 5).Font.Name = "メイリオ"
    Cells(8, 6).Font.Name = "メイリオ"
    Cells(8, 7).Font.Name = "メイリオ"
    Cells(8, 8).Font.Name = "メイリオ"
    Cells(8, 9).Font.Name = "メイリオ"
end Function
Function revival3()
    Cells(8, 10).Font.Name = "メイリオ"
    Cells(8, 11).Font.Name = "メイリオ"
    Cells(8, 12).Font.Name = "メイリオ"
    Cells(8, 13).Font.Name = "メイリオ"
    Cells(8, 14).Font.Name = "メイリオ"
    Cells(8, 15).Font.Name = "メイリオ"
    Cells(8, 16).Font.Name = "メイリオ"
    Cells(9, 1).Font.Size = 18
    Cells(9, 1).Font.Name = "メイリオ"
    Cells(9, 1).Font.Bold = True
    Cells(9, 2).Font.Name = "メイリオ"
    Cells(9, 2).Font.Bold = True
    Cells(9, 2).HorizontalAlignment = -4131
    Cells(9, 2).IndentLevel = 1
    Cells(9, 3).Font.Name = "メイリオ"
    Cells(9, 4).Font.Name = "メイリオ"
    Cells(9, 5).Font.Name = "メイリオ"
    Cells(9, 6).Font.Name = "メイリオ"
    Cells(9, 7).Font.Name = "メイリオ"
    Cells(9, 8).Font.Name = "メイリオ"
    Cells(9, 9).Font.Name = "メイリオ"
    Cells(9, 10).Font.Name = "メイリオ"
    Cells(9, 11).Font.Name = "メイリオ"
    Cells(9, 12).Font.Name = "メイリオ"
    Cells(9, 13).Font.Name = "メイリオ"
    Cells(9, 14).Font.Name = "メイリオ"
    Cells(9, 15).Font.Name = "メイリオ"
    Cells(9, 16).Font.Name = "メイリオ"
    Cells(10, 1).Font.Size = 18
    Cells(10, 1).Font.Name = "メイリオ"
    Cells(10, 1).Font.Bold = True
    Cells(10, 2).Font.Name = "メイリオ"
    Cells(10, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 2).Borders(xlEdgeBottom).color = 0
    Cells(10, 2).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 3).Font.Name = "メイリオ"
    Cells(10, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeBottom).color = 0
    Cells(10, 3).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 4).Font.Name = "メイリオ"
    Cells(10, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeBottom).color = 0
    Cells(10, 4).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 5).Font.Name = "メイリオ"
    Cells(10, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeBottom).color = 0
    Cells(10, 5).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 6).Font.Name = "メイリオ"
    Cells(10, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeBottom).color = 0
    Cells(10, 6).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 7).Font.Name = "メイリオ"
    Cells(10, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 7).Borders(xlEdgeBottom).color = 0
    Cells(10, 7).Borders(xlEdgeBottom).weight = -4138
end Function
Function revival4()
    Cells(10, 8).Font.Name = "メイリオ"
    Cells(10, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 8).Borders(xlEdgeBottom).color = 0
    Cells(10, 8).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 9).Font.Name = "メイリオ"
    Cells(10, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 9).Borders(xlEdgeBottom).color = 0
    Cells(10, 9).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 10).Font.Name = "メイリオ"
    Cells(10, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 10).Borders(xlEdgeBottom).color = 0
    Cells(10, 10).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 11).Font.Name = "メイリオ"
    Cells(10, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 11).Borders(xlEdgeBottom).color = 0
    Cells(10, 11).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 12).Font.Name = "メイリオ"
    Cells(10, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 12).Borders(xlEdgeBottom).color = 0
    Cells(10, 12).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 13).Font.Name = "メイリオ"
    Cells(10, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 13).Borders(xlEdgeBottom).color = 0
    Cells(10, 13).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 14).Font.Name = "メイリオ"
    Cells(10, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 14).Borders(xlEdgeBottom).color = 0
    Cells(10, 14).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 15).Font.Name = "メイリオ"
    Cells(10, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 15).Borders(xlEdgeBottom).color = 0
    Cells(10, 15).Borders(xlEdgeBottom).weight = -4138
    Cells(10, 16).Font.Name = "メイリオ"
    Cells(10, 16).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 16).Borders(xlEdgeBottom).color = 0
    Cells(10, 16).Borders(xlEdgeBottom).weight = -4138
    Cells(11, 1).Font.Size = 18
    Cells(11, 1).Font.Name = "メイリオ"
    Cells(11, 1).Font.Bold = True
    Cells(11, 2) = "■基本情報"
    Cells(11, 2).Font.Name = "メイリオ"
    Cells(11, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 2).Borders(xlEdgeTop).color = 0
    Cells(11, 2).Borders(xlEdgeTop).weight = -4138
    Cells(11, 3).Font.Name = "メイリオ"
    Cells(11, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 3).Borders(xlEdgeTop).color = 0
    Cells(11, 3).Borders(xlEdgeTop).weight = -4138
    Cells(11, 4).Font.Name = "メイリオ"
    Cells(11, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 4).Borders(xlEdgeTop).color = 0
    Cells(11, 4).Borders(xlEdgeTop).weight = -4138
    Cells(11, 5).Font.Name = "メイリオ"
    Cells(11, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 5).Borders(xlEdgeTop).color = 0
    Cells(11, 5).Borders(xlEdgeTop).weight = -4138
    Cells(11, 6).Font.Name = "メイリオ"
    Cells(11, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 6).Borders(xlEdgeTop).color = 0
    Cells(11, 6).Borders(xlEdgeTop).weight = -4138
    Cells(11, 7).Font.Name = "メイリオ"
    Cells(11, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 7).Borders(xlEdgeTop).color = 0
    Cells(11, 7).Borders(xlEdgeTop).weight = -4138
    Cells(11, 8).Font.Name = "メイリオ"
    Cells(11, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 8).Borders(xlEdgeTop).color = 0
    Cells(11, 8).Borders(xlEdgeTop).weight = -4138
    Cells(11, 9).Font.Name = "メイリオ"
    Cells(11, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 9).Borders(xlEdgeTop).color = 0
    Cells(11, 9).Borders(xlEdgeTop).weight = -4138
    Cells(11, 10).Font.Name = "メイリオ"
    Cells(11, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 10).Borders(xlEdgeTop).color = 0
    Cells(11, 10).Borders(xlEdgeTop).weight = -4138
    Cells(11, 11).Font.Name = "メイリオ"
    Cells(11, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 11).Borders(xlEdgeTop).color = 0
    Cells(11, 11).Borders(xlEdgeTop).weight = -4138
    Cells(11, 12).Font.Name = "メイリオ"
    Cells(11, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 12).Borders(xlEdgeTop).color = 0
    Cells(11, 12).Borders(xlEdgeTop).weight = -4138
    Cells(11, 13).Font.Name = "メイリオ"
    Cells(11, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 13).Borders(xlEdgeTop).color = 0
    Cells(11, 13).Borders(xlEdgeTop).weight = -4138
    Cells(11, 14).Font.Name = "メイリオ"
    Cells(11, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 14).Borders(xlEdgeTop).color = 0
    Cells(11, 14).Borders(xlEdgeTop).weight = -4138
    Cells(11, 15).Font.Name = "メイリオ"
    Cells(11, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 15).Borders(xlEdgeTop).color = 0
    Cells(11, 15).Borders(xlEdgeTop).weight = -4138
    Cells(11, 16).Font.Name = "メイリオ"
    Cells(11, 16).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 16).Borders(xlEdgeTop).color = 0
    Cells(11, 16).Borders(xlEdgeTop).weight = -4138
    Cells(12, 1).Font.Size = 18
    Cells(12, 1).Font.Name = "メイリオ"
    Cells(12, 1).Font.Bold = True
    Cells(12, 2).Font.Name = "メイリオ"
    Cells(12, 3).Font.Name = "メイリオ"
    Cells(12, 4).Font.Name = "メイリオ"
    Cells(12, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeBottom).color = 0
    Cells(12, 4).Borders(xlEdgeBottom).weight = 2
    Cells(12, 5).Font.Name = "メイリオ"
    Cells(12, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeBottom).color = 0
    Cells(12, 5).Borders(xlEdgeBottom).weight = 2
end Function
Function revival5()
    Cells(12, 6).Font.Name = "メイリオ"
    Cells(12, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeBottom).color = 0
    Cells(12, 6).Borders(xlEdgeBottom).weight = 2
    Cells(12, 7).Font.Name = "メイリオ"
    Cells(12, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 7).Borders(xlEdgeBottom).color = 0
    Cells(12, 7).Borders(xlEdgeBottom).weight = 2
    Cells(12, 8).Font.Name = "メイリオ"
    Cells(12, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 8).Borders(xlEdgeBottom).color = 0
    Cells(12, 8).Borders(xlEdgeBottom).weight = 2
    Cells(12, 9).Font.Name = "メイリオ"
    Cells(12, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 9).Borders(xlEdgeBottom).color = 0
    Cells(12, 9).Borders(xlEdgeBottom).weight = 2
    Cells(12, 10).Font.Name = "メイリオ"
    Cells(12, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 10).Borders(xlEdgeBottom).color = 0
    Cells(12, 10).Borders(xlEdgeBottom).weight = 2
    Cells(12, 11).Font.Name = "メイリオ"
    Cells(12, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 11).Borders(xlEdgeBottom).color = 0
    Cells(12, 11).Borders(xlEdgeBottom).weight = 2
    Cells(12, 12).Font.Name = "メイリオ"
    Cells(12, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 12).Borders(xlEdgeBottom).color = 0
    Cells(12, 12).Borders(xlEdgeBottom).weight = 2
    Cells(12, 13).Font.Name = "メイリオ"
    Cells(12, 14).Font.Name = "メイリオ"
    Cells(12, 15).Font.Name = "メイリオ"
    Cells(12, 16).Font.Name = "メイリオ"
    Cells(13, 1).Font.Name = "メイリオ"
    Cells(13, 2).Font.Name = "メイリオ"
    Cells(13, 3) = "元フォルダ："
    Cells(13, 3).Font.Name = "メイリオ"
    Cells(13, 3).HorizontalAlignment = -4152
    Cells(13, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 3).Borders(xlEdgeRight).color = 0
    Cells(13, 3).Borders(xlEdgeRight).weight = 2
    Cells(13, 4).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeTop).color = 0
    Cells(13, 4).Borders(xlEdgeTop).weight = 2
    Cells(13, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeBottom).color = 0
    Cells(13, 4).Borders(xlEdgeBottom).weight = 2
    Cells(13, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeLeft).color = 0
    Cells(13, 4).Borders(xlEdgeLeft).weight = 2
    Cells(13, 5).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 5).Borders(xlEdgeTop).color = 0
    Cells(13, 5).Borders(xlEdgeTop).weight = 2
    Cells(13, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 5).Borders(xlEdgeBottom).color = 0
    Cells(13, 5).Borders(xlEdgeBottom).weight = 2
    Cells(13, 6).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 6).Borders(xlEdgeTop).color = 0
    Cells(13, 6).Borders(xlEdgeTop).weight = 2
    Cells(13, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 6).Borders(xlEdgeBottom).color = 0
    Cells(13, 6).Borders(xlEdgeBottom).weight = 2
    Cells(13, 7).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 7).Borders(xlEdgeTop).color = 0
    Cells(13, 7).Borders(xlEdgeTop).weight = 2
    Cells(13, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 7).Borders(xlEdgeBottom).color = 0
    Cells(13, 7).Borders(xlEdgeBottom).weight = 2
    Cells(13, 8).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 8).Borders(xlEdgeTop).color = 0
    Cells(13, 8).Borders(xlEdgeTop).weight = 2
    Cells(13, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 8).Borders(xlEdgeBottom).color = 0
    Cells(13, 8).Borders(xlEdgeBottom).weight = 2
    Cells(13, 9).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 9).Borders(xlEdgeTop).color = 0
    Cells(13, 9).Borders(xlEdgeTop).weight = 2
    Cells(13, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 9).Borders(xlEdgeBottom).color = 0
    Cells(13, 9).Borders(xlEdgeBottom).weight = 2
    Cells(13, 10).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 10).Borders(xlEdgeTop).color = 0
    Cells(13, 10).Borders(xlEdgeTop).weight = 2
    Cells(13, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 10).Borders(xlEdgeBottom).color = 0
    Cells(13, 10).Borders(xlEdgeBottom).weight = 2
    Cells(13, 11).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 11).Borders(xlEdgeTop).color = 0
    Cells(13, 11).Borders(xlEdgeTop).weight = 2
    Cells(13, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 11).Borders(xlEdgeBottom).color = 0
    Cells(13, 11).Borders(xlEdgeBottom).weight = 2
    Cells(13, 12).Font.Name = "メイリオ"
    Range("D13:L13").Merge
    Cells(13, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 12).Borders(xlEdgeTop).color = 0
    Cells(13, 12).Borders(xlEdgeTop).weight = 2
    Cells(13, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 12).Borders(xlEdgeBottom).color = 0
    Cells(13, 12).Borders(xlEdgeBottom).weight = 2
    Cells(13, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 12).Borders(xlEdgeRight).color = 0
    Cells(13, 12).Borders(xlEdgeRight).weight = 2
    Cells(13, 13).Font.Name = "メイリオ"
    Cells(13, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 13).Borders(xlEdgeLeft).color = 0
    Cells(13, 13).Borders(xlEdgeLeft).weight = 2
    Cells(13, 14).Font.Name = "メイリオ"
    Cells(13, 15).Font.Name = "メイリオ"
    Cells(13, 16).Font.Name = "メイリオ"
    Cells(14, 1).Font.Name = "メイリオ"
    Cells(14, 2).Font.Name = "メイリオ"
    Cells(14, 3) = "先フォルダ："
    Cells(14, 3).Font.Name = "メイリオ"
    Cells(14, 3).HorizontalAlignment = -4152
    Cells(14, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 3).Borders(xlEdgeRight).color = 0
    Cells(14, 3).Borders(xlEdgeRight).weight = 2
end Function
Function revival6()
    Cells(14, 4).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeTop).color = 0
    Cells(14, 4).Borders(xlEdgeTop).weight = 2
    Cells(14, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeBottom).color = 0
    Cells(14, 4).Borders(xlEdgeBottom).weight = 2
    Cells(14, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeLeft).color = 0
    Cells(14, 4).Borders(xlEdgeLeft).weight = 2
    Cells(14, 5).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 5).Borders(xlEdgeTop).color = 0
    Cells(14, 5).Borders(xlEdgeTop).weight = 2
    Cells(14, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 5).Borders(xlEdgeBottom).color = 0
    Cells(14, 5).Borders(xlEdgeBottom).weight = 2
    Cells(14, 6).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 6).Borders(xlEdgeTop).color = 0
    Cells(14, 6).Borders(xlEdgeTop).weight = 2
    Cells(14, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 6).Borders(xlEdgeBottom).color = 0
    Cells(14, 6).Borders(xlEdgeBottom).weight = 2
    Cells(14, 7).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 7).Borders(xlEdgeTop).color = 0
    Cells(14, 7).Borders(xlEdgeTop).weight = 2
    Cells(14, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 7).Borders(xlEdgeBottom).color = 0
    Cells(14, 7).Borders(xlEdgeBottom).weight = 2
    Cells(14, 8).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 8).Borders(xlEdgeTop).color = 0
    Cells(14, 8).Borders(xlEdgeTop).weight = 2
    Cells(14, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 8).Borders(xlEdgeBottom).color = 0
    Cells(14, 8).Borders(xlEdgeBottom).weight = 2
    Cells(14, 9).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 9).Borders(xlEdgeTop).color = 0
    Cells(14, 9).Borders(xlEdgeTop).weight = 2
    Cells(14, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 9).Borders(xlEdgeBottom).color = 0
    Cells(14, 9).Borders(xlEdgeBottom).weight = 2
    Cells(14, 10).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 10).Borders(xlEdgeTop).color = 0
    Cells(14, 10).Borders(xlEdgeTop).weight = 2
    Cells(14, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 10).Borders(xlEdgeBottom).color = 0
    Cells(14, 10).Borders(xlEdgeBottom).weight = 2
    Cells(14, 11).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 11).Borders(xlEdgeTop).color = 0
    Cells(14, 11).Borders(xlEdgeTop).weight = 2
    Cells(14, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 11).Borders(xlEdgeBottom).color = 0
    Cells(14, 11).Borders(xlEdgeBottom).weight = 2
    Cells(14, 12).Font.Name = "メイリオ"
    Range("D14:L14").Merge
    Cells(14, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 12).Borders(xlEdgeTop).color = 0
    Cells(14, 12).Borders(xlEdgeTop).weight = 2
    Cells(14, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 12).Borders(xlEdgeBottom).color = 0
    Cells(14, 12).Borders(xlEdgeBottom).weight = 2
    Cells(14, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 12).Borders(xlEdgeRight).color = 0
    Cells(14, 12).Borders(xlEdgeRight).weight = 2
    Cells(14, 13).Font.Name = "メイリオ"
    Cells(14, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 13).Borders(xlEdgeLeft).color = 0
    Cells(14, 13).Borders(xlEdgeLeft).weight = 2
    Cells(14, 14).Font.Name = "メイリオ"
    Cells(14, 15).Font.Name = "メイリオ"
    Cells(14, 16).Font.Name = "メイリオ"
    Cells(15, 1).Font.Name = "メイリオ"
    Cells(15, 2).Font.Name = "メイリオ"
    Cells(15, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 2).Borders(xlEdgeBottom).color = 0
    Cells(15, 2).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 3).Font.Name = "メイリオ"
    Cells(15, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 3).Borders(xlEdgeBottom).color = 0
    Cells(15, 3).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 4).Font.Name = "メイリオ"
    Cells(15, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 4).Borders(xlEdgeTop).color = 0
    Cells(15, 4).Borders(xlEdgeTop).weight = 2
    Cells(15, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 4).Borders(xlEdgeBottom).color = 0
    Cells(15, 4).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 5).Font.Name = "メイリオ"
    Cells(15, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 5).Borders(xlEdgeTop).color = 0
    Cells(15, 5).Borders(xlEdgeTop).weight = 2
    Cells(15, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 5).Borders(xlEdgeBottom).color = 0
    Cells(15, 5).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 6).Font.Name = "メイリオ"
    Cells(15, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 6).Borders(xlEdgeTop).color = 0
    Cells(15, 6).Borders(xlEdgeTop).weight = 2
    Cells(15, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 6).Borders(xlEdgeBottom).color = 0
    Cells(15, 6).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 7).Font.Name = "メイリオ"
    Cells(15, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 7).Borders(xlEdgeTop).color = 0
    Cells(15, 7).Borders(xlEdgeTop).weight = 2
    Cells(15, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 7).Borders(xlEdgeBottom).color = 0
    Cells(15, 7).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 8).Font.Name = "メイリオ"
    Cells(15, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 8).Borders(xlEdgeTop).color = 0
    Cells(15, 8).Borders(xlEdgeTop).weight = 2
    Cells(15, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 8).Borders(xlEdgeBottom).color = 0
    Cells(15, 8).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 9).Font.Name = "メイリオ"
    Cells(15, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 9).Borders(xlEdgeTop).color = 0
    Cells(15, 9).Borders(xlEdgeTop).weight = 2
    Cells(15, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 9).Borders(xlEdgeBottom).color = 0
    Cells(15, 9).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 10).Font.Name = "メイリオ"
    Cells(15, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 10).Borders(xlEdgeTop).color = 0
    Cells(15, 10).Borders(xlEdgeTop).weight = 2
    Cells(15, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 10).Borders(xlEdgeBottom).color = 0
    Cells(15, 10).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 11).Font.Name = "メイリオ"
    Cells(15, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 11).Borders(xlEdgeTop).color = 0
    Cells(15, 11).Borders(xlEdgeTop).weight = 2
    Cells(15, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 11).Borders(xlEdgeBottom).color = 0
    Cells(15, 11).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 12).Font.Name = "メイリオ"
    Cells(15, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 12).Borders(xlEdgeTop).color = 0
    Cells(15, 12).Borders(xlEdgeTop).weight = 2
    Cells(15, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 12).Borders(xlEdgeBottom).color = 0
    Cells(15, 12).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 13).Font.Name = "メイリオ"
    Cells(15, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 13).Borders(xlEdgeBottom).color = 0
    Cells(15, 13).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 14).Font.Name = "メイリオ"
    Cells(15, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 14).Borders(xlEdgeBottom).color = 0
    Cells(15, 14).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 15).Font.Name = "メイリオ"
    Cells(15, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 15).Borders(xlEdgeBottom).color = 0
    Cells(15, 15).Borders(xlEdgeBottom).weight = -4138
    Cells(15, 16).Font.Name = "メイリオ"
    Cells(15, 16).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 16).Borders(xlEdgeBottom).color = 0
    Cells(15, 16).Borders(xlEdgeBottom).weight = -4138
    Cells(16, 1).Font.Name = "メイリオ"
end Function
Function revival7()
    Cells(16, 2) = "■共通オプション"
    Cells(16, 2).Font.Name = "メイリオ"
    Cells(16, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 2).Borders(xlEdgeTop).color = 0
    Cells(16, 2).Borders(xlEdgeTop).weight = -4138
    Cells(16, 3).Font.Name = "メイリオ"
    Cells(16, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 3).Borders(xlEdgeTop).color = 0
    Cells(16, 3).Borders(xlEdgeTop).weight = -4138
    Cells(16, 4).Font.Name = "メイリオ"
    Cells(16, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 4).Borders(xlEdgeTop).color = 0
    Cells(16, 4).Borders(xlEdgeTop).weight = -4138
    Cells(16, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 4).Borders(xlEdgeBottom).color = 0
    Cells(16, 4).Borders(xlEdgeBottom).weight = 2
    Cells(16, 5).Font.Name = "メイリオ"
    Cells(16, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 5).Borders(xlEdgeTop).color = 0
    Cells(16, 5).Borders(xlEdgeTop).weight = -4138
    Cells(16, 6).Font.Name = "メイリオ"
    Cells(16, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 6).Borders(xlEdgeTop).color = 0
    Cells(16, 6).Borders(xlEdgeTop).weight = -4138
    Cells(16, 7).Font.Name = "メイリオ"
    Cells(16, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 7).Borders(xlEdgeTop).color = 0
    Cells(16, 7).Borders(xlEdgeTop).weight = -4138
    Cells(16, 8).Font.Name = "メイリオ"
    Cells(16, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 8).Borders(xlEdgeTop).color = 0
    Cells(16, 8).Borders(xlEdgeTop).weight = -4138
    Cells(16, 9).Font.Name = "メイリオ"
    Cells(16, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 9).Borders(xlEdgeTop).color = 0
    Cells(16, 9).Borders(xlEdgeTop).weight = -4138
    Cells(16, 10).Font.Name = "メイリオ"
    Cells(16, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 10).Borders(xlEdgeTop).color = 0
    Cells(16, 10).Borders(xlEdgeTop).weight = -4138
    Cells(16, 11).Font.Name = "メイリオ"
    Cells(16, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 11).Borders(xlEdgeTop).color = 0
    Cells(16, 11).Borders(xlEdgeTop).weight = -4138
    Cells(16, 12).Font.Name = "メイリオ"
    Cells(16, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 12).Borders(xlEdgeTop).color = 0
    Cells(16, 12).Borders(xlEdgeTop).weight = -4138
    Cells(16, 13).Font.Name = "メイリオ"
    Cells(16, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 13).Borders(xlEdgeTop).color = 0
    Cells(16, 13).Borders(xlEdgeTop).weight = -4138
    Cells(16, 14).Font.Name = "メイリオ"
    Cells(16, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 14).Borders(xlEdgeTop).color = 0
    Cells(16, 14).Borders(xlEdgeTop).weight = -4138
    Cells(16, 15).Font.Name = "メイリオ"
    Cells(16, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 15).Borders(xlEdgeTop).color = 0
    Cells(16, 15).Borders(xlEdgeTop).weight = -4138
    Cells(16, 16).Font.Name = "メイリオ"
    Cells(16, 16).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 16).Borders(xlEdgeTop).color = 0
    Cells(16, 16).Borders(xlEdgeTop).weight = -4138
    Cells(17, 1).Font.Name = "メイリオ"
    Cells(17, 2).Font.Name = "メイリオ"
    Cells(17, 3) = "再帰処理："
    Cells(17, 3).Font.Name = "メイリオ"
    Cells(17, 3).HorizontalAlignment = -4152
    Cells(17, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 3).Borders(xlEdgeRight).color = 0
    Cells(17, 3).Borders(xlEdgeRight).weight = 2
    Cells(17, 4).Font.Name = "メイリオ"
    Cells(17, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeTop).color = 0
    Cells(17, 4).Borders(xlEdgeTop).weight = 2
    Cells(17, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeBottom).color = 0
    Cells(17, 4).Borders(xlEdgeBottom).weight = 2
    Cells(17, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeLeft).color = 0
    Cells(17, 4).Borders(xlEdgeLeft).weight = 2
    Cells(17, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeRight).color = 0
    Cells(17, 4).Borders(xlEdgeRight).weight = 2
    Cells(17, 4).Validation.Delete
    Cells(17, 4).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="する,しない"
    Cells(17, 5) = "子フォルダも対象とするかどうか"
    Cells(17, 5).Font.Size = 10
    Cells(17, 5).Font.Name = "メイリオ"
    Cells(17, 5).Font.Color = 8421504
    Cells(17, 5).HorizontalAlignment = -4131
    Cells(17, 5).IndentLevel = 1
    Cells(17, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 5).Borders(xlEdgeLeft).color = 0
    Cells(17, 5).Borders(xlEdgeLeft).weight = 2
    Cells(17, 6).Font.Name = "メイリオ"
    Cells(17, 7).Font.Name = "メイリオ"
    Cells(17, 8).Font.Name = "メイリオ"
    Cells(17, 9).Font.Name = "メイリオ"
    Cells(17, 10).Font.Name = "メイリオ"
    Cells(17, 11).Font.Name = "メイリオ"
    Cells(17, 12).Font.Name = "メイリオ"
    Cells(17, 13).Font.Name = "メイリオ"
    Cells(17, 14).Font.Name = "メイリオ"
    Cells(17, 15).Font.Name = "メイリオ"
end Function
Function revival8()
    Cells(17, 16).Font.Name = "メイリオ"
    Cells(18, 1).Font.Name = "メイリオ"
    Cells(18, 2).Font.Name = "メイリオ"
    Cells(18, 3) = "ログの出力："
    Cells(18, 3).Font.Name = "メイリオ"
    Cells(18, 3).HorizontalAlignment = -4152
    Cells(18, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 3).Borders(xlEdgeRight).color = 0
    Cells(18, 3).Borders(xlEdgeRight).weight = 2
    Cells(18, 4) = "する"
    Cells(18, 4).Font.Name = "メイリオ"
    Cells(18, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeTop).color = 0
    Cells(18, 4).Borders(xlEdgeTop).weight = 2
    Cells(18, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeBottom).color = 0
    Cells(18, 4).Borders(xlEdgeBottom).weight = 2
    Cells(18, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeLeft).color = 0
    Cells(18, 4).Borders(xlEdgeLeft).weight = 2
    Cells(18, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeRight).color = 0
    Cells(18, 4).Borders(xlEdgeRight).weight = 2
    Cells(18, 4).Validation.Delete
    Cells(18, 4).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="する,しない"
    Cells(18, 5) = "「する」にしておいてくれ・・。処理時間を縮めたいときに「しない」にする"
    Cells(18, 5).Font.Size = 10
    Cells(18, 5).Font.Name = "メイリオ"
    Cells(18, 5).Font.Color = 8421504
    Cells(18, 5).HorizontalAlignment = -4131
    Cells(18, 5).IndentLevel = 1
    Cells(18, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 5).Borders(xlEdgeLeft).color = 0
    Cells(18, 5).Borders(xlEdgeLeft).weight = 2
    Cells(18, 6).Font.Name = "メイリオ"
    Cells(18, 7).Font.Name = "メイリオ"
    Cells(18, 8).Font.Name = "メイリオ"
    Cells(18, 9).Font.Name = "メイリオ"
    Cells(18, 10).Font.Name = "メイリオ"
    Cells(18, 11).Font.Name = "メイリオ"
    Cells(18, 12).Font.Name = "メイリオ"
    Cells(18, 13).Font.Name = "メイリオ"
    Cells(18, 14).Font.Name = "メイリオ"
    Cells(18, 15).Font.Name = "メイリオ"
    Cells(18, 16).Font.Name = "メイリオ"
    Cells(19, 1).Font.Name = "メイリオ"
    Cells(19, 2).Font.Name = "メイリオ"
    Cells(19, 3) = "対象ファイル形式："
    Cells(19, 3).Font.Name = "メイリオ"
    Cells(19, 3).HorizontalAlignment = -4152
    Cells(19, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(19, 3).Borders(xlEdgeRight).color = 0
    Cells(19, 3).Borders(xlEdgeRight).weight = 2
    Cells(19, 4).Font.Name = "メイリオ"
    Cells(19, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 4).Borders(xlEdgeTop).color = 0
    Cells(19, 4).Borders(xlEdgeTop).weight = 2
    Cells(19, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(19, 4).Borders(xlEdgeBottom).color = 0
    Cells(19, 4).Borders(xlEdgeBottom).weight = 2
    Cells(19, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(19, 4).Borders(xlEdgeLeft).color = 0
    Cells(19, 4).Borders(xlEdgeLeft).weight = 2
    Cells(19, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(19, 4).Borders(xlEdgeRight).color = 0
    Cells(19, 4).Borders(xlEdgeRight).weight = 2
    Cells(19, 5) = "ドットは不要（例：xlsx）。未指定の場合すべて対象。複数指定時はカンマ区切りでスペースは不要"
    Cells(19, 5).Font.Size = 10
    Cells(19, 5).Font.Name = "メイリオ"
    Cells(19, 5).Font.Color = 8421504
    Cells(19, 5).HorizontalAlignment = -4131
    Cells(19, 5).IndentLevel = 1
    Cells(19, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(19, 5).Borders(xlEdgeLeft).color = 0
    Cells(19, 5).Borders(xlEdgeLeft).weight = 2
    Cells(19, 6).Font.Name = "メイリオ"
    Cells(19, 7).Font.Name = "メイリオ"
    Cells(19, 8).Font.Name = "メイリオ"
    Cells(19, 9).Font.Name = "メイリオ"
    Cells(19, 10).Font.Name = "メイリオ"
    Cells(19, 11).Font.Name = "メイリオ"
    Cells(19, 12).Font.Name = "メイリオ"
    Cells(19, 13).Font.Name = "メイリオ"
end Function
Function revival9()
    Cells(19, 14).Font.Name = "メイリオ"
    Cells(19, 15).Font.Name = "メイリオ"
    Cells(19, 16).Font.Name = "メイリオ"
    Cells(20, 1).Font.Name = "メイリオ"
    Cells(20, 2).Font.Name = "メイリオ"
    Cells(20, 3) = "更新日時（FROM）："
    Cells(20, 3).Font.Name = "メイリオ"
    Cells(20, 3).HorizontalAlignment = -4152
    Cells(20, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(20, 3).Borders(xlEdgeRight).color = 0
    Cells(20, 3).Borders(xlEdgeRight).weight = 2
    Cells(20, 4).NumberFormatLocal = "yyyy/m/d h:mm"
    Cells(20, 4).Font.Name = "メイリオ"
    Cells(20, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(20, 4).Borders(xlEdgeTop).color = 0
    Cells(20, 4).Borders(xlEdgeTop).weight = 2
    Cells(20, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(20, 4).Borders(xlEdgeBottom).color = 0
    Cells(20, 4).Borders(xlEdgeBottom).weight = 2
    Cells(20, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(20, 4).Borders(xlEdgeLeft).color = 0
    Cells(20, 4).Borders(xlEdgeLeft).weight = 2
    Cells(20, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(20, 4).Borders(xlEdgeRight).color = 0
    Cells(20, 4).Borders(xlEdgeRight).weight = 2
    Cells(20, 5) = "左記の時間以降のファイルを対象とする。入力形式はyyyy/mm/dd hh:mm:ss"
    Cells(20, 5).Font.Size = 10
    Cells(20, 5).Font.Name = "メイリオ"
    Cells(20, 5).Font.Color = 8421504
    Cells(20, 5).HorizontalAlignment = -4131
    Cells(20, 5).IndentLevel = 1
    Cells(20, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(20, 5).Borders(xlEdgeLeft).color = 0
    Cells(20, 5).Borders(xlEdgeLeft).weight = 2
    Cells(20, 6).Font.Name = "メイリオ"
    Cells(20, 7).Font.Name = "メイリオ"
    Cells(20, 8).Font.Name = "メイリオ"
    Cells(20, 9).Font.Name = "メイリオ"
    Cells(20, 10).Font.Name = "メイリオ"
    Cells(20, 11).Font.Name = "メイリオ"
    Cells(20, 12).Font.Name = "メイリオ"
    Cells(20, 13).Font.Name = "メイリオ"
    Cells(20, 14).Font.Name = "メイリオ"
    Cells(20, 15).Font.Name = "メイリオ"
    Cells(20, 16).Font.Name = "メイリオ"
    Cells(21, 1).Font.Name = "メイリオ"
    Cells(21, 2).Font.Name = "メイリオ"
    Cells(21, 3) = "更新日時（TO）："
    Cells(21, 3).Font.Name = "メイリオ"
    Cells(21, 3).HorizontalAlignment = -4152
    Cells(21, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(21, 3).Borders(xlEdgeRight).color = 0
    Cells(21, 3).Borders(xlEdgeRight).weight = 2
    Cells(21, 4).NumberFormatLocal = "yyyy/m/d h:mm"
    Cells(21, 4).Font.Name = "メイリオ"
    Cells(21, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(21, 4).Borders(xlEdgeTop).color = 0
    Cells(21, 4).Borders(xlEdgeTop).weight = 2
    Cells(21, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(21, 4).Borders(xlEdgeBottom).color = 0
    Cells(21, 4).Borders(xlEdgeBottom).weight = 2
    Cells(21, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(21, 4).Borders(xlEdgeLeft).color = 0
    Cells(21, 4).Borders(xlEdgeLeft).weight = 2
    Cells(21, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(21, 4).Borders(xlEdgeRight).color = 0
    Cells(21, 4).Borders(xlEdgeRight).weight = 2
    Cells(21, 5) = "左記の時間以前のファイルを対象とする。入力形式はyyyy/mm/dd hh:mm:ss"
    Cells(21, 5).Font.Size = 10
    Cells(21, 5).Font.Name = "メイリオ"
    Cells(21, 5).Font.Color = 8421504
    Cells(21, 5).HorizontalAlignment = -4131
    Cells(21, 5).IndentLevel = 1
    Cells(21, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(21, 5).Borders(xlEdgeLeft).color = 0
    Cells(21, 5).Borders(xlEdgeLeft).weight = 2
    Cells(21, 6).Font.Name = "メイリオ"
    Cells(21, 7).Font.Name = "メイリオ"
    Cells(21, 8).Font.Name = "メイリオ"
    Cells(21, 9).Font.Name = "メイリオ"
    Cells(21, 10).Font.Name = "メイリオ"
    Cells(21, 11).Font.Name = "メイリオ"
end Function
Function revival10()
    Cells(21, 12).Font.Name = "メイリオ"
    Cells(21, 13).Font.Name = "メイリオ"
    Cells(21, 14).Font.Name = "メイリオ"
    Cells(21, 15).Font.Name = "メイリオ"
    Cells(21, 16).Font.Name = "メイリオ"
    Cells(22, 1).Font.Name = "メイリオ"
    Cells(22, 2).Font.Name = "メイリオ"
    Cells(22, 3) = "フォルダ構成再現："
    Cells(22, 3).Font.Name = "メイリオ"
    Cells(22, 3).HorizontalAlignment = -4152
    Cells(22, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(22, 3).Borders(xlEdgeRight).color = 0
    Cells(22, 3).Borders(xlEdgeRight).weight = 2
    Cells(22, 4) = "する"
    Cells(22, 4).Font.Name = "メイリオ"
    Cells(22, 4).Interior.Color = 0
    Cells(22, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(22, 4).Borders(xlEdgeTop).color = 0
    Cells(22, 4).Borders(xlEdgeTop).weight = 2
    Cells(22, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(22, 4).Borders(xlEdgeBottom).color = 0
    Cells(22, 4).Borders(xlEdgeBottom).weight = 2
    Cells(22, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(22, 4).Borders(xlEdgeLeft).color = 0
    Cells(22, 4).Borders(xlEdgeLeft).weight = 2
    Cells(22, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(22, 4).Borders(xlEdgeRight).color = 0
    Cells(22, 4).Borders(xlEdgeRight).weight = 2
    Cells(22, 4).Validation.Delete
    Cells(22, 4).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="する,しない"
    Cells(22, 5).Font.Size = 10
    Cells(22, 5).Font.Name = "メイリオ"
    Cells(22, 5).Font.Color = 8421504
    Cells(22, 5).HorizontalAlignment = -4131
    Cells(22, 5).IndentLevel = 1
    Cells(22, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(22, 5).Borders(xlEdgeLeft).color = 0
    Cells(22, 5).Borders(xlEdgeLeft).weight = 2
    Cells(22, 6).Font.Name = "メイリオ"
    Cells(22, 7).Font.Name = "メイリオ"
    Cells(22, 8).Font.Name = "メイリオ"
    Cells(22, 9).Font.Name = "メイリオ"
    Cells(22, 10).Font.Name = "メイリオ"
    Cells(22, 11).Font.Name = "メイリオ"
    Cells(22, 12).Font.Name = "メイリオ"
    Cells(22, 13).Font.Name = "メイリオ"
    Cells(22, 14).Font.Name = "メイリオ"
    Cells(22, 15).Font.Name = "メイリオ"
    Cells(22, 16).Font.Name = "メイリオ"
    Cells(23, 1).Font.Name = "メイリオ"
    Cells(23, 2).Font.Name = "メイリオ"
    Cells(23, 3) = "拡張子利用："
    Cells(23, 3).Font.Name = "メイリオ"
    Cells(23, 3).HorizontalAlignment = -4152
    Cells(23, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(23, 3).Borders(xlEdgeRight).color = 0
    Cells(23, 3).Borders(xlEdgeRight).weight = 2
    Cells(23, 4).Font.Name = "メイリオ"
    Cells(23, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(23, 4).Borders(xlEdgeTop).color = 0
    Cells(23, 4).Borders(xlEdgeTop).weight = 2
    Cells(23, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(23, 4).Borders(xlEdgeBottom).color = 0
    Cells(23, 4).Borders(xlEdgeBottom).weight = 2
    Cells(23, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(23, 4).Borders(xlEdgeLeft).color = 0
    Cells(23, 4).Borders(xlEdgeLeft).weight = 2
    Cells(23, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(23, 4).Borders(xlEdgeRight).color = 0
    Cells(23, 4).Borders(xlEdgeRight).weight = 2
    Cells(23, 4).Validation.Delete
    Cells(23, 4).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="する,しない"
    Cells(23, 5) = "対象ファイル条件のチェックにファイルの拡張子を含むかどうか"
    Cells(23, 5).Font.Size = 10
    Cells(23, 5).Font.Name = "メイリオ"
    Cells(23, 5).Font.Color = 8421504
    Cells(23, 5).HorizontalAlignment = -4131
    Cells(23, 5).IndentLevel = 1
    Cells(23, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(23, 5).Borders(xlEdgeLeft).color = 0
    Cells(23, 5).Borders(xlEdgeLeft).weight = 2
    Cells(23, 6).Font.Name = "メイリオ"
    Cells(23, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(23, 6).Borders(xlEdgeBottom).color = 0
    Cells(23, 6).Borders(xlEdgeBottom).weight = 2
    Cells(23, 7).Font.Name = "メイリオ"
    Cells(23, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(23, 7).Borders(xlEdgeBottom).color = 0
    Cells(23, 7).Borders(xlEdgeBottom).weight = 2
    Cells(23, 8).Font.Name = "メイリオ"
    Cells(23, 9).Font.Name = "メイリオ"
    Cells(23, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(23, 9).Borders(xlEdgeBottom).color = 0
    Cells(23, 9).Borders(xlEdgeBottom).weight = 2
end Function
Function revival11()
    Cells(23, 10).Font.Name = "メイリオ"
    Cells(23, 11).Font.Name = "メイリオ"
    Cells(23, 12).Font.Name = "メイリオ"
    Cells(23, 13).Font.Name = "メイリオ"
    Cells(23, 14).Font.Name = "メイリオ"
    Cells(23, 15).Font.Name = "メイリオ"
    Cells(23, 16).Font.Name = "メイリオ"
    Cells(24, 1).Font.Name = "メイリオ"
    Cells(24, 2).Font.Name = "メイリオ"
    Cells(24, 3) = "対象ファイル条件："
    Cells(24, 3).Font.Name = "メイリオ"
    Cells(24, 3).HorizontalAlignment = -4152
    Cells(24, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(24, 3).Borders(xlEdgeRight).color = 0
    Cells(24, 3).Borders(xlEdgeRight).weight = 2
    Cells(24, 4).Font.Name = "メイリオ"
    Cells(24, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(24, 4).Borders(xlEdgeTop).color = 0
    Cells(24, 4).Borders(xlEdgeTop).weight = 2
    Cells(24, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(24, 4).Borders(xlEdgeBottom).color = 0
    Cells(24, 4).Borders(xlEdgeBottom).weight = 2
    Cells(24, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(24, 4).Borders(xlEdgeLeft).color = 0
    Cells(24, 4).Borders(xlEdgeLeft).weight = 2
    Cells(24, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(24, 4).Borders(xlEdgeRight).color = 0
    Cells(24, 4).Borders(xlEdgeRight).weight = 2
    Cells(24, 5) = "→"
    Cells(24, 5).Font.Name = "メイリオ"
    Cells(24, 5).HorizontalAlignment = -4108
    Cells(24, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(24, 5).Borders(xlEdgeLeft).color = 0
    Cells(24, 5).Borders(xlEdgeLeft).weight = 2
    Cells(24, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(24, 5).Borders(xlEdgeRight).color = 0
    Cells(24, 5).Borders(xlEdgeRight).weight = 2
    Cells(24, 6).Font.Size = 9
    Cells(24, 6).Font.Name = "メイリオ"
    Range("F24:G24").Merge
    Cells(24, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(24, 6).Borders(xlEdgeTop).color = 0
    Cells(24, 6).Borders(xlEdgeTop).weight = 2
    Cells(24, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(24, 6).Borders(xlEdgeBottom).color = 0
    Cells(24, 6).Borders(xlEdgeBottom).weight = 2
    Cells(24, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(24, 6).Borders(xlEdgeLeft).color = 0
    Cells(24, 6).Borders(xlEdgeLeft).weight = 2
    Cells(24, 6).Validation.Delete
    Cells(24, 6).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(24, 7).Font.Size = 9
    Cells(24, 7).Font.Name = "メイリオ"
    Range("F24:G24").Merge
    Cells(24, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(24, 7).Borders(xlEdgeTop).color = 0
    Cells(24, 7).Borders(xlEdgeTop).weight = 2
    Cells(24, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(24, 7).Borders(xlEdgeBottom).color = 0
    Cells(24, 7).Borders(xlEdgeBottom).weight = 2
    Cells(24, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(24, 7).Borders(xlEdgeRight).color = 0
    Cells(24, 7).Borders(xlEdgeRight).weight = 2
    Cells(24, 7).Validation.Delete
    Cells(24, 7).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(24, 8).Font.Name = "メイリオ"
    Cells(24, 8).HorizontalAlignment = -4108
    Cells(24, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(24, 8).Borders(xlEdgeLeft).color = 0
    Cells(24, 8).Borders(xlEdgeLeft).weight = 2
    Cells(24, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(24, 8).Borders(xlEdgeRight).color = 0
    Cells(24, 8).Borders(xlEdgeRight).weight = 2
    Cells(24, 9).Font.Name = "メイリオ"
    Cells(24, 9).HorizontalAlignment = -4131
    Cells(24, 9).IndentLevel = 1
    Cells(24, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(24, 9).Borders(xlEdgeTop).color = 0
    Cells(24, 9).Borders(xlEdgeTop).weight = 2
    Cells(24, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(24, 9).Borders(xlEdgeBottom).color = 0
    Cells(24, 9).Borders(xlEdgeBottom).weight = 2
    Cells(24, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(24, 9).Borders(xlEdgeLeft).color = 0
    Cells(24, 9).Borders(xlEdgeLeft).weight = 2
    Cells(24, 9).Borders(xlEdgeRight).LineStyle = 1
    Cells(24, 9).Borders(xlEdgeRight).color = 0
    Cells(24, 9).Borders(xlEdgeRight).weight = 2
    Cells(24, 9).Validation.Delete
    Cells(24, 9).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="かつ,または"
    Cells(24, 10) = "未指定時はOR条件とする"
    Cells(24, 10).Font.Size = 10
    Cells(24, 10).Font.Name = "メイリオ"
    Cells(24, 10).Font.Color = 8421504
    Cells(24, 10).HorizontalAlignment = -4131
    Cells(24, 10).IndentLevel = 1
    Cells(24, 10).Borders(xlEdgeLeft).LineStyle = 1
    Cells(24, 10).Borders(xlEdgeLeft).color = 0
    Cells(24, 10).Borders(xlEdgeLeft).weight = 2
    Cells(24, 11).Font.Name = "メイリオ"
    Cells(24, 12).Font.Name = "メイリオ"
    Cells(24, 13).Font.Name = "メイリオ"
    Cells(24, 14).Font.Name = "メイリオ"
    Cells(24, 15).Font.Name = "メイリオ"
    Cells(24, 16).Font.Name = "メイリオ"
    Cells(25, 1).Font.Name = "メイリオ"
    Cells(25, 2).Font.Name = "メイリオ"
    Cells(25, 3).Font.Name = "メイリオ"
    Cells(25, 3).HorizontalAlignment = -4152
    Cells(25, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(25, 3).Borders(xlEdgeRight).color = 0
    Cells(25, 3).Borders(xlEdgeRight).weight = 2
    Cells(25, 4).Font.Name = "メイリオ"
    Cells(25, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(25, 4).Borders(xlEdgeTop).color = 0
    Cells(25, 4).Borders(xlEdgeTop).weight = 2
    Cells(25, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(25, 4).Borders(xlEdgeBottom).color = 0
    Cells(25, 4).Borders(xlEdgeBottom).weight = 2
    Cells(25, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(25, 4).Borders(xlEdgeLeft).color = 0
    Cells(25, 4).Borders(xlEdgeLeft).weight = 2
    Cells(25, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(25, 4).Borders(xlEdgeRight).color = 0
    Cells(25, 4).Borders(xlEdgeRight).weight = 2
    Cells(25, 5) = "→"
    Cells(25, 5).Font.Name = "メイリオ"
    Cells(25, 5).HorizontalAlignment = -4108
    Cells(25, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(25, 5).Borders(xlEdgeLeft).color = 0
    Cells(25, 5).Borders(xlEdgeLeft).weight = 2
    Cells(25, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(25, 5).Borders(xlEdgeRight).color = 0
    Cells(25, 5).Borders(xlEdgeRight).weight = 2
    Cells(25, 6).Font.Size = 9
    Cells(25, 6).Font.Name = "メイリオ"
    Range("F25:G25").Merge
    Cells(25, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(25, 6).Borders(xlEdgeTop).color = 0
    Cells(25, 6).Borders(xlEdgeTop).weight = 2
    Cells(25, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(25, 6).Borders(xlEdgeBottom).color = 0
    Cells(25, 6).Borders(xlEdgeBottom).weight = 2
    Cells(25, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(25, 6).Borders(xlEdgeLeft).color = 0
    Cells(25, 6).Borders(xlEdgeLeft).weight = 2
    Cells(25, 6).Validation.Delete
    Cells(25, 6).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(25, 7).Font.Size = 9
    Cells(25, 7).Font.Name = "メイリオ"
    Range("F25:G25").Merge
    Cells(25, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(25, 7).Borders(xlEdgeTop).color = 0
    Cells(25, 7).Borders(xlEdgeTop).weight = 2
    Cells(25, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(25, 7).Borders(xlEdgeBottom).color = 0
    Cells(25, 7).Borders(xlEdgeBottom).weight = 2
    Cells(25, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(25, 7).Borders(xlEdgeRight).color = 0
    Cells(25, 7).Borders(xlEdgeRight).weight = 2
    Cells(25, 7).Validation.Delete
    Cells(25, 7).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
end Function
Function revival12()
    Cells(25, 8).Font.Name = "メイリオ"
    Cells(25, 8).HorizontalAlignment = -4108
    Cells(25, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(25, 8).Borders(xlEdgeLeft).color = 0
    Cells(25, 8).Borders(xlEdgeLeft).weight = 2
    Cells(25, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(25, 8).Borders(xlEdgeRight).color = 0
    Cells(25, 8).Borders(xlEdgeRight).weight = 2
    Cells(25, 9).Font.Name = "メイリオ"
    Cells(25, 9).HorizontalAlignment = -4131
    Cells(25, 9).IndentLevel = 1
    Cells(25, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(25, 9).Borders(xlEdgeTop).color = 0
    Cells(25, 9).Borders(xlEdgeTop).weight = 2
    Cells(25, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(25, 9).Borders(xlEdgeBottom).color = 0
    Cells(25, 9).Borders(xlEdgeBottom).weight = 2
    Cells(25, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(25, 9).Borders(xlEdgeLeft).color = 0
    Cells(25, 9).Borders(xlEdgeLeft).weight = 2
    Cells(25, 9).Borders(xlEdgeRight).LineStyle = 1
    Cells(25, 9).Borders(xlEdgeRight).color = 0
    Cells(25, 9).Borders(xlEdgeRight).weight = 2
    Cells(25, 9).Validation.Delete
    Cells(25, 9).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="かつ,または"
    Cells(25, 10) = "未指定時はOR条件とする"
    Cells(25, 10).Font.Size = 10
    Cells(25, 10).Font.Name = "メイリオ"
    Cells(25, 10).Font.Color = 8421504
    Cells(25, 10).HorizontalAlignment = -4131
    Cells(25, 10).IndentLevel = 1
    Cells(25, 10).Borders(xlEdgeLeft).LineStyle = 1
    Cells(25, 10).Borders(xlEdgeLeft).color = 0
    Cells(25, 10).Borders(xlEdgeLeft).weight = 2
    Cells(25, 11).Font.Name = "メイリオ"
    Cells(25, 12).Font.Name = "メイリオ"
    Cells(25, 13).Font.Name = "メイリオ"
    Cells(25, 14).Font.Name = "メイリオ"
    Cells(25, 15).Font.Name = "メイリオ"
    Cells(25, 16).Font.Name = "メイリオ"
    Cells(26, 1).Font.Name = "メイリオ"
    Cells(26, 2).Font.Name = "メイリオ"
    Cells(26, 3).Font.Name = "メイリオ"
    Cells(26, 3).HorizontalAlignment = -4152
    Cells(26, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(26, 3).Borders(xlEdgeRight).color = 0
    Cells(26, 3).Borders(xlEdgeRight).weight = 2
    Cells(26, 4).NumberFormatLocal = "@"
    Cells(26, 4).Font.Name = "メイリオ"
    Cells(26, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(26, 4).Borders(xlEdgeTop).color = 0
    Cells(26, 4).Borders(xlEdgeTop).weight = 2
    Cells(26, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(26, 4).Borders(xlEdgeBottom).color = 0
    Cells(26, 4).Borders(xlEdgeBottom).weight = 2
    Cells(26, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(26, 4).Borders(xlEdgeLeft).color = 0
    Cells(26, 4).Borders(xlEdgeLeft).weight = 2
    Cells(26, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(26, 4).Borders(xlEdgeRight).color = 0
    Cells(26, 4).Borders(xlEdgeRight).weight = 2
    Cells(26, 5) = "→"
    Cells(26, 5).Font.Name = "メイリオ"
    Cells(26, 5).HorizontalAlignment = -4108
    Cells(26, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(26, 5).Borders(xlEdgeLeft).color = 0
    Cells(26, 5).Borders(xlEdgeLeft).weight = 2
    Cells(26, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(26, 5).Borders(xlEdgeRight).color = 0
    Cells(26, 5).Borders(xlEdgeRight).weight = 2
    Cells(26, 6).Font.Size = 9
    Cells(26, 6).Font.Name = "メイリオ"
    Range("F26:G26").Merge
    Cells(26, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(26, 6).Borders(xlEdgeTop).color = 0
    Cells(26, 6).Borders(xlEdgeTop).weight = 2
    Cells(26, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(26, 6).Borders(xlEdgeBottom).color = 0
    Cells(26, 6).Borders(xlEdgeBottom).weight = 2
    Cells(26, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(26, 6).Borders(xlEdgeLeft).color = 0
    Cells(26, 6).Borders(xlEdgeLeft).weight = 2
    Cells(26, 6).Validation.Delete
    Cells(26, 6).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(26, 7).Font.Size = 9
    Cells(26, 7).Font.Name = "メイリオ"
    Range("F26:G26").Merge
    Cells(26, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(26, 7).Borders(xlEdgeTop).color = 0
    Cells(26, 7).Borders(xlEdgeTop).weight = 2
    Cells(26, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(26, 7).Borders(xlEdgeBottom).color = 0
    Cells(26, 7).Borders(xlEdgeBottom).weight = 2
    Cells(26, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(26, 7).Borders(xlEdgeRight).color = 0
    Cells(26, 7).Borders(xlEdgeRight).weight = 2
    Cells(26, 7).Validation.Delete
    Cells(26, 7).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(26, 8).Font.Name = "メイリオ"
    Cells(26, 8).HorizontalAlignment = -4108
    Cells(26, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(26, 8).Borders(xlEdgeLeft).color = 0
    Cells(26, 8).Borders(xlEdgeLeft).weight = 2
    Cells(26, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(26, 8).Borders(xlEdgeRight).color = 0
    Cells(26, 8).Borders(xlEdgeRight).weight = 2
    Cells(26, 9).Font.Name = "メイリオ"
    Cells(26, 9).HorizontalAlignment = -4131
    Cells(26, 9).IndentLevel = 1
    Cells(26, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(26, 9).Borders(xlEdgeTop).color = 0
    Cells(26, 9).Borders(xlEdgeTop).weight = 2
    Cells(26, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(26, 9).Borders(xlEdgeBottom).color = 0
    Cells(26, 9).Borders(xlEdgeBottom).weight = 2
    Cells(26, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(26, 9).Borders(xlEdgeLeft).color = 0
    Cells(26, 9).Borders(xlEdgeLeft).weight = 2
    Cells(26, 9).Borders(xlEdgeRight).LineStyle = 1
    Cells(26, 9).Borders(xlEdgeRight).color = 0
    Cells(26, 9).Borders(xlEdgeRight).weight = 2
    Cells(26, 9).Validation.Delete
    Cells(26, 9).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="かつ,または"
    Cells(26, 10) = "未指定時はOR条件とする"
    Cells(26, 10).Font.Size = 10
    Cells(26, 10).Font.Name = "メイリオ"
    Cells(26, 10).Font.Color = 8421504
    Cells(26, 10).HorizontalAlignment = -4131
    Cells(26, 10).IndentLevel = 1
    Cells(26, 10).Borders(xlEdgeLeft).LineStyle = 1
    Cells(26, 10).Borders(xlEdgeLeft).color = 0
    Cells(26, 10).Borders(xlEdgeLeft).weight = 2
    Cells(26, 11).Font.Name = "メイリオ"
    Cells(26, 12).Font.Name = "メイリオ"
    Cells(26, 13).Font.Name = "メイリオ"
    Cells(26, 14).Font.Name = "メイリオ"
    Cells(26, 15).Font.Name = "メイリオ"
    Cells(26, 16).Font.Name = "メイリオ"
    Cells(27, 1).Font.Name = "メイリオ"
    Cells(27, 2).Font.Name = "メイリオ"
    Cells(27, 3).Font.Name = "メイリオ"
    Cells(27, 3).HorizontalAlignment = -4152
    Cells(27, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(27, 3).Borders(xlEdgeRight).color = 0
    Cells(27, 3).Borders(xlEdgeRight).weight = 2
    Cells(27, 4).Font.Name = "メイリオ"
    Cells(27, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(27, 4).Borders(xlEdgeTop).color = 0
    Cells(27, 4).Borders(xlEdgeTop).weight = 2
    Cells(27, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(27, 4).Borders(xlEdgeBottom).color = 0
    Cells(27, 4).Borders(xlEdgeBottom).weight = 2
    Cells(27, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(27, 4).Borders(xlEdgeLeft).color = 0
    Cells(27, 4).Borders(xlEdgeLeft).weight = 2
    Cells(27, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(27, 4).Borders(xlEdgeRight).color = 0
    Cells(27, 4).Borders(xlEdgeRight).weight = 2
    Cells(27, 5) = "→"
    Cells(27, 5).Font.Name = "メイリオ"
    Cells(27, 5).HorizontalAlignment = -4108
    Cells(27, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(27, 5).Borders(xlEdgeLeft).color = 0
    Cells(27, 5).Borders(xlEdgeLeft).weight = 2
    Cells(27, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(27, 5).Borders(xlEdgeRight).color = 0
    Cells(27, 5).Borders(xlEdgeRight).weight = 2
end Function
Function revival13()
    Cells(27, 6).Font.Size = 9
    Cells(27, 6).Font.Name = "メイリオ"
    Range("F27:G27").Merge
    Cells(27, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(27, 6).Borders(xlEdgeTop).color = 0
    Cells(27, 6).Borders(xlEdgeTop).weight = 2
    Cells(27, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(27, 6).Borders(xlEdgeBottom).color = 0
    Cells(27, 6).Borders(xlEdgeBottom).weight = 2
    Cells(27, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(27, 6).Borders(xlEdgeLeft).color = 0
    Cells(27, 6).Borders(xlEdgeLeft).weight = 2
    Cells(27, 6).Validation.Delete
    Cells(27, 6).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(27, 7).Font.Size = 9
    Cells(27, 7).Font.Name = "メイリオ"
    Range("F27:G27").Merge
    Cells(27, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(27, 7).Borders(xlEdgeTop).color = 0
    Cells(27, 7).Borders(xlEdgeTop).weight = 2
    Cells(27, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(27, 7).Borders(xlEdgeBottom).color = 0
    Cells(27, 7).Borders(xlEdgeBottom).weight = 2
    Cells(27, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(27, 7).Borders(xlEdgeRight).color = 0
    Cells(27, 7).Borders(xlEdgeRight).weight = 2
    Cells(27, 7).Validation.Delete
    Cells(27, 7).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="左記にファイル名が一致する,左記をファイル名に含む,左記をファイル名に含まない,左記からファイル名が始まる,左記でファイル名が終わる,左記の正規表現に一致する"
    Cells(27, 8).Font.Name = "メイリオ"
    Cells(27, 8).HorizontalAlignment = -4108
    Cells(27, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(27, 8).Borders(xlEdgeLeft).color = 0
    Cells(27, 8).Borders(xlEdgeLeft).weight = 2
    Cells(27, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(27, 8).Borders(xlEdgeRight).color = 0
    Cells(27, 8).Borders(xlEdgeRight).weight = 2
    Cells(27, 9).Font.Name = "メイリオ"
    Cells(27, 9).HorizontalAlignment = -4131
    Cells(27, 9).IndentLevel = 1
    Cells(27, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(27, 9).Borders(xlEdgeTop).color = 0
    Cells(27, 9).Borders(xlEdgeTop).weight = 2
    Cells(27, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(27, 9).Borders(xlEdgeBottom).color = 0
    Cells(27, 9).Borders(xlEdgeBottom).weight = 2
    Cells(27, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(27, 9).Borders(xlEdgeLeft).color = 0
    Cells(27, 9).Borders(xlEdgeLeft).weight = 2
    Cells(27, 9).Borders(xlEdgeRight).LineStyle = 1
    Cells(27, 9).Borders(xlEdgeRight).color = 0
    Cells(27, 9).Borders(xlEdgeRight).weight = 2
    Cells(27, 9).Validation.Delete
    Cells(27, 9).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="かつ,または"
    Cells(27, 10) = "未指定時はOR条件とする"
    Cells(27, 10).Font.Size = 10
    Cells(27, 10).Font.Name = "メイリオ"
    Cells(27, 10).Font.Color = 8421504
    Cells(27, 10).HorizontalAlignment = -4131
    Cells(27, 10).IndentLevel = 1
    Cells(27, 10).Borders(xlEdgeLeft).LineStyle = 1
    Cells(27, 10).Borders(xlEdgeLeft).color = 0
    Cells(27, 10).Borders(xlEdgeLeft).weight = 2
    Cells(27, 11).Font.Name = "メイリオ"
    Cells(27, 12).Font.Name = "メイリオ"
    Cells(27, 13).Font.Name = "メイリオ"
    Cells(27, 14).Font.Name = "メイリオ"
    Cells(27, 15).Font.Name = "メイリオ"
    Cells(27, 16).Font.Name = "メイリオ"
    Cells(28, 1).Font.Size = 18
    Cells(28, 1).Font.Name = "メイリオ"
    Cells(28, 1).Font.Bold = True
    Cells(28, 2).Font.Name = "メイリオ"
    Cells(28, 2).Font.Bold = True
    Cells(28, 2).HorizontalAlignment = -4131
    Cells(28, 2).IndentLevel = 1
    Cells(28, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 2).Borders(xlEdgeBottom).color = 0
    Cells(28, 2).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 3).Font.Name = "メイリオ"
    Cells(28, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 3).Borders(xlEdgeBottom).color = 0
    Cells(28, 3).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 4).Font.Name = "メイリオ"
    Cells(28, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(28, 4).Borders(xlEdgeTop).color = 0
    Cells(28, 4).Borders(xlEdgeTop).weight = 2
    Cells(28, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 4).Borders(xlEdgeBottom).color = 0
    Cells(28, 4).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 5).Font.Name = "メイリオ"
    Cells(28, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 5).Borders(xlEdgeBottom).color = 0
    Cells(28, 5).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 6).Font.Name = "メイリオ"
    Cells(28, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(28, 6).Borders(xlEdgeTop).color = 0
    Cells(28, 6).Borders(xlEdgeTop).weight = 2
    Cells(28, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 6).Borders(xlEdgeBottom).color = 0
    Cells(28, 6).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 7).Font.Name = "メイリオ"
    Cells(28, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(28, 7).Borders(xlEdgeTop).color = 0
    Cells(28, 7).Borders(xlEdgeTop).weight = 2
    Cells(28, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 7).Borders(xlEdgeBottom).color = 0
    Cells(28, 7).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 8).Font.Name = "メイリオ"
    Cells(28, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 8).Borders(xlEdgeBottom).color = 0
    Cells(28, 8).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 9).Font.Name = "メイリオ"
    Cells(28, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(28, 9).Borders(xlEdgeTop).color = 0
    Cells(28, 9).Borders(xlEdgeTop).weight = 2
    Cells(28, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 9).Borders(xlEdgeBottom).color = 0
    Cells(28, 9).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 10).Font.Name = "メイリオ"
    Cells(28, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 10).Borders(xlEdgeBottom).color = 0
    Cells(28, 10).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 11).Font.Name = "メイリオ"
    Cells(28, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 11).Borders(xlEdgeBottom).color = 0
    Cells(28, 11).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 12).Font.Name = "メイリオ"
    Cells(28, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 12).Borders(xlEdgeBottom).color = 0
    Cells(28, 12).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 13).Font.Name = "メイリオ"
    Cells(28, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 13).Borders(xlEdgeBottom).color = 0
    Cells(28, 13).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 14).Font.Name = "メイリオ"
    Cells(28, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 14).Borders(xlEdgeBottom).color = 0
    Cells(28, 14).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 15).Font.Name = "メイリオ"
    Cells(28, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 15).Borders(xlEdgeBottom).color = 0
    Cells(28, 15).Borders(xlEdgeBottom).weight = -4138
    Cells(28, 16).Font.Name = "メイリオ"
    Cells(28, 16).Borders(xlEdgeBottom).LineStyle = 1
    Cells(28, 16).Borders(xlEdgeBottom).color = 0
    Cells(28, 16).Borders(xlEdgeBottom).weight = -4138
    Cells(29, 1).Font.Size = 18
    Cells(29, 1).Font.Name = "メイリオ"
    Cells(29, 1).Font.Bold = True
    Cells(29, 2) = "■実行条件"
    Cells(29, 2).Font.Name = "メイリオ"
    Cells(29, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 2).Borders(xlEdgeTop).color = 0
    Cells(29, 2).Borders(xlEdgeTop).weight = -4138
    Cells(29, 3).Font.Name = "メイリオ"
    Cells(29, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 3).Borders(xlEdgeTop).color = 0
    Cells(29, 3).Borders(xlEdgeTop).weight = -4138
end Function
Function revival14()
    Cells(29, 4).Font.Name = "メイリオ"
    Cells(29, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 4).Borders(xlEdgeTop).color = 0
    Cells(29, 4).Borders(xlEdgeTop).weight = -4138
    Cells(29, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(29, 4).Borders(xlEdgeBottom).color = 0
    Cells(29, 4).Borders(xlEdgeBottom).weight = 2
    Cells(29, 5).Font.Name = "メイリオ"
    Cells(29, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 5).Borders(xlEdgeTop).color = 0
    Cells(29, 5).Borders(xlEdgeTop).weight = -4138
    Cells(29, 6).Font.Name = "メイリオ"
    Cells(29, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 6).Borders(xlEdgeTop).color = 0
    Cells(29, 6).Borders(xlEdgeTop).weight = -4138
    Cells(29, 7).Font.Name = "メイリオ"
    Cells(29, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 7).Borders(xlEdgeTop).color = 0
    Cells(29, 7).Borders(xlEdgeTop).weight = -4138
    Cells(29, 8).Font.Name = "メイリオ"
    Cells(29, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 8).Borders(xlEdgeTop).color = 0
    Cells(29, 8).Borders(xlEdgeTop).weight = -4138
    Cells(29, 9).Font.Name = "メイリオ"
    Cells(29, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 9).Borders(xlEdgeTop).color = 0
    Cells(29, 9).Borders(xlEdgeTop).weight = -4138
    Cells(29, 10).Font.Name = "メイリオ"
    Cells(29, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 10).Borders(xlEdgeTop).color = 0
    Cells(29, 10).Borders(xlEdgeTop).weight = -4138
    Cells(29, 11).Font.Name = "メイリオ"
    Cells(29, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 11).Borders(xlEdgeTop).color = 0
    Cells(29, 11).Borders(xlEdgeTop).weight = -4138
    Cells(29, 12).Font.Name = "メイリオ"
    Cells(29, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 12).Borders(xlEdgeTop).color = 0
    Cells(29, 12).Borders(xlEdgeTop).weight = -4138
    Cells(29, 13).Font.Name = "メイリオ"
    Cells(29, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 13).Borders(xlEdgeTop).color = 0
    Cells(29, 13).Borders(xlEdgeTop).weight = -4138
    Cells(29, 14).Font.Name = "メイリオ"
    Cells(29, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 14).Borders(xlEdgeTop).color = 0
    Cells(29, 14).Borders(xlEdgeTop).weight = -4138
    Cells(29, 15).Font.Name = "メイリオ"
    Cells(29, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 15).Borders(xlEdgeTop).color = 0
    Cells(29, 15).Borders(xlEdgeTop).weight = -4138
    Cells(29, 16).Font.Name = "メイリオ"
    Cells(29, 16).Borders(xlEdgeTop).LineStyle = 1
    Cells(29, 16).Borders(xlEdgeTop).color = 0
    Cells(29, 16).Borders(xlEdgeTop).weight = -4138
    Cells(30, 1).Font.Size = 18
    Cells(30, 1).Font.Name = "メイリオ"
    Cells(30, 1).Font.Bold = True
    Cells(30, 2).Font.Name = "メイリオ"
    Cells(30, 3) = "処理種別："
    Cells(30, 3).Font.Name = "メイリオ"
    Cells(30, 3).HorizontalAlignment = -4152
    Cells(30, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(30, 3).Borders(xlEdgeRight).color = 0
    Cells(30, 3).Borders(xlEdgeRight).weight = 2
    Cells(30, 4).Font.Name = "メイリオ"
    Cells(30, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(30, 4).Borders(xlEdgeTop).color = 0
    Cells(30, 4).Borders(xlEdgeTop).weight = 2
    Cells(30, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(30, 4).Borders(xlEdgeBottom).color = 0
    Cells(30, 4).Borders(xlEdgeBottom).weight = 2
    Cells(30, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(30, 4).Borders(xlEdgeLeft).color = 0
    Cells(30, 4).Borders(xlEdgeLeft).weight = 2
    Cells(30, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(30, 4).Borders(xlEdgeRight).color = 0
    Cells(30, 4).Borders(xlEdgeRight).weight = 2
    Cells(30, 4).Validation.Delete
    Cells(30, 4).Validation.Add Type:=xlValidateList, _
        Operator:=xlEqual, _
        Formula1:="移動,コピー"
    Cells(30, 5) = "移動 or コピー"
    Cells(30, 5).Font.Size = 10
    Cells(30, 5).Font.Name = "メイリオ"
    Cells(30, 5).Font.Color = 12566463
    Cells(30, 5).HorizontalAlignment = -4131
    Cells(30, 5).IndentLevel = 1
    Cells(30, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(30, 5).Borders(xlEdgeLeft).color = 0
    Cells(30, 5).Borders(xlEdgeLeft).weight = 2
    Cells(30, 6).Font.Name = "メイリオ"
    Cells(30, 7).Font.Name = "メイリオ"
    Cells(30, 8).Font.Name = "メイリオ"
    Cells(30, 9).Font.Name = "メイリオ"
    Cells(30, 10).Font.Name = "メイリオ"
    Cells(30, 11).Font.Name = "メイリオ"
    Cells(30, 12).Font.Name = "メイリオ"
    Cells(30, 13).Font.Name = "メイリオ"
    Cells(30, 14).Font.Name = "メイリオ"
    Cells(30, 15).Font.Name = "メイリオ"
    Cells(30, 16).Font.Name = "メイリオ"
    Cells(31, 1).Font.Size = 18
    Cells(31, 1).Font.Name = "メイリオ"
    Cells(31, 1).Font.Bold = True
end Function
Function revival15()
    Cells(31, 2).Font.Name = "メイリオ"
    Cells(31, 2).Font.Bold = True
    Cells(31, 2).HorizontalAlignment = -4131
    Cells(31, 2).IndentLevel = 1
    Cells(31, 3) = "ブランク置換文字："
    Cells(31, 3).Font.Name = "メイリオ"
    Cells(31, 3).HorizontalAlignment = -4152
    Cells(31, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(31, 3).Borders(xlEdgeRight).color = 0
    Cells(31, 3).Borders(xlEdgeRight).weight = 2
    Cells(31, 4).Font.Name = "メイリオ"
    Cells(31, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(31, 4).Borders(xlEdgeTop).color = 0
    Cells(31, 4).Borders(xlEdgeTop).weight = 2
    Cells(31, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(31, 4).Borders(xlEdgeBottom).color = 0
    Cells(31, 4).Borders(xlEdgeBottom).weight = 2
    Cells(31, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(31, 4).Borders(xlEdgeLeft).color = 0
    Cells(31, 4).Borders(xlEdgeLeft).weight = 2
    Cells(31, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(31, 4).Borders(xlEdgeRight).color = 0
    Cells(31, 4).Borders(xlEdgeRight).weight = 2
    Cells(31, 5) = "ファイルコピー/移動時にブランクで置換したい文字列を指定する"
    Cells(31, 5).Font.Size = 10
    Cells(31, 5).Font.Name = "メイリオ"
    Cells(31, 5).Font.Color = 8421504
    Cells(31, 5).HorizontalAlignment = -4131
    Cells(31, 5).IndentLevel = 1
    Cells(31, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(31, 5).Borders(xlEdgeLeft).color = 0
    Cells(31, 5).Borders(xlEdgeLeft).weight = 2
    Cells(31, 6).Font.Name = "メイリオ"
    Cells(31, 7).Font.Name = "メイリオ"
    Cells(31, 8).Font.Name = "メイリオ"
    Cells(31, 9).Font.Name = "メイリオ"
    Cells(31, 10).Font.Name = "メイリオ"
    Cells(31, 11).Font.Name = "メイリオ"
    Cells(31, 12).Font.Name = "メイリオ"
    Cells(31, 13).Font.Name = "メイリオ"
    Cells(31, 14).Font.Name = "メイリオ"
    Cells(31, 15).Font.Name = "メイリオ"
    Cells(31, 16).Font.Name = "メイリオ"
    Cells(32, 1).Font.Size = 18
    Cells(32, 1).Font.Name = "メイリオ"
    Cells(32, 1).Font.Bold = True
    Cells(32, 2).Font.Name = "メイリオ"
    Cells(32, 2).Font.Bold = True
    Cells(32, 2).HorizontalAlignment = -4131
    Cells(32, 2).IndentLevel = 1
    Cells(32, 3).Font.Name = "メイリオ"
    Cells(32, 4).Font.Name = "メイリオ"
    Cells(32, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(32, 4).Borders(xlEdgeTop).color = 0
    Cells(32, 4).Borders(xlEdgeTop).weight = 2
    Cells(32, 5).Font.Name = "メイリオ"
    Cells(32, 6).Font.Name = "メイリオ"
    Cells(32, 7).Font.Name = "メイリオ"
    Cells(32, 8).Font.Name = "メイリオ"
    Cells(32, 9).Font.Name = "メイリオ"
    Cells(32, 10).Font.Name = "メイリオ"
    Cells(32, 11).Font.Name = "メイリオ"
    Cells(32, 12).Font.Name = "メイリオ"
    Cells(32, 13).Font.Name = "メイリオ"
    Cells(32, 14).Font.Name = "メイリオ"
    Cells(32, 15).Font.Name = "メイリオ"
end Function
Function revival16()
    Cells(32, 16).Font.Name = "メイリオ"
    Cells(33, 1).Font.Size = 18
    Cells(33, 1).Font.Name = "メイリオ"
    Cells(33, 1).Font.Bold = True
    Cells(33, 2).Font.Name = "メイリオ"
    Cells(33, 2).Font.Bold = True
    Cells(33, 2).HorizontalAlignment = -4131
    Cells(33, 2).IndentLevel = 1
    Cells(33, 3).Font.Name = "メイリオ"
    Cells(33, 4).Font.Name = "メイリオ"
    Cells(33, 5).Font.Name = "メイリオ"
    Cells(33, 6).Font.Name = "メイリオ"
    Cells(33, 7).Font.Name = "メイリオ"
    Cells(33, 8).Font.Name = "メイリオ"
    Cells(33, 9).Font.Name = "メイリオ"
    Cells(33, 10).Font.Name = "メイリオ"
    Cells(33, 11).Font.Name = "メイリオ"
    Cells(33, 12).Font.Name = "メイリオ"
    Cells(33, 13).Font.Name = "メイリオ"
    Cells(33, 14).Font.Name = "メイリオ"
    Cells(33, 15).Font.Name = "メイリオ"
    Cells(33, 16).Font.Name = "メイリオ"
    Cells(34, 1).Font.Size = 18
    Cells(34, 1).Font.Name = "メイリオ"
    Cells(34, 1).Font.Bold = True
    Cells(34, 2).Font.Name = "メイリオ"
    Cells(34, 2).Font.Bold = True
    Cells(34, 2).HorizontalAlignment = -4131
    Cells(34, 2).IndentLevel = 1
    Cells(34, 3).Font.Name = "メイリオ"
    Cells(34, 4).Font.Name = "メイリオ"
    Cells(34, 5).Font.Name = "メイリオ"
    Cells(34, 6).Font.Name = "メイリオ"
    Cells(34, 7).Font.Name = "メイリオ"
    Cells(34, 8).Font.Name = "メイリオ"
    Cells(34, 9).Font.Name = "メイリオ"
    Cells(34, 10).Font.Name = "メイリオ"
    Cells(34, 11).Font.Name = "メイリオ"
    Cells(34, 12).Font.Name = "メイリオ"
    Cells(34, 13).Font.Name = "メイリオ"
end Function
Function revival17()
    Cells(34, 14).Font.Name = "メイリオ"
    Cells(34, 15).Font.Name = "メイリオ"
    Cells(34, 16).Font.Name = "メイリオ"
    Cells(35, 1).Font.Size = 18
    Cells(35, 1).Font.Name = "メイリオ"
    Cells(35, 1).Font.Bold = True
    Cells(35, 2).Font.Name = "メイリオ"
    Cells(35, 2).Font.Bold = True
    Cells(35, 2).HorizontalAlignment = -4131
    Cells(35, 2).IndentLevel = 1
    Cells(35, 3).Font.Name = "メイリオ"
    Cells(35, 4).Font.Name = "メイリオ"
    Cells(35, 5).Font.Name = "メイリオ"
    Cells(35, 6).Font.Name = "メイリオ"
    Cells(35, 7).Font.Name = "メイリオ"
    Cells(35, 8).Font.Name = "メイリオ"
    Cells(35, 9).Font.Name = "メイリオ"
    Cells(35, 10).Font.Name = "メイリオ"
    Cells(35, 11).Font.Name = "メイリオ"
    Cells(35, 12).Font.Name = "メイリオ"
    Cells(35, 13).Font.Name = "メイリオ"
    Cells(35, 14).Font.Name = "メイリオ"
    Cells(35, 15).Font.Name = "メイリオ"
    Cells(35, 16).Font.Name = "メイリオ"
    Cells(36, 1).Font.Size = 18
    Cells(36, 1).Font.Name = "メイリオ"
    Cells(36, 1).Font.Bold = True
    Cells(36, 2).Font.Name = "メイリオ"
    Cells(36, 2).Font.Bold = True
    Cells(36, 2).HorizontalAlignment = -4131
    Cells(36, 2).IndentLevel = 1
    Cells(36, 3).Font.Name = "メイリオ"
    Cells(36, 4).Font.Name = "メイリオ"
    Cells(36, 5).Font.Name = "メイリオ"
    Cells(36, 6).Font.Name = "メイリオ"
    Cells(36, 7).Font.Name = "メイリオ"
    Cells(36, 8).Font.Name = "メイリオ"
    Cells(36, 9).Font.Name = "メイリオ"
    Cells(36, 10).Font.Name = "メイリオ"
    Cells(36, 11).Font.Name = "メイリオ"
end Function
Function revival18()
    Cells(36, 12).Font.Name = "メイリオ"
    Cells(36, 13).Font.Name = "メイリオ"
    Cells(36, 14).Font.Name = "メイリオ"
    Cells(36, 15).Font.Name = "メイリオ"
    Cells(36, 16).Font.Name = "メイリオ"
    Cells(37, 1).Font.Size = 18
    Cells(37, 1).Font.Name = "メイリオ"
    Cells(37, 1).Font.Bold = True
    Cells(37, 2).Font.Name = "メイリオ"
    Cells(37, 2).Font.Bold = True
    Cells(37, 2).HorizontalAlignment = -4131
    Cells(37, 2).IndentLevel = 1
    Cells(37, 3).Font.Name = "メイリオ"
    Cells(37, 4).Font.Name = "メイリオ"
    Cells(37, 5).Font.Name = "メイリオ"
    Cells(37, 6).Font.Name = "メイリオ"
    Cells(37, 7).Font.Name = "メイリオ"
    Cells(37, 8).Font.Name = "メイリオ"
    Cells(37, 9).Font.Name = "メイリオ"
    Cells(37, 10).Font.Name = "メイリオ"
    Cells(37, 11).Font.Name = "メイリオ"
    Cells(37, 12).Font.Name = "メイリオ"
    Cells(37, 13).Font.Name = "メイリオ"
    Cells(37, 14).Font.Name = "メイリオ"
    Cells(37, 15).Font.Name = "メイリオ"
    Cells(37, 16).Font.Name = "メイリオ"
    Cells(38, 1).Font.Size = 18
    Cells(38, 1).Font.Name = "メイリオ"
    Cells(38, 1).Font.Bold = True
    Cells(38, 2).Font.Name = "メイリオ"
    Cells(38, 2).Font.Bold = True
    Cells(38, 2).HorizontalAlignment = -4131
    Cells(38, 2).IndentLevel = 1
    Cells(38, 3).Font.Name = "メイリオ"
    Cells(38, 4).Font.Name = "メイリオ"
    Cells(38, 5).Font.Name = "メイリオ"
    Cells(38, 6).Font.Name = "メイリオ"
    Cells(38, 7).Font.Name = "メイリオ"
    Cells(38, 8).Font.Name = "メイリオ"
    Cells(38, 9).Font.Name = "メイリオ"
end Function
Function revival19()
    Cells(38, 10).Font.Name = "メイリオ"
    Cells(38, 11).Font.Name = "メイリオ"
    Cells(38, 12).Font.Name = "メイリオ"
    Cells(38, 13).Font.Name = "メイリオ"
    Cells(38, 14).Font.Name = "メイリオ"
    Cells(38, 15).Font.Name = "メイリオ"
    Cells(38, 16).Font.Name = "メイリオ"
    Rows(1).RowHeight = 30
    Rows(2).RowHeight = 23.25
    Rows(3).RowHeight = 23.25
    Rows(4).RowHeight = 23.25
    Rows(5).RowHeight = 23.25
    Rows(6).RowHeight = 23.25
    Rows(7).RowHeight = 23.25
    Rows(8).RowHeight = 23.25
    Rows(9).RowHeight = 23.25
    Rows(10).RowHeight = 21
    Rows(11).RowHeight = 21
    Rows(12).RowHeight = 21
    Rows(13).RowHeight = 21
    Rows(14).RowHeight = 23.25
    Rows(15).RowHeight = 21
    Rows(16).RowHeight = 23.25
    Rows(17).RowHeight = 23.25
    Rows(18).RowHeight = 23.25
    Rows(19).RowHeight = 23.25
    Rows(20).RowHeight = 23.25
    Rows(21).RowHeight = 23.25
    Rows(22).RowHeight = 23.25
    Rows(23).RowHeight = 23.25
    Rows(24).RowHeight = 23.25
    Rows(25).RowHeight = 23.25
    Rows(26).RowHeight = 23.25
    Rows(27).RowHeight = 23.25
    Rows(28).RowHeight = 23.25
    Rows(29).RowHeight = 23.25
    Rows(30).RowHeight = 23.25
    Rows(31).RowHeight = 23.25
    Rows(32).RowHeight = 23.25
    Rows(33).RowHeight = 23.25
    Rows(34).RowHeight = 23.25
    Rows(35).RowHeight = 23.25
    Rows(36).RowHeight = 23.25
    Rows(37).RowHeight = 23.25
    Rows(38).RowHeight = 23.25
    Columns(1).ColumnWidth = 8.38
    Columns(2).ColumnWidth = 8.38
    Columns(3).ColumnWidth = 8.38
    Columns(4).ColumnWidth = 8.25
    Columns(5).ColumnWidth = 8.38
    Columns(6).ColumnWidth = 8.38
    Columns(7).ColumnWidth = 8.38
    Columns(8).ColumnWidth = 8.38
    Columns(9).ColumnWidth = 8.38
    Columns(10).ColumnWidth = 8.38
    Columns(11).ColumnWidth = 8.38
    Columns(12).ColumnWidth = 8.38
    Columns(13).ColumnWidth = 8.38
    Columns(14).ColumnWidth = 8.38
    Columns(15).ColumnWidth = 8.38
    Columns(16).ColumnWidth = 8.38
    Dim onShape As Object
    Set onShape = ActiveSheet.Buttons.Add(646.5,682.5,53.25,22.5)
    onShape.OnAction = "'02_ファイル仕分けv2.5.xlsm'!exe"
    onShape.Name = "Button 7"
    onShape.Visible = -1
    onShape.Placement = 1
End Function
sub revival()
    CALL revival0()
    CALL revival1()
    CALL revival2()
    CALL revival3()
    CALL revival4()
    CALL revival5()
    CALL revival6()
    CALL revival7()
    CALL revival8()
    CALL revival9()
    CALL revival10()
    CALL revival11()
    CALL revival12()
    CALL revival13()
    CALL revival14()
    CALL revival15()
    CALL revival16()
    CALL revival17()
    CALL revival18()
    CALL revival19()
end sub