Attribute VB_Name = "setup2"
Function revival0()
    ActiveWindow.DisplayGridlines = False
    ActiveWindow.Zoom = 70
    ActiveSheet.Name = "練習用"
    Cells(3, 4).Font.Size = 14
    Cells(3, 4).Font.Name = "BIZ UDPゴシック"
    Cells(3, 4).Font.Color = 1315860
    Cells(3, 4).Font.Bold = True
    Cells(3, 5).Font.Name = "游ゴシック"
    Cells(3, 6).Font.Name = "游ゴシック"
    Cells(3, 7).Font.Name = "游ゴシック"
    Cells(4, 4).Font.Name = "游ゴシック"
    Cells(4, 5).Font.Name = "游ゴシック"
    Cells(4, 6).Font.Name = "游ゴシック"
    Cells(4, 7).Font.Size = 14
    Cells(4, 7).Font.Name = "BIZ UDPゴシック"
    Cells(4, 7).Font.Color = 1315860
    Cells(4, 7).Font.Bold = True
    Cells(5, 4).Font.Name = "游ゴシック"
    Cells(5, 5).Font.Name = "游ゴシック"
    Cells(5, 6).Font.Name = "游ゴシック"
    Cells(5, 7).Font.Name = "游ゴシック"
    Cells(6, 4).Font.Name = "游ゴシック"
    Cells(6, 5).Font.Name = "游ゴシック"
    Cells(6, 6).Font.Name = "游ゴシック"
    Cells(6, 7).Font.Name = "游ゴシック"
    Cells(7, 4).Font.Size = 14
    Cells(7, 4).Font.Name = "BIZ UDPゴシック"
    Cells(7, 4).Font.Color = 1315860
    Cells(7, 4).Font.Bold = True
    Cells(7, 5).Font.Name = "游ゴシック"
    Cells(7, 6).Font.Name = "游ゴシック"
    Cells(7, 7).Font.Name = "游ゴシック"
    Cells(8, 4).Font.Name = "游ゴシック"
    Cells(8, 5).Font.Name = "游ゴシック"
    Cells(8, 6).Font.Name = "游ゴシック"
    Cells(8, 7).Font.Name = "游ゴシック"
    Cells(9, 4).Font.Name = "游ゴシック"
    Cells(9, 5).Font.Name = "游ゴシック"
    Cells(9, 6).Font.Name = "游ゴシック"
    Cells(9, 7).Font.Name = "游ゴシック"
    Cells(10, 4).Font.Name = "游ゴシック"
    Cells(10, 5).Font.Name = "游ゴシック"
    Cells(10, 6).Font.Name = "游ゴシック"
    Cells(10, 7).Font.Name = "游ゴシック"
    Cells(11, 4).Font.Name = "游ゴシック"
    Cells(11, 5).Font.Name = "游ゴシック"
    Cells(11, 6).Font.Name = "游ゴシック"
    Cells(11, 7).Font.Name = "游ゴシック"
    Cells(12, 4).Font.Name = "游ゴシック"
    Cells(12, 5).Font.Name = "游ゴシック"
    Cells(12, 6).Font.Name = "游ゴシック"
    Cells(12, 7).Font.Name = "游ゴシック"
    Cells(13, 4).Font.Name = "游ゴシック"
    Cells(13, 5).Font.Name = "游ゴシック"
    Cells(13, 6).Font.Name = "游ゴシック"
    Cells(13, 7).Font.Name = "游ゴシック"
    Cells(14, 4).Font.Size = 14
    Cells(14, 4).Font.Name = "BIZ UDPゴシック"
    Cells(14, 4).Font.Color = 1315860
    Cells(14, 4).Font.Bold = True
    Cells(14, 5).Font.Name = "游ゴシック"
    Cells(14, 6).Font.Name = "游ゴシック"
    Cells(14, 7).Font.Size = 14
    Cells(14, 7).Font.Name = "BIZ UDPゴシック"
    Cells(14, 7).Font.Color = 1315860
    Cells(14, 7).Font.Bold = True
    Cells(15, 4).Font.Name = "游ゴシック"
    Cells(15, 5).Font.Name = "游ゴシック"
    Cells(15, 6).Font.Name = "游ゴシック"
    Cells(15, 7).Font.Name = "游ゴシック"
    Cells(16, 4).Font.Name = "游ゴシック"
    Cells(16, 5).Font.Name = "游ゴシック"
    Cells(16, 6).Font.Name = "游ゴシック"
    Cells(16, 7).Font.Name = "游ゴシック"
    Cells(17, 4).Font.Size = 14
    Cells(17, 4).Font.Name = "BIZ UDPゴシック"
    Cells(17, 4).Font.Color = 1315860
    Cells(17, 4).Font.Bold = True
    Cells(17, 5).Font.Name = "游ゴシック"
    Cells(17, 6).Font.Name = "游ゴシック"
    Cells(17, 7).Font.Name = "游ゴシック"
    Cells(18, 4).Font.Name = "游ゴシック"
end Function
Function revival1()
    Cells(18, 5).Font.Name = "游ゴシック"
    Cells(18, 6).Font.Name = "游ゴシック"
    Cells(18, 7).Font.Name = "游ゴシック"
    Cells(19, 4).Font.Name = "游ゴシック"
    Cells(19, 5).Font.Name = "游ゴシック"
    Cells(19, 6).Font.Name = "游ゴシック"
    Cells(19, 7).Font.Name = "游ゴシック"
    Cells(20, 4).Font.Name = "游ゴシック"
    Cells(20, 5).Font.Name = "游ゴシック"
    Cells(20, 6).Font.Name = "游ゴシック"
    Cells(20, 7).Font.Name = "游ゴシック"
    Cells(21, 4).Font.Name = "游ゴシック"
    Cells(21, 5).Font.Name = "游ゴシック"
    Cells(21, 6).Font.Name = "游ゴシック"
    Cells(21, 7).Font.Name = "游ゴシック"
    Cells(22, 4).Font.Name = "游ゴシック"
    Cells(22, 5).Font.Name = "游ゴシック"
    Cells(22, 6).Font.Name = "游ゴシック"
    Cells(22, 7).Font.Name = "游ゴシック"
    Cells(23, 4).Font.Name = "游ゴシック"
    Cells(23, 5).Font.Name = "游ゴシック"
    Cells(23, 6).Font.Name = "游ゴシック"
    Cells(23, 7).Font.Name = "游ゴシック"
    Cells(24, 4).Font.Name = "游ゴシック"
    Cells(24, 5).Font.Name = "游ゴシック"
    Cells(24, 6).Font.Name = "游ゴシック"
    Cells(24, 7).Font.Name = "游ゴシック"
    Cells(25, 4).Font.Name = "游ゴシック"
    Cells(25, 5).Font.Name = "游ゴシック"
    Cells(25, 6).Font.Name = "游ゴシック"
end Function
Function revival2()
    Cells(25, 7).Font.Size = 14
    Cells(25, 7).Font.Name = "BIZ UDPゴシック"
    Cells(25, 7).Font.Color = 1315860
    Cells(25, 7).Font.Bold = True
    Cells(26, 4).Font.Name = "游ゴシック"
    Cells(26, 5).Font.Name = "游ゴシック"
    Cells(26, 6).Font.Name = "游ゴシック"
    Cells(26, 7).Font.Name = "游ゴシック"
    Cells(27, 4).Font.Size = 14
    Cells(27, 4).Font.Name = "BIZ UDPゴシック"
    Cells(27, 4).Font.Color = 1315860
    Cells(27, 4).Font.Bold = True
    Cells(27, 5).Font.Name = "游ゴシック"
    Cells(27, 6).Font.Name = "游ゴシック"
    Cells(27, 7).Font.Name = "游ゴシック"
    Cells(28, 4).Font.Size = 14
    Cells(28, 4).Font.Name = "BIZ UDPゴシック"
    Cells(28, 4).Font.Color = 1315860
    Cells(28, 4).Font.Bold = True
    Cells(28, 5).Font.Name = "游ゴシック"
    Cells(28, 6).Font.Name = "游ゴシック"
    Cells(28, 7).Font.Name = "游ゴシック"
    Cells(29, 4).Font.Name = "游ゴシック"
    Cells(29, 5).Font.Name = "游ゴシック"
    Cells(29, 6).Font.Name = "游ゴシック"
    Cells(29, 7).Font.Name = "游ゴシック"
    Cells(30, 4).Font.Name = "游ゴシック"
    Cells(30, 5).Font.Name = "游ゴシック"
    Cells(30, 6).Font.Name = "游ゴシック"
    Cells(30, 7).Font.Name = "游ゴシック"
    Cells(31, 4).Font.Name = "游ゴシック"
    Cells(31, 5).Font.Name = "游ゴシック"
    Cells(31, 6).Font.Name = "游ゴシック"
    Cells(31, 7).Font.Name = "游ゴシック"
    Cells(32, 4).Font.Name = "游ゴシック"
    Cells(32, 5).Font.Name = "游ゴシック"
    Cells(32, 6).Font.Name = "游ゴシック"
    Cells(32, 7).Font.Name = "游ゴシック"
    Cells(33, 4).Font.Name = "游ゴシック"
end Function
Function revival3()
    Cells(33, 5).Font.Name = "游ゴシック"
    Cells(33, 6).Font.Name = "游ゴシック"
    Cells(33, 7).Font.Name = "游ゴシック"
    Cells(34, 4).Font.Name = "游ゴシック"
    Cells(34, 5).Font.Name = "游ゴシック"
    Cells(34, 6).Font.Name = "游ゴシック"
    Cells(34, 7).Font.Name = "游ゴシック"
    Cells(35, 4).Font.Name = "游ゴシック"
    Cells(35, 5).Font.Name = "游ゴシック"
    Cells(35, 6).Font.Name = "游ゴシック"
    Cells(35, 7).Font.Name = "游ゴシック"
    Cells(36, 4).Font.Name = "游ゴシック"
    Cells(36, 5).Font.Name = "游ゴシック"
    Cells(36, 6).Font.Name = "游ゴシック"
    Cells(36, 7).Font.Size = 14
    Cells(36, 7).Font.Name = "BIZ UDPゴシック"
    Cells(36, 7).Font.Color = 1315860
    Cells(36, 7).Font.Bold = True
    Cells(37, 4).Font.Name = "游ゴシック"
    Cells(37, 5).Font.Name = "游ゴシック"
    Cells(37, 6).Font.Name = "游ゴシック"
    Cells(37, 7).Font.Name = "游ゴシック"
    Cells(38, 4).Font.Name = "游ゴシック"
    Cells(38, 5).Font.Name = "游ゴシック"
    Cells(38, 6).Font.Name = "游ゴシック"
    Cells(38, 7).Font.Name = "游ゴシック"
    Cells(39, 4).Font.Size = 14
    Cells(39, 4).Font.Name = "BIZ UDPゴシック"
    Cells(39, 4).Font.Color = 1315860
    Cells(39, 4).Font.Bold = True
    Cells(39, 5).Font.Name = "游ゴシック"
    Cells(39, 6).Font.Name = "游ゴシック"
    Cells(39, 7).Font.Name = "游ゴシック"
    Rows(3).RowHeight = 18.75
    Rows(4).RowHeight = 18.75
    Rows(5).RowHeight = 18.75
    Rows(6).RowHeight = 18.75
    Rows(7).RowHeight = 18.75
    Rows(8).RowHeight = 18.75
    Rows(9).RowHeight = 18.75
    Rows(10).RowHeight = 18.75
    Rows(11).RowHeight = 18.75
    Rows(12).RowHeight = 18.75
    Rows(13).RowHeight = 18.75
    Rows(14).RowHeight = 18.75
    Rows(15).RowHeight = 18.75
    Rows(16).RowHeight = 18.75
    Rows(17).RowHeight = 18.75
    Rows(18).RowHeight = 18.75
    Rows(19).RowHeight = 18.75
    Rows(20).RowHeight = 18.75
    Rows(21).RowHeight = 18.75
    Rows(22).RowHeight = 18.75
    Rows(23).RowHeight = 18.75
    Rows(24).RowHeight = 18.75
    Rows(25).RowHeight = 18.75
    Rows(26).RowHeight = 18.75
    Rows(27).RowHeight = 18.75
    Rows(28).RowHeight = 18.75
    Rows(29).RowHeight = 18.75
    Rows(30).RowHeight = 18.75
    Rows(31).RowHeight = 18.75
    Rows(32).RowHeight = 18.75
    Rows(33).RowHeight = 18.75
    Rows(34).RowHeight = 18.75
    Rows(35).RowHeight = 18.75
    Rows(36).RowHeight = 18.75
    Rows(37).RowHeight = 18.75
    Rows(38).RowHeight = 18.75
    Rows(39).RowHeight = 18.75
    Columns(4).ColumnWidth = 8.38
    Columns(5).ColumnWidth = 8.38
    Columns(6).ColumnWidth = 8.38
    Columns(7).ColumnWidth = 8.38
    Dim onShape As Object
    Set onShape = ActiveSheet.Shapes.AddShape(1,54,56.25,183.4285,104.4642)
    onShape.Name = "Rectangle 12"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 2185902
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "①　"
    onShape.Fill.ForeColor.RGB = 3243501
    onShape.TextFrame2.TextRange.Font.Size = 72
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 2
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(1,378,56.25,183.4286,104.4642)
    onShape.Name = "Rectangle 13"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 7895160
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "②　"
    onShape.Fill.ForeColor.RGB = 10855845
    onShape.TextFrame2.TextRange.Font.Size = 72
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 2
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(1,303.2143,211.6072,183.8572,104.4642)
    onShape.Name = "Rectangle 14"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 9392687
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "③　"
    onShape.Fill.ForeColor.RGB = 12874308
    onShape.TextFrame2.TextRange.Font.Size = 72
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 2
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(1,587.1429,252.3215,183.8571,103.9285)
    onShape.Name = "Rectangle 15"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3309136
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "④　"
    onShape.Fill.ForeColor.RGB = 4697456
    onShape.TextFrame2.TextRange.Font.Size = 72
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 2
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(1,586.0714,400.1785,183.8571,104.4642)
    onShape.Name = "Rectangle 16"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 36028
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "⑤　"
    onShape.Fill.ForeColor.RGB = 49407
    onShape.TextFrame2.TextRange.Font.Size = 72
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 2
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(1,831.4286,401.25,183.4285,104.4642)
    onShape.Name = "Rectangle 17"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 0
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "⑥　"
    onShape.Fill.ForeColor.RGB = 0
    onShape.TextFrame2.TextRange.Font.Size = 72
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 2
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
End Function
Sub revival()
    Worksheets.Add After:=Worksheets(Worksheets.Count)
    CALL revival0()
    CALL revival1()
    CALL revival2()
    CALL revival3()
    Worksheets(1).select
end sub