Attribute VB_Name = "setup"
Function revival0()
    ActiveWindow.DisplayGridlines = False
    ActiveWindow.Zoom = 85
    ActiveSheet.Name = "シェイプ一覧"
    Cells(1, 1) = "No"
    Cells(1, 1).Font.Name = "Meiryo UI"
    Cells(1, 1).Interior.Color = 13431551
    Cells(1, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeTop).color = 0
    Cells(1, 1).Borders(xlEdgeTop).weight = 2
    Cells(1, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeBottom).color = 0
    Cells(1, 1).Borders(xlEdgeBottom).weight = 2
    Cells(1, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeLeft).color = 0
    Cells(1, 1).Borders(xlEdgeLeft).weight = 2
    Cells(1, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeRight).color = 0
    Cells(1, 1).Borders(xlEdgeRight).weight = 2
    Cells(1, 2) = "種別"
    Cells(1, 2).Font.Name = "Meiryo UI"
    Cells(1, 2).Interior.Color = 13431551
    Cells(1, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeTop).color = 0
    Cells(1, 2).Borders(xlEdgeTop).weight = 2
    Cells(1, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeBottom).color = 0
    Cells(1, 2).Borders(xlEdgeBottom).weight = 2
    Cells(1, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeLeft).color = 0
    Cells(1, 2).Borders(xlEdgeLeft).weight = 2
    Cells(1, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeRight).color = 0
    Cells(1, 2).Borders(xlEdgeRight).weight = 2
    Cells(1, 3) = "値"
    Cells(1, 3).Font.Name = "Meiryo UI"
    Cells(1, 3).Interior.Color = 13431551
    Cells(1, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeTop).color = 0
    Cells(1, 3).Borders(xlEdgeTop).weight = 2
    Cells(1, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeBottom).color = 0
    Cells(1, 3).Borders(xlEdgeBottom).weight = 2
    Cells(1, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeLeft).color = 0
    Cells(1, 3).Borders(xlEdgeLeft).weight = 2
    Cells(1, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeRight).color = 0
    Cells(1, 3).Borders(xlEdgeRight).weight = 2
    Cells(1, 4) = "始点"
    Cells(1, 4).Font.Name = "Meiryo UI"
    Cells(1, 4).Interior.Color = 13431551
    Cells(1, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeTop).color = 0
    Cells(1, 4).Borders(xlEdgeTop).weight = 2
    Cells(1, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeBottom).color = 0
    Cells(1, 4).Borders(xlEdgeBottom).weight = 2
    Cells(1, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeLeft).color = 0
    Cells(1, 4).Borders(xlEdgeLeft).weight = 2
    Cells(1, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeRight).color = 0
    Cells(1, 4).Borders(xlEdgeRight).weight = 2
    Cells(1, 5) = "終点"
    Cells(1, 5).Font.Name = "Meiryo UI"
    Cells(1, 5).Interior.Color = 13431551
    Cells(1, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeTop).color = 0
    Cells(1, 5).Borders(xlEdgeTop).weight = 2
    Cells(1, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeBottom).color = 0
    Cells(1, 5).Borders(xlEdgeBottom).weight = 2
    Cells(1, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeLeft).color = 0
    Cells(1, 5).Borders(xlEdgeLeft).weight = 2
    Cells(1, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeRight).color = 0
    Cells(1, 5).Borders(xlEdgeRight).weight = 2
    Cells(1, 6) = "形"
    Cells(1, 6).Font.Name = "Meiryo UI"
    Cells(1, 6).Interior.Color = 13431551
    Cells(1, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeTop).color = 0
    Cells(1, 6).Borders(xlEdgeTop).weight = 2
    Cells(1, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeBottom).color = 0
    Cells(1, 6).Borders(xlEdgeBottom).weight = 2
    Cells(1, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeLeft).color = 0
    Cells(1, 6).Borders(xlEdgeLeft).weight = 2
    Cells(1, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeRight).color = 0
    Cells(1, 6).Borders(xlEdgeRight).weight = 2
    Cells(1, 7).Font.Name = "游ゴシック"
    Cells(1, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 7).Borders(xlEdgeLeft).color = 0
    Cells(1, 7).Borders(xlEdgeLeft).weight = 2
    Cells(1, 8).Font.Name = "游ゴシック"
    Cells(1, 9).Font.Name = "游ゴシック"
    Cells(1, 10).Font.Name = "游ゴシック"
    Cells(1, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 10).Borders(xlEdgeRight).color = 0
    Cells(1, 10).Borders(xlEdgeRight).weight = 2
    Cells(1, 11) = "処理No"
    Cells(1, 11).Font.Name = "游ゴシック"
    Cells(1, 11).Interior.Color = 13431551
    Cells(1, 11).Font.Bold = True
    Cells(1, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 11).Borders(xlEdgeTop).color = 0
    Cells(1, 11).Borders(xlEdgeTop).weight = 2
    Cells(1, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 11).Borders(xlEdgeBottom).color = 0
    Cells(1, 11).Borders(xlEdgeBottom).weight = 2
    Cells(1, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 11).Borders(xlEdgeLeft).color = 0
    Cells(1, 11).Borders(xlEdgeLeft).weight = 2
    Cells(1, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 11).Borders(xlEdgeRight).color = 0
    Cells(1, 11).Borders(xlEdgeRight).weight = 2
    Cells(1, 12) = "フローNo"
    Cells(1, 12).Font.Name = "游ゴシック"
    Cells(1, 12).Interior.Color = 13431551
    Cells(1, 12).Font.Bold = True
    Cells(1, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 12).Borders(xlEdgeTop).color = 0
    Cells(1, 12).Borders(xlEdgeTop).weight = 2
    Cells(1, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 12).Borders(xlEdgeBottom).color = 0
    Cells(1, 12).Borders(xlEdgeBottom).weight = 2
    Cells(1, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 12).Borders(xlEdgeLeft).color = 0
    Cells(1, 12).Borders(xlEdgeLeft).weight = 2
    Cells(1, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 12).Borders(xlEdgeRight).color = 0
    Cells(1, 12).Borders(xlEdgeRight).weight = 2
    Cells(1, 13) = "遷移先"
    Cells(1, 13).Font.Name = "游ゴシック"
    Cells(1, 13).Interior.Color = 13431551
    Cells(1, 13).Font.Bold = True
    Cells(1, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 13).Borders(xlEdgeTop).color = 0
    Cells(1, 13).Borders(xlEdgeTop).weight = 2
    Cells(1, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 13).Borders(xlEdgeBottom).color = 0
    Cells(1, 13).Borders(xlEdgeBottom).weight = 2
    Cells(1, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 13).Borders(xlEdgeLeft).color = 0
    Cells(1, 13).Borders(xlEdgeLeft).weight = 2
    Cells(1, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 13).Borders(xlEdgeRight).color = 0
    Cells(1, 13).Borders(xlEdgeRight).weight = 2
    Cells(1, 14) = "種別"
    Cells(1, 14).Font.Name = "游ゴシック"
    Cells(1, 14).Interior.Color = 13431551
    Cells(1, 14).Font.Bold = True
    Cells(1, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 14).Borders(xlEdgeTop).color = 0
    Cells(1, 14).Borders(xlEdgeTop).weight = 2
    Cells(1, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 14).Borders(xlEdgeBottom).color = 0
    Cells(1, 14).Borders(xlEdgeBottom).weight = 2
    Cells(1, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 14).Borders(xlEdgeLeft).color = 0
    Cells(1, 14).Borders(xlEdgeLeft).weight = 2
    Cells(1, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 14).Borders(xlEdgeRight).color = 0
    Cells(1, 14).Borders(xlEdgeRight).weight = 2
    Cells(1, 15) = "フローテキスト"
    Cells(1, 15).Font.Name = "游ゴシック"
    Cells(1, 15).Interior.Color = 13431551
    Cells(1, 15).Font.Bold = True
    Cells(1, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 15).Borders(xlEdgeTop).color = 0
    Cells(1, 15).Borders(xlEdgeTop).weight = 2
    Cells(1, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 15).Borders(xlEdgeBottom).color = 0
    Cells(1, 15).Borders(xlEdgeBottom).weight = 2
    Cells(1, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 15).Borders(xlEdgeLeft).color = 0
    Cells(1, 15).Borders(xlEdgeLeft).weight = 2
    Cells(1, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 15).Borders(xlEdgeRight).color = 0
    Cells(1, 15).Borders(xlEdgeRight).weight = 2
    Cells(2, 1) = "1"
    Cells(2, 1).Font.Name = "Meiryo UI"
    Cells(2, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeTop).color = 0
    Cells(2, 1).Borders(xlEdgeTop).weight = 2
    Cells(2, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeBottom).color = 0
    Cells(2, 1).Borders(xlEdgeBottom).weight = 2
    Cells(2, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeLeft).color = 0
    Cells(2, 1).Borders(xlEdgeLeft).weight = 2
    Cells(2, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeRight).color = 0
    Cells(2, 1).Borders(xlEdgeRight).weight = 2
    Cells(2, 2) = "ロジック"
    Cells(2, 2).Font.Name = "Meiryo UI"
    Cells(2, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeTop).color = 0
    Cells(2, 2).Borders(xlEdgeTop).weight = 2
    Cells(2, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeBottom).color = 0
    Cells(2, 2).Borders(xlEdgeBottom).weight = 2
    Cells(2, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeLeft).color = 0
    Cells(2, 2).Borders(xlEdgeLeft).weight = 2
    Cells(2, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeRight).color = 0
    Cells(2, 2).Borders(xlEdgeRight).weight = 2
    Cells(2, 3) = "61"
    Cells(2, 3).Font.Name = "Meiryo UI"
    Cells(2, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeTop).color = 0
    Cells(2, 3).Borders(xlEdgeTop).weight = 2
    Cells(2, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeBottom).color = 0
    Cells(2, 3).Borders(xlEdgeBottom).weight = 2
    Cells(2, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeLeft).color = 0
    Cells(2, 3).Borders(xlEdgeLeft).weight = 2
    Cells(2, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeRight).color = 0
    Cells(2, 3).Borders(xlEdgeRight).weight = 2
    Cells(2, 4) = "3"
    Cells(2, 4).Font.Name = "Meiryo UI"
    Cells(2, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeTop).color = 0
    Cells(2, 4).Borders(xlEdgeTop).weight = 2
    Cells(2, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeBottom).color = 0
    Cells(2, 4).Borders(xlEdgeBottom).weight = 2
    Cells(2, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeLeft).color = 0
    Cells(2, 4).Borders(xlEdgeLeft).weight = 2
    Cells(2, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeRight).color = 0
    Cells(2, 4).Borders(xlEdgeRight).weight = 2
    Cells(2, 5) = "1"
    Cells(2, 5).Font.Name = "Meiryo UI"
    Cells(2, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeTop).color = 0
    Cells(2, 5).Borders(xlEdgeTop).weight = 2
    Cells(2, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeBottom).color = 0
    Cells(2, 5).Borders(xlEdgeBottom).weight = 2
    Cells(2, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeLeft).color = 0
    Cells(2, 5).Borders(xlEdgeLeft).weight = 2
    Cells(2, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeRight).color = 0
    Cells(2, 5).Borders(xlEdgeRight).weight = 2
    Cells(2, 6).Font.Name = "Meiryo UI"
    Cells(2, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeTop).color = 0
    Cells(2, 6).Borders(xlEdgeTop).weight = 2
    Cells(2, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeBottom).color = 0
    Cells(2, 6).Borders(xlEdgeBottom).weight = 2
    Cells(2, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeLeft).color = 0
    Cells(2, 6).Borders(xlEdgeLeft).weight = 2
    Cells(2, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeRight).color = 0
    Cells(2, 6).Borders(xlEdgeRight).weight = 2
    Cells(2, 7).Font.Name = "游ゴシック"
    Cells(2, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 7).Borders(xlEdgeLeft).color = 0
    Cells(2, 7).Borders(xlEdgeLeft).weight = 2
    Cells(2, 8).Font.Name = "游ゴシック"
    Cells(2, 9).Font.Name = "游ゴシック"
    Cells(2, 10).Font.Name = "游ゴシック"
    Cells(2, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 10).Borders(xlEdgeRight).color = 0
    Cells(2, 10).Borders(xlEdgeRight).weight = 2
    Cells(2, 11).Font.Name = "游ゴシック"
    Cells(2, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 11).Borders(xlEdgeTop).color = 0
    Cells(2, 11).Borders(xlEdgeTop).weight = 2
    Cells(2, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 11).Borders(xlEdgeBottom).color = 0
    Cells(2, 11).Borders(xlEdgeBottom).weight = 2
    Cells(2, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 11).Borders(xlEdgeLeft).color = 0
    Cells(2, 11).Borders(xlEdgeLeft).weight = 2
    Cells(2, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 11).Borders(xlEdgeRight).color = 0
    Cells(2, 11).Borders(xlEdgeRight).weight = 2
    Cells(2, 12) = "1"
    Cells(2, 12).Font.Name = "游ゴシック"
    Cells(2, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 12).Borders(xlEdgeTop).color = 0
    Cells(2, 12).Borders(xlEdgeTop).weight = 2
    Cells(2, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 12).Borders(xlEdgeBottom).color = 0
    Cells(2, 12).Borders(xlEdgeBottom).weight = 2
    Cells(2, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 12).Borders(xlEdgeLeft).color = 0
    Cells(2, 12).Borders(xlEdgeLeft).weight = 2
    Cells(2, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 12).Borders(xlEdgeRight).color = 0
    Cells(2, 12).Borders(xlEdgeRight).weight = 2
    Cells(2, 13) = "2"
    Cells(2, 13).Font.Name = "游ゴシック"
    Cells(2, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 13).Borders(xlEdgeTop).color = 0
    Cells(2, 13).Borders(xlEdgeTop).weight = 2
    Cells(2, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 13).Borders(xlEdgeBottom).color = 0
    Cells(2, 13).Borders(xlEdgeBottom).weight = 2
    Cells(2, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 13).Borders(xlEdgeLeft).color = 0
    Cells(2, 13).Borders(xlEdgeLeft).weight = 2
    Cells(2, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 13).Borders(xlEdgeRight).color = 0
    Cells(2, 13).Borders(xlEdgeRight).weight = 2
    Cells(2, 14) = "開始"
    Cells(2, 14).Font.Name = "游ゴシック"
    Cells(2, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 14).Borders(xlEdgeTop).color = 0
    Cells(2, 14).Borders(xlEdgeTop).weight = 2
    Cells(2, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 14).Borders(xlEdgeBottom).color = 0
    Cells(2, 14).Borders(xlEdgeBottom).weight = 2
    Cells(2, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 14).Borders(xlEdgeLeft).color = 0
    Cells(2, 14).Borders(xlEdgeLeft).weight = 2
    Cells(2, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 14).Borders(xlEdgeRight).color = 0
    Cells(2, 14).Borders(xlEdgeRight).weight = 2
    Cells(2, 15) = "開始"
    Cells(2, 15).Font.Name = "游ゴシック"
    Cells(2, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 15).Borders(xlEdgeTop).color = 0
    Cells(2, 15).Borders(xlEdgeTop).weight = 2
    Cells(2, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 15).Borders(xlEdgeBottom).color = 0
    Cells(2, 15).Borders(xlEdgeBottom).weight = 2
    Cells(2, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 15).Borders(xlEdgeLeft).color = 0
    Cells(2, 15).Borders(xlEdgeLeft).weight = 2
    Cells(2, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 15).Borders(xlEdgeRight).color = 0
    Cells(2, 15).Borders(xlEdgeRight).weight = 2
    Cells(3, 1) = "2"
    Cells(3, 1).Font.Name = "Meiryo UI"
    Cells(3, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeTop).color = 0
    Cells(3, 1).Borders(xlEdgeTop).weight = 2
    Cells(3, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeBottom).color = 0
    Cells(3, 1).Borders(xlEdgeBottom).weight = 2
    Cells(3, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeLeft).color = 0
    Cells(3, 1).Borders(xlEdgeLeft).weight = 2
    Cells(3, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeRight).color = 0
    Cells(3, 1).Borders(xlEdgeRight).weight = 2
    Cells(3, 2) = "分岐/Switch"
    Cells(3, 2).Font.Name = "Meiryo UI"
    Cells(3, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeTop).color = 0
    Cells(3, 2).Borders(xlEdgeTop).weight = 2
    Cells(3, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeBottom).color = 0
    Cells(3, 2).Borders(xlEdgeBottom).weight = 2
    Cells(3, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeLeft).color = 0
    Cells(3, 2).Borders(xlEdgeLeft).weight = 2
    Cells(3, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeRight).color = 0
    Cells(3, 2).Borders(xlEdgeRight).weight = 2
    Cells(3, 3) = "63"
    Cells(3, 3).Font.Name = "Meiryo UI"
    Cells(3, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeTop).color = 0
    Cells(3, 3).Borders(xlEdgeTop).weight = 2
    Cells(3, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeBottom).color = 0
    Cells(3, 3).Borders(xlEdgeBottom).weight = 2
    Cells(3, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeLeft).color = 0
    Cells(3, 3).Borders(xlEdgeLeft).weight = 2
    Cells(3, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeRight).color = 0
    Cells(3, 3).Borders(xlEdgeRight).weight = 2
    Cells(3, 4) = "3"
    Cells(3, 4).Font.Name = "Meiryo UI"
    Cells(3, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeTop).color = 0
    Cells(3, 4).Borders(xlEdgeTop).weight = 2
    Cells(3, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeBottom).color = 0
    Cells(3, 4).Borders(xlEdgeBottom).weight = 2
    Cells(3, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeLeft).color = 0
    Cells(3, 4).Borders(xlEdgeLeft).weight = 2
    Cells(3, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeRight).color = 0
    Cells(3, 4).Borders(xlEdgeRight).weight = 2
    Cells(3, 5) = "1"
    Cells(3, 5).Font.Name = "Meiryo UI"
    Cells(3, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeTop).color = 0
    Cells(3, 5).Borders(xlEdgeTop).weight = 2
    Cells(3, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeBottom).color = 0
    Cells(3, 5).Borders(xlEdgeBottom).weight = 2
    Cells(3, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeLeft).color = 0
    Cells(3, 5).Borders(xlEdgeLeft).weight = 2
    Cells(3, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeRight).color = 0
    Cells(3, 5).Borders(xlEdgeRight).weight = 2
    Cells(3, 6).Font.Name = "Meiryo UI"
    Cells(3, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeTop).color = 0
    Cells(3, 6).Borders(xlEdgeTop).weight = 2
    Cells(3, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeBottom).color = 0
    Cells(3, 6).Borders(xlEdgeBottom).weight = 2
    Cells(3, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeLeft).color = 0
    Cells(3, 6).Borders(xlEdgeLeft).weight = 2
    Cells(3, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeRight).color = 0
    Cells(3, 6).Borders(xlEdgeRight).weight = 2
    Cells(3, 7).Font.Name = "游ゴシック"
    Cells(3, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 7).Borders(xlEdgeLeft).color = 0
    Cells(3, 7).Borders(xlEdgeLeft).weight = 2
    Cells(3, 8).Font.Name = "游ゴシック"
    Cells(3, 9).Font.Name = "游ゴシック"
    Cells(3, 10).Font.Name = "游ゴシック"
    Cells(3, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 10).Borders(xlEdgeRight).color = 0
    Cells(3, 10).Borders(xlEdgeRight).weight = 2
    Cells(3, 11) = "1"
    Cells(3, 11).Font.Name = "游ゴシック"
    Cells(3, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 11).Borders(xlEdgeTop).color = 0
    Cells(3, 11).Borders(xlEdgeTop).weight = 2
    Cells(3, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 11).Borders(xlEdgeBottom).color = 0
    Cells(3, 11).Borders(xlEdgeBottom).weight = 2
    Cells(3, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 11).Borders(xlEdgeLeft).color = 0
    Cells(3, 11).Borders(xlEdgeLeft).weight = 2
    Cells(3, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 11).Borders(xlEdgeRight).color = 0
    Cells(3, 11).Borders(xlEdgeRight).weight = 2
    Cells(3, 12) = "2"
    Cells(3, 12).Font.Name = "游ゴシック"
    Cells(3, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 12).Borders(xlEdgeTop).color = 0
    Cells(3, 12).Borders(xlEdgeTop).weight = 2
    Cells(3, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 12).Borders(xlEdgeBottom).color = 0
    Cells(3, 12).Borders(xlEdgeBottom).weight = 2
    Cells(3, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 12).Borders(xlEdgeLeft).color = 0
    Cells(3, 12).Borders(xlEdgeLeft).weight = 2
    Cells(3, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 12).Borders(xlEdgeRight).color = 0
    Cells(3, 12).Borders(xlEdgeRight).weight = 2
    Cells(3, 13) = "3"
    Cells(3, 13).Font.Name = "游ゴシック"
    Cells(3, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 13).Borders(xlEdgeTop).color = 0
    Cells(3, 13).Borders(xlEdgeTop).weight = 2
    Cells(3, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 13).Borders(xlEdgeBottom).color = 0
    Cells(3, 13).Borders(xlEdgeBottom).weight = 2
    Cells(3, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 13).Borders(xlEdgeLeft).color = 0
    Cells(3, 13).Borders(xlEdgeLeft).weight = 2
    Cells(3, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 13).Borders(xlEdgeRight).color = 0
    Cells(3, 13).Borders(xlEdgeRight).weight = 2
    Cells(3, 14) = "ロジック"
    Cells(3, 14).Font.Name = "游ゴシック"
    Cells(3, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 14).Borders(xlEdgeTop).color = 0
    Cells(3, 14).Borders(xlEdgeTop).weight = 2
    Cells(3, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 14).Borders(xlEdgeBottom).color = 0
    Cells(3, 14).Borders(xlEdgeBottom).weight = 2
    Cells(3, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 14).Borders(xlEdgeLeft).color = 0
    Cells(3, 14).Borders(xlEdgeLeft).weight = 2
    Cells(3, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 14).Borders(xlEdgeRight).color = 0
    Cells(3, 14).Borders(xlEdgeRight).weight = 2
    Cells(3, 15) = "蓋をあけ、お湯を注ぐ"
    Cells(3, 15).Font.Name = "游ゴシック"
    Cells(3, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 15).Borders(xlEdgeTop).color = 0
    Cells(3, 15).Borders(xlEdgeTop).weight = 2
    Cells(3, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 15).Borders(xlEdgeBottom).color = 0
    Cells(3, 15).Borders(xlEdgeBottom).weight = 2
    Cells(3, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 15).Borders(xlEdgeLeft).color = 0
    Cells(3, 15).Borders(xlEdgeLeft).weight = 2
    Cells(3, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 15).Borders(xlEdgeRight).color = 0
    Cells(3, 15).Borders(xlEdgeRight).weight = 2
    Cells(4, 1) = "3"
    Cells(4, 1).Font.Name = "Meiryo UI"
    Cells(4, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeTop).color = 0
    Cells(4, 1).Borders(xlEdgeTop).weight = 2
    Cells(4, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeBottom).color = 0
    Cells(4, 1).Borders(xlEdgeBottom).weight = 2
    Cells(4, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeLeft).color = 0
    Cells(4, 1).Borders(xlEdgeLeft).weight = 2
    Cells(4, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeRight).color = 0
    Cells(4, 1).Borders(xlEdgeRight).weight = 2
    Cells(4, 2) = "入力/出力"
    Cells(4, 2).Font.Name = "Meiryo UI"
    Cells(4, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeTop).color = 0
    Cells(4, 2).Borders(xlEdgeTop).weight = 2
    Cells(4, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeBottom).color = 0
    Cells(4, 2).Borders(xlEdgeBottom).weight = 2
    Cells(4, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeLeft).color = 0
    Cells(4, 2).Borders(xlEdgeLeft).weight = 2
    Cells(4, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeRight).color = 0
    Cells(4, 2).Borders(xlEdgeRight).weight = 2
    Cells(4, 3) = "64"
    Cells(4, 3).Font.Name = "Meiryo UI"
    Cells(4, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeTop).color = 0
    Cells(4, 3).Borders(xlEdgeTop).weight = 2
    Cells(4, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeBottom).color = 0
    Cells(4, 3).Borders(xlEdgeBottom).weight = 2
    Cells(4, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeLeft).color = 0
    Cells(4, 3).Borders(xlEdgeLeft).weight = 2
    Cells(4, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeRight).color = 0
    Cells(4, 3).Borders(xlEdgeRight).weight = 2
    Cells(4, 4) = "5"
    Cells(4, 4).Font.Name = "Meiryo UI"
    Cells(4, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeTop).color = 0
    Cells(4, 4).Borders(xlEdgeTop).weight = 2
    Cells(4, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeBottom).color = 0
    Cells(4, 4).Borders(xlEdgeBottom).weight = 2
    Cells(4, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeLeft).color = 0
    Cells(4, 4).Borders(xlEdgeLeft).weight = 2
    Cells(4, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeRight).color = 0
    Cells(4, 4).Borders(xlEdgeRight).weight = 2
    Cells(4, 5) = "2"
    Cells(4, 5).Font.Name = "Meiryo UI"
    Cells(4, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeTop).color = 0
    Cells(4, 5).Borders(xlEdgeTop).weight = 2
    Cells(4, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeBottom).color = 0
    Cells(4, 5).Borders(xlEdgeBottom).weight = 2
    Cells(4, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeLeft).color = 0
    Cells(4, 5).Borders(xlEdgeLeft).weight = 2
    Cells(4, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeRight).color = 0
    Cells(4, 5).Borders(xlEdgeRight).weight = 2
    Cells(4, 6).Font.Name = "Meiryo UI"
    Cells(4, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeTop).color = 0
    Cells(4, 6).Borders(xlEdgeTop).weight = 2
    Cells(4, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeBottom).color = 0
    Cells(4, 6).Borders(xlEdgeBottom).weight = 2
    Cells(4, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeLeft).color = 0
    Cells(4, 6).Borders(xlEdgeLeft).weight = 2
    Cells(4, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeRight).color = 0
    Cells(4, 6).Borders(xlEdgeRight).weight = 2
    Cells(4, 7).Font.Name = "游ゴシック"
    Cells(4, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 7).Borders(xlEdgeLeft).color = 0
    Cells(4, 7).Borders(xlEdgeLeft).weight = 2
    Cells(4, 8).Font.Name = "游ゴシック"
    Cells(4, 9).Font.Name = "游ゴシック"
    Cells(4, 10).Font.Name = "游ゴシック"
    Cells(4, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 10).Borders(xlEdgeRight).color = 0
    Cells(4, 10).Borders(xlEdgeRight).weight = 2
    Cells(4, 11) = "2"
    Cells(4, 11).Font.Name = "游ゴシック"
    Cells(4, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 11).Borders(xlEdgeTop).color = 0
    Cells(4, 11).Borders(xlEdgeTop).weight = 2
    Cells(4, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 11).Borders(xlEdgeBottom).color = 0
    Cells(4, 11).Borders(xlEdgeBottom).weight = 2
    Cells(4, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 11).Borders(xlEdgeLeft).color = 0
    Cells(4, 11).Borders(xlEdgeLeft).weight = 2
    Cells(4, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 11).Borders(xlEdgeRight).color = 0
    Cells(4, 11).Borders(xlEdgeRight).weight = 2
    Cells(4, 12) = "3"
    Cells(4, 12).Font.Name = "游ゴシック"
    Cells(4, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 12).Borders(xlEdgeTop).color = 0
    Cells(4, 12).Borders(xlEdgeTop).weight = 2
    Cells(4, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 12).Borders(xlEdgeBottom).color = 0
    Cells(4, 12).Borders(xlEdgeBottom).weight = 2
    Cells(4, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 12).Borders(xlEdgeLeft).color = 0
    Cells(4, 12).Borders(xlEdgeLeft).weight = 2
    Cells(4, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 12).Borders(xlEdgeRight).color = 0
    Cells(4, 12).Borders(xlEdgeRight).weight = 2
    Cells(4, 13) = "4"
    Cells(4, 13).Font.Name = "游ゴシック"
    Cells(4, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 13).Borders(xlEdgeTop).color = 0
    Cells(4, 13).Borders(xlEdgeTop).weight = 2
    Cells(4, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 13).Borders(xlEdgeBottom).color = 0
    Cells(4, 13).Borders(xlEdgeBottom).weight = 2
    Cells(4, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 13).Borders(xlEdgeLeft).color = 0
    Cells(4, 13).Borders(xlEdgeLeft).weight = 2
    Cells(4, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 13).Borders(xlEdgeRight).color = 0
    Cells(4, 13).Borders(xlEdgeRight).weight = 2
    Cells(4, 14) = "ループ開始"
    Cells(4, 14).Font.Name = "游ゴシック"
    Cells(4, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 14).Borders(xlEdgeTop).color = 0
    Cells(4, 14).Borders(xlEdgeTop).weight = 2
    Cells(4, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 14).Borders(xlEdgeBottom).color = 0
    Cells(4, 14).Borders(xlEdgeBottom).weight = 2
    Cells(4, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 14).Borders(xlEdgeLeft).color = 0
    Cells(4, 14).Borders(xlEdgeLeft).weight = 2
    Cells(4, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 14).Borders(xlEdgeRight).color = 0
    Cells(4, 14).Borders(xlEdgeRight).weight = 2
    Cells(4, 15) = "継続条件：3分以内"
    Cells(4, 15).Font.Name = "游ゴシック"
    Cells(4, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 15).Borders(xlEdgeTop).color = 0
    Cells(4, 15).Borders(xlEdgeTop).weight = 2
    Cells(4, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 15).Borders(xlEdgeBottom).color = 0
    Cells(4, 15).Borders(xlEdgeBottom).weight = 2
    Cells(4, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 15).Borders(xlEdgeLeft).color = 0
    Cells(4, 15).Borders(xlEdgeLeft).weight = 2
    Cells(4, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 15).Borders(xlEdgeRight).color = 0
    Cells(4, 15).Borders(xlEdgeRight).weight = 2
    Cells(5, 1) = "4"
    Cells(5, 1).Font.Name = "Meiryo UI"
    Cells(5, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeTop).color = 0
    Cells(5, 1).Borders(xlEdgeTop).weight = 2
    Cells(5, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeBottom).color = 0
    Cells(5, 1).Borders(xlEdgeBottom).weight = 2
    Cells(5, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeLeft).color = 0
    Cells(5, 1).Borders(xlEdgeLeft).weight = 2
    Cells(5, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeRight).color = 0
    Cells(5, 1).Borders(xlEdgeRight).weight = 2
end Function
Function revival1()
    Cells(5, 2) = "サブルーチン"
    Cells(5, 2).Font.Name = "Meiryo UI"
    Cells(5, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeTop).color = 0
    Cells(5, 2).Borders(xlEdgeTop).weight = 2
    Cells(5, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeBottom).color = 0
    Cells(5, 2).Borders(xlEdgeBottom).weight = 2
    Cells(5, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeLeft).color = 0
    Cells(5, 2).Borders(xlEdgeLeft).weight = 2
    Cells(5, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeRight).color = 0
    Cells(5, 2).Borders(xlEdgeRight).weight = 2
    Cells(5, 3) = "65"
    Cells(5, 3).Font.Name = "Meiryo UI"
    Cells(5, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeTop).color = 0
    Cells(5, 3).Borders(xlEdgeTop).weight = 2
    Cells(5, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeBottom).color = 0
    Cells(5, 3).Borders(xlEdgeBottom).weight = 2
    Cells(5, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeLeft).color = 0
    Cells(5, 3).Borders(xlEdgeLeft).weight = 2
    Cells(5, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeRight).color = 0
    Cells(5, 3).Borders(xlEdgeRight).weight = 2
    Cells(5, 4) = "3"
    Cells(5, 4).Font.Name = "Meiryo UI"
    Cells(5, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeTop).color = 0
    Cells(5, 4).Borders(xlEdgeTop).weight = 2
    Cells(5, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeBottom).color = 0
    Cells(5, 4).Borders(xlEdgeBottom).weight = 2
    Cells(5, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeLeft).color = 0
    Cells(5, 4).Borders(xlEdgeLeft).weight = 2
    Cells(5, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeRight).color = 0
    Cells(5, 4).Borders(xlEdgeRight).weight = 2
    Cells(5, 5) = "1"
    Cells(5, 5).Font.Name = "Meiryo UI"
    Cells(5, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeTop).color = 0
    Cells(5, 5).Borders(xlEdgeTop).weight = 2
    Cells(5, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeBottom).color = 0
    Cells(5, 5).Borders(xlEdgeBottom).weight = 2
    Cells(5, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeLeft).color = 0
    Cells(5, 5).Borders(xlEdgeLeft).weight = 2
    Cells(5, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeRight).color = 0
    Cells(5, 5).Borders(xlEdgeRight).weight = 2
    Cells(5, 6).Font.Name = "Meiryo UI"
    Cells(5, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeTop).color = 0
    Cells(5, 6).Borders(xlEdgeTop).weight = 2
    Cells(5, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeBottom).color = 0
    Cells(5, 6).Borders(xlEdgeBottom).weight = 2
    Cells(5, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeLeft).color = 0
    Cells(5, 6).Borders(xlEdgeLeft).weight = 2
    Cells(5, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeRight).color = 0
    Cells(5, 6).Borders(xlEdgeRight).weight = 2
    Cells(5, 7).Font.Name = "游ゴシック"
    Cells(5, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 7).Borders(xlEdgeLeft).color = 0
    Cells(5, 7).Borders(xlEdgeLeft).weight = 2
    Cells(5, 8).Font.Name = "游ゴシック"
    Cells(5, 9).Font.Name = "游ゴシック"
    Cells(5, 10).Font.Name = "游ゴシック"
    Cells(5, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 10).Borders(xlEdgeRight).color = 0
    Cells(5, 10).Borders(xlEdgeRight).weight = 2
    Cells(5, 11) = "3"
    Cells(5, 11).Font.Name = "游ゴシック"
    Cells(5, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 11).Borders(xlEdgeTop).color = 0
    Cells(5, 11).Borders(xlEdgeTop).weight = 2
    Cells(5, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 11).Borders(xlEdgeBottom).color = 0
    Cells(5, 11).Borders(xlEdgeBottom).weight = 2
    Cells(5, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 11).Borders(xlEdgeLeft).color = 0
    Cells(5, 11).Borders(xlEdgeLeft).weight = 2
    Cells(5, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 11).Borders(xlEdgeRight).color = 0
    Cells(5, 11).Borders(xlEdgeRight).weight = 2
    Cells(5, 12) = "4"
    Cells(5, 12).Font.Name = "游ゴシック"
    Cells(5, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 12).Borders(xlEdgeTop).color = 0
    Cells(5, 12).Borders(xlEdgeTop).weight = 2
    Cells(5, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 12).Borders(xlEdgeBottom).color = 0
    Cells(5, 12).Borders(xlEdgeBottom).weight = 2
    Cells(5, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 12).Borders(xlEdgeLeft).color = 0
    Cells(5, 12).Borders(xlEdgeLeft).weight = 2
    Cells(5, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 12).Borders(xlEdgeRight).color = 0
    Cells(5, 12).Borders(xlEdgeRight).weight = 2
    Cells(5, 13) = "5"
    Cells(5, 13).Font.Name = "游ゴシック"
    Cells(5, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 13).Borders(xlEdgeTop).color = 0
    Cells(5, 13).Borders(xlEdgeTop).weight = 2
    Cells(5, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 13).Borders(xlEdgeBottom).color = 0
    Cells(5, 13).Borders(xlEdgeBottom).weight = 2
    Cells(5, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 13).Borders(xlEdgeLeft).color = 0
    Cells(5, 13).Borders(xlEdgeLeft).weight = 2
    Cells(5, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 13).Borders(xlEdgeRight).color = 0
    Cells(5, 13).Borders(xlEdgeRight).weight = 2
    Cells(5, 14) = "ロジック"
    Cells(5, 14).Font.Name = "游ゴシック"
    Cells(5, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 14).Borders(xlEdgeTop).color = 0
    Cells(5, 14).Borders(xlEdgeTop).weight = 2
    Cells(5, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 14).Borders(xlEdgeBottom).color = 0
    Cells(5, 14).Borders(xlEdgeBottom).weight = 2
    Cells(5, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 14).Borders(xlEdgeLeft).color = 0
    Cells(5, 14).Borders(xlEdgeLeft).weight = 2
    Cells(5, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 14).Borders(xlEdgeRight).color = 0
    Cells(5, 14).Borders(xlEdgeRight).weight = 2
    Cells(5, 15) = "蓋を閉じた状態で待つ"
    Cells(5, 15).Font.Name = "游ゴシック"
    Cells(5, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 15).Borders(xlEdgeTop).color = 0
    Cells(5, 15).Borders(xlEdgeTop).weight = 2
    Cells(5, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 15).Borders(xlEdgeBottom).color = 0
    Cells(5, 15).Borders(xlEdgeBottom).weight = 2
    Cells(5, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 15).Borders(xlEdgeLeft).color = 0
    Cells(5, 15).Borders(xlEdgeLeft).weight = 2
    Cells(5, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 15).Borders(xlEdgeRight).color = 0
    Cells(5, 15).Borders(xlEdgeRight).weight = 2
    Cells(6, 1) = "5"
    Cells(6, 1).Font.Name = "Meiryo UI"
    Cells(6, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeTop).color = 0
    Cells(6, 1).Borders(xlEdgeTop).weight = 2
    Cells(6, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeBottom).color = 0
    Cells(6, 1).Borders(xlEdgeBottom).weight = 2
    Cells(6, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeLeft).color = 0
    Cells(6, 1).Borders(xlEdgeLeft).weight = 2
    Cells(6, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeRight).color = 0
    Cells(6, 1).Borders(xlEdgeRight).weight = 2
    Cells(6, 2) = "開始/終了"
    Cells(6, 2).Font.Name = "Meiryo UI"
    Cells(6, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeTop).color = 0
    Cells(6, 2).Borders(xlEdgeTop).weight = 2
    Cells(6, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeBottom).color = 0
    Cells(6, 2).Borders(xlEdgeBottom).weight = 2
    Cells(6, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeLeft).color = 0
    Cells(6, 2).Borders(xlEdgeLeft).weight = 2
    Cells(6, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeRight).color = 0
    Cells(6, 2).Borders(xlEdgeRight).weight = 2
    Cells(6, 3) = "69"
    Cells(6, 3).Font.Name = "Meiryo UI"
    Cells(6, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeTop).color = 0
    Cells(6, 3).Borders(xlEdgeTop).weight = 2
    Cells(6, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeBottom).color = 0
    Cells(6, 3).Borders(xlEdgeBottom).weight = 2
    Cells(6, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeLeft).color = 0
    Cells(6, 3).Borders(xlEdgeLeft).weight = 2
    Cells(6, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeRight).color = 0
    Cells(6, 3).Borders(xlEdgeRight).weight = 2
    Cells(6, 4) = "3"
    Cells(6, 4).Font.Name = "Meiryo UI"
    Cells(6, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeTop).color = 0
    Cells(6, 4).Borders(xlEdgeTop).weight = 2
    Cells(6, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeBottom).color = 0
    Cells(6, 4).Borders(xlEdgeBottom).weight = 2
    Cells(6, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeLeft).color = 0
    Cells(6, 4).Borders(xlEdgeLeft).weight = 2
    Cells(6, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeRight).color = 0
    Cells(6, 4).Borders(xlEdgeRight).weight = 2
    Cells(6, 5) = "1"
    Cells(6, 5).Font.Name = "Meiryo UI"
    Cells(6, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeTop).color = 0
    Cells(6, 5).Borders(xlEdgeTop).weight = 2
    Cells(6, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeBottom).color = 0
    Cells(6, 5).Borders(xlEdgeBottom).weight = 2
    Cells(6, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeLeft).color = 0
    Cells(6, 5).Borders(xlEdgeLeft).weight = 2
    Cells(6, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeRight).color = 0
    Cells(6, 5).Borders(xlEdgeRight).weight = 2
    Cells(6, 6).Font.Name = "Meiryo UI"
    Cells(6, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeTop).color = 0
    Cells(6, 6).Borders(xlEdgeTop).weight = 2
    Cells(6, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeBottom).color = 0
    Cells(6, 6).Borders(xlEdgeBottom).weight = 2
    Cells(6, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeLeft).color = 0
    Cells(6, 6).Borders(xlEdgeLeft).weight = 2
    Cells(6, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeRight).color = 0
    Cells(6, 6).Borders(xlEdgeRight).weight = 2
    Cells(6, 7).Font.Name = "游ゴシック"
    Cells(6, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 7).Borders(xlEdgeLeft).color = 0
    Cells(6, 7).Borders(xlEdgeLeft).weight = 2
    Cells(6, 8).Font.Name = "游ゴシック"
    Cells(6, 9).Font.Name = "游ゴシック"
    Cells(6, 10).Font.Name = "游ゴシック"
    Cells(6, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 10).Borders(xlEdgeRight).color = 0
    Cells(6, 10).Borders(xlEdgeRight).weight = 2
    Cells(6, 11).Font.Name = "游ゴシック"
    Cells(6, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 11).Borders(xlEdgeTop).color = 0
    Cells(6, 11).Borders(xlEdgeTop).weight = 2
    Cells(6, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 11).Borders(xlEdgeBottom).color = 0
    Cells(6, 11).Borders(xlEdgeBottom).weight = 2
    Cells(6, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 11).Borders(xlEdgeLeft).color = 0
    Cells(6, 11).Borders(xlEdgeLeft).weight = 2
    Cells(6, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 11).Borders(xlEdgeRight).color = 0
    Cells(6, 11).Borders(xlEdgeRight).weight = 2
    Cells(6, 12) = "5"
    Cells(6, 12).Font.Name = "游ゴシック"
    Cells(6, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 12).Borders(xlEdgeTop).color = 0
    Cells(6, 12).Borders(xlEdgeTop).weight = 2
    Cells(6, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 12).Borders(xlEdgeBottom).color = 0
    Cells(6, 12).Borders(xlEdgeBottom).weight = 2
    Cells(6, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 12).Borders(xlEdgeLeft).color = 0
    Cells(6, 12).Borders(xlEdgeLeft).weight = 2
    Cells(6, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 12).Borders(xlEdgeRight).color = 0
    Cells(6, 12).Borders(xlEdgeRight).weight = 2
    Cells(6, 13) = "Next:3"& vbLf & "End:6"
    Cells(6, 13).WrapText  = True
    Cells(6, 13).Font.Name = "游ゴシック"
    Cells(6, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 13).Borders(xlEdgeTop).color = 0
    Cells(6, 13).Borders(xlEdgeTop).weight = 2
    Cells(6, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 13).Borders(xlEdgeBottom).color = 0
    Cells(6, 13).Borders(xlEdgeBottom).weight = 2
    Cells(6, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 13).Borders(xlEdgeLeft).color = 0
    Cells(6, 13).Borders(xlEdgeLeft).weight = 2
    Cells(6, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 13).Borders(xlEdgeRight).color = 0
    Cells(6, 13).Borders(xlEdgeRight).weight = 2
    Cells(6, 14) = "ループ終了"
    Cells(6, 14).Font.Name = "游ゴシック"
    Cells(6, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 14).Borders(xlEdgeTop).color = 0
    Cells(6, 14).Borders(xlEdgeTop).weight = 2
    Cells(6, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 14).Borders(xlEdgeBottom).color = 0
    Cells(6, 14).Borders(xlEdgeBottom).weight = 2
    Cells(6, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 14).Borders(xlEdgeLeft).color = 0
    Cells(6, 14).Borders(xlEdgeLeft).weight = 2
    Cells(6, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 14).Borders(xlEdgeRight).color = 0
    Cells(6, 14).Borders(xlEdgeRight).weight = 2
    Cells(6, 15).Font.Name = "游ゴシック"
    Cells(6, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 15).Borders(xlEdgeTop).color = 0
    Cells(6, 15).Borders(xlEdgeTop).weight = 2
    Cells(6, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 15).Borders(xlEdgeBottom).color = 0
    Cells(6, 15).Borders(xlEdgeBottom).weight = 2
    Cells(6, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 15).Borders(xlEdgeLeft).color = 0
    Cells(6, 15).Borders(xlEdgeLeft).weight = 2
    Cells(6, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 15).Borders(xlEdgeRight).color = 0
    Cells(6, 15).Borders(xlEdgeRight).weight = 2
    Cells(7, 1) = "6"
    Cells(7, 1).Font.Name = "Meiryo UI"
    Cells(7, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeTop).color = 0
    Cells(7, 1).Borders(xlEdgeTop).weight = 2
    Cells(7, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeBottom).color = 0
    Cells(7, 1).Borders(xlEdgeBottom).weight = 2
    Cells(7, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeLeft).color = 0
    Cells(7, 1).Borders(xlEdgeLeft).weight = 2
    Cells(7, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeRight).color = 0
    Cells(7, 1).Borders(xlEdgeRight).weight = 2
end Function
Function revival2()
    Cells(7, 2) = "参照"
    Cells(7, 2).Font.Name = "Meiryo UI"
    Cells(7, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeTop).color = 0
    Cells(7, 2).Borders(xlEdgeTop).weight = 2
    Cells(7, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeBottom).color = 0
    Cells(7, 2).Borders(xlEdgeBottom).weight = 2
    Cells(7, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeLeft).color = 0
    Cells(7, 2).Borders(xlEdgeLeft).weight = 2
    Cells(7, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeRight).color = 0
    Cells(7, 2).Borders(xlEdgeRight).weight = 2
    Cells(7, 3) = "73"
    Cells(7, 3).Font.Name = "Meiryo UI"
    Cells(7, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeTop).color = 0
    Cells(7, 3).Borders(xlEdgeTop).weight = 2
    Cells(7, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeBottom).color = 0
    Cells(7, 3).Borders(xlEdgeBottom).weight = 2
    Cells(7, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeLeft).color = 0
    Cells(7, 3).Borders(xlEdgeLeft).weight = 2
    Cells(7, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeRight).color = 0
    Cells(7, 3).Borders(xlEdgeRight).weight = 2
    Cells(7, 4) = "5"
    Cells(7, 4).Font.Name = "Meiryo UI"
    Cells(7, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeTop).color = 0
    Cells(7, 4).Borders(xlEdgeTop).weight = 2
    Cells(7, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeBottom).color = 0
    Cells(7, 4).Borders(xlEdgeBottom).weight = 2
    Cells(7, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeLeft).color = 0
    Cells(7, 4).Borders(xlEdgeLeft).weight = 2
    Cells(7, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeRight).color = 0
    Cells(7, 4).Borders(xlEdgeRight).weight = 2
    Cells(7, 5) = "1"
    Cells(7, 5).Font.Name = "Meiryo UI"
    Cells(7, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeTop).color = 0
    Cells(7, 5).Borders(xlEdgeTop).weight = 2
    Cells(7, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeBottom).color = 0
    Cells(7, 5).Borders(xlEdgeBottom).weight = 2
    Cells(7, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeLeft).color = 0
    Cells(7, 5).Borders(xlEdgeLeft).weight = 2
    Cells(7, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeRight).color = 0
    Cells(7, 5).Borders(xlEdgeRight).weight = 2
    Cells(7, 6).Font.Name = "Meiryo UI"
    Cells(7, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeTop).color = 0
    Cells(7, 6).Borders(xlEdgeTop).weight = 2
    Cells(7, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeBottom).color = 0
    Cells(7, 6).Borders(xlEdgeBottom).weight = 2
    Cells(7, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeLeft).color = 0
    Cells(7, 6).Borders(xlEdgeLeft).weight = 2
    Cells(7, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeRight).color = 0
    Cells(7, 6).Borders(xlEdgeRight).weight = 2
    Cells(7, 7).Font.Name = "游ゴシック"
    Cells(7, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 7).Borders(xlEdgeLeft).color = 0
    Cells(7, 7).Borders(xlEdgeLeft).weight = 2
    Cells(7, 8).Font.Name = "游ゴシック"
    Cells(7, 9).Font.Name = "游ゴシック"
    Cells(7, 10).Font.Name = "游ゴシック"
    Cells(7, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 10).Borders(xlEdgeRight).color = 0
    Cells(7, 10).Borders(xlEdgeRight).weight = 2
    Cells(7, 11) = "4"
    Cells(7, 11).Font.Name = "游ゴシック"
    Cells(7, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 11).Borders(xlEdgeTop).color = 0
    Cells(7, 11).Borders(xlEdgeTop).weight = 2
    Cells(7, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 11).Borders(xlEdgeBottom).color = 0
    Cells(7, 11).Borders(xlEdgeBottom).weight = 2
    Cells(7, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 11).Borders(xlEdgeLeft).color = 0
    Cells(7, 11).Borders(xlEdgeLeft).weight = 2
    Cells(7, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 11).Borders(xlEdgeRight).color = 0
    Cells(7, 11).Borders(xlEdgeRight).weight = 2
    Cells(7, 12) = "6"
    Cells(7, 12).Font.Name = "游ゴシック"
    Cells(7, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 12).Borders(xlEdgeTop).color = 0
    Cells(7, 12).Borders(xlEdgeTop).weight = 2
    Cells(7, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 12).Borders(xlEdgeBottom).color = 0
    Cells(7, 12).Borders(xlEdgeBottom).weight = 2
    Cells(7, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 12).Borders(xlEdgeLeft).color = 0
    Cells(7, 12).Borders(xlEdgeLeft).weight = 2
    Cells(7, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 12).Borders(xlEdgeRight).color = 0
    Cells(7, 12).Borders(xlEdgeRight).weight = 2
    Cells(7, 13) = "7"
    Cells(7, 13).Font.Name = "游ゴシック"
    Cells(7, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 13).Borders(xlEdgeTop).color = 0
    Cells(7, 13).Borders(xlEdgeTop).weight = 2
    Cells(7, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 13).Borders(xlEdgeBottom).color = 0
    Cells(7, 13).Borders(xlEdgeBottom).weight = 2
    Cells(7, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 13).Borders(xlEdgeLeft).color = 0
    Cells(7, 13).Borders(xlEdgeLeft).weight = 2
    Cells(7, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 13).Borders(xlEdgeRight).color = 0
    Cells(7, 13).Borders(xlEdgeRight).weight = 2
    Cells(7, 14) = "ロジック"
    Cells(7, 14).Font.Name = "游ゴシック"
    Cells(7, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 14).Borders(xlEdgeTop).color = 0
    Cells(7, 14).Borders(xlEdgeTop).weight = 2
    Cells(7, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 14).Borders(xlEdgeBottom).color = 0
    Cells(7, 14).Borders(xlEdgeBottom).weight = 2
    Cells(7, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 14).Borders(xlEdgeLeft).color = 0
    Cells(7, 14).Borders(xlEdgeLeft).weight = 2
    Cells(7, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 14).Borders(xlEdgeRight).color = 0
    Cells(7, 14).Borders(xlEdgeRight).weight = 2
    Cells(7, 15) = "完成。食べよう！"
    Cells(7, 15).Font.Name = "游ゴシック"
    Cells(7, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 15).Borders(xlEdgeTop).color = 0
    Cells(7, 15).Borders(xlEdgeTop).weight = 2
    Cells(7, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 15).Borders(xlEdgeBottom).color = 0
    Cells(7, 15).Borders(xlEdgeBottom).weight = 2
    Cells(7, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 15).Borders(xlEdgeLeft).color = 0
    Cells(7, 15).Borders(xlEdgeLeft).weight = 2
    Cells(7, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 15).Borders(xlEdgeRight).color = 0
    Cells(7, 15).Borders(xlEdgeRight).weight = 2
    Cells(8, 1) = "7"
    Cells(8, 1).Font.Name = "Meiryo UI"
    Cells(8, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeTop).color = 0
    Cells(8, 1).Borders(xlEdgeTop).weight = 2
    Cells(8, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeBottom).color = 0
    Cells(8, 1).Borders(xlEdgeBottom).weight = 2
    Cells(8, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeLeft).color = 0
    Cells(8, 1).Borders(xlEdgeLeft).weight = 2
    Cells(8, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeRight).color = 0
    Cells(8, 1).Borders(xlEdgeRight).weight = 2
    Cells(8, 2) = "DBアクセス"
    Cells(8, 2).Font.Name = "Meiryo UI"
    Cells(8, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeTop).color = 0
    Cells(8, 2).Borders(xlEdgeTop).weight = 2
    Cells(8, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeBottom).color = 0
    Cells(8, 2).Borders(xlEdgeBottom).weight = 2
    Cells(8, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeLeft).color = 0
    Cells(8, 2).Borders(xlEdgeLeft).weight = 2
    Cells(8, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeRight).color = 0
    Cells(8, 2).Borders(xlEdgeRight).weight = 2
    Cells(8, 3) = "86"
    Cells(8, 3).Font.Name = "Meiryo UI"
    Cells(8, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeTop).color = 0
    Cells(8, 3).Borders(xlEdgeTop).weight = 2
    Cells(8, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeBottom).color = 0
    Cells(8, 3).Borders(xlEdgeBottom).weight = 2
    Cells(8, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeLeft).color = 0
    Cells(8, 3).Borders(xlEdgeLeft).weight = 2
    Cells(8, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeRight).color = 0
    Cells(8, 3).Borders(xlEdgeRight).weight = 2
    Cells(8, 4) = "4"
    Cells(8, 4).Font.Name = "Meiryo UI"
    Cells(8, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeTop).color = 0
    Cells(8, 4).Borders(xlEdgeTop).weight = 2
    Cells(8, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeBottom).color = 0
    Cells(8, 4).Borders(xlEdgeBottom).weight = 2
    Cells(8, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeLeft).color = 0
    Cells(8, 4).Borders(xlEdgeLeft).weight = 2
    Cells(8, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeRight).color = 0
    Cells(8, 4).Borders(xlEdgeRight).weight = 2
    Cells(8, 5) = "2"
    Cells(8, 5).Font.Name = "Meiryo UI"
    Cells(8, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeTop).color = 0
    Cells(8, 5).Borders(xlEdgeTop).weight = 2
    Cells(8, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeBottom).color = 0
    Cells(8, 5).Borders(xlEdgeBottom).weight = 2
    Cells(8, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeLeft).color = 0
    Cells(8, 5).Borders(xlEdgeLeft).weight = 2
    Cells(8, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeRight).color = 0
    Cells(8, 5).Borders(xlEdgeRight).weight = 2
    Cells(8, 6).Font.Name = "Meiryo UI"
    Cells(8, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeTop).color = 0
    Cells(8, 6).Borders(xlEdgeTop).weight = 2
    Cells(8, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeBottom).color = 0
    Cells(8, 6).Borders(xlEdgeBottom).weight = 2
    Cells(8, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeLeft).color = 0
    Cells(8, 6).Borders(xlEdgeLeft).weight = 2
    Cells(8, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeRight).color = 0
    Cells(8, 6).Borders(xlEdgeRight).weight = 2
    Cells(8, 7).Font.Name = "游ゴシック"
    Cells(8, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 7).Borders(xlEdgeLeft).color = 0
    Cells(8, 7).Borders(xlEdgeLeft).weight = 2
    Cells(8, 8).Font.Name = "游ゴシック"
    Cells(8, 9).Font.Name = "游ゴシック"
    Cells(8, 10).Font.Name = "游ゴシック"
    Cells(8, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 10).Borders(xlEdgeRight).color = 0
    Cells(8, 10).Borders(xlEdgeRight).weight = 2
    Cells(8, 11).Font.Name = "游ゴシック"
    Cells(8, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 11).Borders(xlEdgeTop).color = 0
    Cells(8, 11).Borders(xlEdgeTop).weight = 2
    Cells(8, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 11).Borders(xlEdgeBottom).color = 0
    Cells(8, 11).Borders(xlEdgeBottom).weight = 2
    Cells(8, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 11).Borders(xlEdgeLeft).color = 0
    Cells(8, 11).Borders(xlEdgeLeft).weight = 2
    Cells(8, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 11).Borders(xlEdgeRight).color = 0
    Cells(8, 11).Borders(xlEdgeRight).weight = 2
    Cells(8, 12) = "7"
    Cells(8, 12).Font.Name = "游ゴシック"
    Cells(8, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 12).Borders(xlEdgeTop).color = 0
    Cells(8, 12).Borders(xlEdgeTop).weight = 2
    Cells(8, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 12).Borders(xlEdgeBottom).color = 0
    Cells(8, 12).Borders(xlEdgeBottom).weight = 2
    Cells(8, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 12).Borders(xlEdgeLeft).color = 0
    Cells(8, 12).Borders(xlEdgeLeft).weight = 2
    Cells(8, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 12).Borders(xlEdgeRight).color = 0
    Cells(8, 12).Borders(xlEdgeRight).weight = 2
    Cells(8, 13).Font.Name = "游ゴシック"
    Cells(8, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 13).Borders(xlEdgeTop).color = 0
    Cells(8, 13).Borders(xlEdgeTop).weight = 2
    Cells(8, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 13).Borders(xlEdgeBottom).color = 0
    Cells(8, 13).Borders(xlEdgeBottom).weight = 2
    Cells(8, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 13).Borders(xlEdgeLeft).color = 0
    Cells(8, 13).Borders(xlEdgeLeft).weight = 2
    Cells(8, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 13).Borders(xlEdgeRight).color = 0
    Cells(8, 13).Borders(xlEdgeRight).weight = 2
    Cells(8, 14) = "終了"
    Cells(8, 14).Font.Name = "游ゴシック"
    Cells(8, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 14).Borders(xlEdgeTop).color = 0
    Cells(8, 14).Borders(xlEdgeTop).weight = 2
    Cells(8, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 14).Borders(xlEdgeBottom).color = 0
    Cells(8, 14).Borders(xlEdgeBottom).weight = 2
    Cells(8, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 14).Borders(xlEdgeLeft).color = 0
    Cells(8, 14).Borders(xlEdgeLeft).weight = 2
    Cells(8, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 14).Borders(xlEdgeRight).color = 0
    Cells(8, 14).Borders(xlEdgeRight).weight = 2
    Cells(8, 15) = "終了"
    Cells(8, 15).Font.Name = "游ゴシック"
    Cells(8, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 15).Borders(xlEdgeTop).color = 0
    Cells(8, 15).Borders(xlEdgeTop).weight = 2
    Cells(8, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 15).Borders(xlEdgeBottom).color = 0
    Cells(8, 15).Borders(xlEdgeBottom).weight = 2
    Cells(8, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 15).Borders(xlEdgeLeft).color = 0
    Cells(8, 15).Borders(xlEdgeLeft).weight = 2
    Cells(8, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 15).Borders(xlEdgeRight).color = 0
    Cells(8, 15).Borders(xlEdgeRight).weight = 2
    Cells(9, 1) = "8"
    Cells(9, 1).Font.Name = "Meiryo UI"
    Cells(9, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeTop).color = 0
    Cells(9, 1).Borders(xlEdgeTop).weight = 2
    Cells(9, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeBottom).color = 0
    Cells(9, 1).Borders(xlEdgeBottom).weight = 2
    Cells(9, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeLeft).color = 0
    Cells(9, 1).Borders(xlEdgeLeft).weight = 2
    Cells(9, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeRight).color = 0
    Cells(9, 1).Borders(xlEdgeRight).weight = 2
end Function
Function revival3()
    Cells(9, 2) = "ループ開始/ループ終了"
    Cells(9, 2).Font.Name = "Meiryo UI"
    Cells(9, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeTop).color = 0
    Cells(9, 2).Borders(xlEdgeTop).weight = 2
    Cells(9, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeBottom).color = 0
    Cells(9, 2).Borders(xlEdgeBottom).weight = 2
    Cells(9, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeLeft).color = 0
    Cells(9, 2).Borders(xlEdgeLeft).weight = 2
    Cells(9, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeRight).color = 0
    Cells(9, 2).Borders(xlEdgeRight).weight = 2
    Cells(9, 3) = "156"
    Cells(9, 3).Font.Name = "Meiryo UI"
    Cells(9, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeTop).color = 0
    Cells(9, 3).Borders(xlEdgeTop).weight = 2
    Cells(9, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeBottom).color = 0
    Cells(9, 3).Borders(xlEdgeBottom).weight = 2
    Cells(9, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeLeft).color = 0
    Cells(9, 3).Borders(xlEdgeLeft).weight = 2
    Cells(9, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeRight).color = 0
    Cells(9, 3).Borders(xlEdgeRight).weight = 2
    Cells(9, 4) = "2"
    Cells(9, 4).Font.Name = "Meiryo UI"
    Cells(9, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeTop).color = 0
    Cells(9, 4).Borders(xlEdgeTop).weight = 2
    Cells(9, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeBottom).color = 0
    Cells(9, 4).Borders(xlEdgeBottom).weight = 2
    Cells(9, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeLeft).color = 0
    Cells(9, 4).Borders(xlEdgeLeft).weight = 2
    Cells(9, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeRight).color = 0
    Cells(9, 4).Borders(xlEdgeRight).weight = 2
    Cells(9, 5) = "4"
    Cells(9, 5).Font.Name = "Meiryo UI"
    Cells(9, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeTop).color = 0
    Cells(9, 5).Borders(xlEdgeTop).weight = 2
    Cells(9, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeBottom).color = 0
    Cells(9, 5).Borders(xlEdgeBottom).weight = 2
    Cells(9, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeLeft).color = 0
    Cells(9, 5).Borders(xlEdgeLeft).weight = 2
    Cells(9, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeRight).color = 0
    Cells(9, 5).Borders(xlEdgeRight).weight = 2
    Cells(9, 6).Font.Name = "Meiryo UI"
    Cells(9, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeTop).color = 0
    Cells(9, 6).Borders(xlEdgeTop).weight = 2
    Cells(9, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeBottom).color = 0
    Cells(9, 6).Borders(xlEdgeBottom).weight = 2
    Cells(9, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeLeft).color = 0
    Cells(9, 6).Borders(xlEdgeLeft).weight = 2
    Cells(9, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeRight).color = 0
    Cells(9, 6).Borders(xlEdgeRight).weight = 2
    Cells(9, 7).Font.Name = "游ゴシック"
    Cells(9, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 7).Borders(xlEdgeLeft).color = 0
    Cells(9, 7).Borders(xlEdgeLeft).weight = 2
    Cells(9, 8).Font.Name = "游ゴシック"
    Cells(9, 9).Font.Name = "游ゴシック"
    Cells(9, 10).Font.Name = "游ゴシック"
    Cells(9, 11).Font.Name = "游ゴシック"
    Cells(9, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 11).Borders(xlEdgeTop).color = 0
    Cells(9, 11).Borders(xlEdgeTop).weight = 2
    Cells(9, 12).Font.Name = "游ゴシック"
    Cells(9, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 12).Borders(xlEdgeTop).color = 0
    Cells(9, 12).Borders(xlEdgeTop).weight = 2
    Cells(9, 13).Font.Name = "游ゴシック"
    Cells(9, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 13).Borders(xlEdgeTop).color = 0
    Cells(9, 13).Borders(xlEdgeTop).weight = 2
    Cells(9, 14).Font.Name = "游ゴシック"
    Cells(9, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 14).Borders(xlEdgeTop).color = 0
    Cells(9, 14).Borders(xlEdgeTop).weight = 2
    Cells(9, 15).Font.Name = "游ゴシック"
    Cells(9, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 15).Borders(xlEdgeTop).color = 0
    Cells(9, 15).Borders(xlEdgeTop).weight = 2
    Cells(10, 1).Font.Name = "游ゴシック"
    Cells(10, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 1).Borders(xlEdgeTop).color = 0
    Cells(10, 1).Borders(xlEdgeTop).weight = 2
    Cells(10, 2) = "https://learn.microsoft.com/ja-jp/office/vba/api/office.msoautoshapetype?source=recommendations"
    Cells(10, 2).Font.Name = "游ゴシック"
    Cells(10, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 2).Borders(xlEdgeTop).color = 0
    Cells(10, 2).Borders(xlEdgeTop).weight = 2
    Cells(10, 3).Font.Name = "游ゴシック"
    Cells(10, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeTop).color = 0
    Cells(10, 3).Borders(xlEdgeTop).weight = 2
    Cells(10, 4).Font.Name = "游ゴシック"
    Cells(10, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeTop).color = 0
    Cells(10, 4).Borders(xlEdgeTop).weight = 2
    Cells(10, 5).Font.Name = "游ゴシック"
    Cells(10, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeTop).color = 0
    Cells(10, 5).Borders(xlEdgeTop).weight = 2
    Cells(10, 6).Font.Name = "游ゴシック"
    Cells(10, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeTop).color = 0
    Cells(10, 6).Borders(xlEdgeTop).weight = 2
    Cells(10, 7).Font.Name = "游ゴシック"
    Cells(10, 8).Font.Name = "游ゴシック"
    Cells(10, 9).Font.Name = "游ゴシック"
    Cells(10, 10).Font.Name = "游ゴシック"
    Cells(10, 11).Font.Name = "游ゴシック"
    Cells(10, 12).Font.Name = "游ゴシック"
    Cells(10, 13).Font.Name = "游ゴシック"
    Cells(10, 14).Font.Name = "游ゴシック"
    Cells(10, 15).Font.Name = "游ゴシック"
    Rows(1).RowHeight = 18.75
    Rows(2).RowHeight = 32.25
    Rows(3).RowHeight = 32.25
    Rows(4).RowHeight = 32.25
    Rows(5).RowHeight = 32.25
    Rows(6).RowHeight = 32.25
    Rows(7).RowHeight = 32.25
    Rows(8).RowHeight = 32.25
    Rows(9).RowHeight = 32.25
    Rows(10).RowHeight = 32.25
    Columns(1).ColumnWidth = 4.88
    Columns(2).ColumnWidth = 33.75
    Columns(3).ColumnWidth = 6.13
    Columns(4).ColumnWidth = 8.63
    Columns(5).ColumnWidth = 8.63
    Columns(6).ColumnWidth = 8.38
    Columns(7).ColumnWidth = 8.38
    Columns(8).ColumnWidth = 8.38
    Columns(9).ColumnWidth = 8.38
    Columns(10).ColumnWidth = 8.38
    Columns(11).ColumnWidth = 8.38
    Columns(12).ColumnWidth = 8.38
    Columns(13).ColumnWidth = 8.38
    Columns(14).ColumnWidth = 8.38
    Columns(15).ColumnWidth = 8.38
    Dim onShape As Object
    Set onShape = ActiveSheet.Shapes.AddShape(61,395.75,24.63228,44,22.25)
    onShape.Name = "Flowchart: Process 1"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(63,395.7502,56.00008,44,22.25)
    onShape.Name = "Flowchart: Decision 2"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(64,394.8676,88.25008,44,22.25)
    onShape.Name = "Flowchart: Data 3"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(65,395.7498,121.3824,44,22.25)
    onShape.Name = "Flowchart: Predefined Process 4"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(69,395.75,152.75,44,22.25)
    onShape.Name = "Flowchart: Terminator 5"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(73,405.456,185.8824,25,22.25)
    onShape.Name = "Flowchart: Connector 6"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(86,395.75,217.25,44,22.25)
    onShape.Name = "Flowchart: Magnetic Disk 7"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(156,395.75,249.5,44,22.25)
    onShape.Name = "Snip Same Side Corner Rectangle 8"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
End Function
sub revival()
    CALL revival0()
    CALL revival1()
    CALL revival2()
    CALL revival3()
end sub