Attribute VB_Name = "setup"
Function revival0()
    ActiveWindow.DisplayGridlines = False
    ActiveWindow.Zoom = 100
    ActiveSheet.Name = "シェイプ一覧"
    Cells(1, 1) = "No"
    Cells(1, 1).Font.Name = "游ゴシック"
    Cells(1, 1).Interior.Color = 13431551
    Cells(1, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeTop).color = 0
    Cells(1, 1).Borders(xlEdgeTop).weight = 1
    Cells(1, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeBottom).color = 0
    Cells(1, 1).Borders(xlEdgeBottom).weight = 1
    Cells(1, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeLeft).color = 0
    Cells(1, 1).Borders(xlEdgeLeft).weight = 1
    Cells(1, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeRight).color = 0
    Cells(1, 1).Borders(xlEdgeRight).weight = 1
    Cells(1, 2) = "種別"
    Cells(1, 2).Font.Name = "游ゴシック"
    Cells(1, 2).Interior.Color = 13431551
    Cells(1, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeTop).color = 0
    Cells(1, 2).Borders(xlEdgeTop).weight = 1
    Cells(1, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeBottom).color = 0
    Cells(1, 2).Borders(xlEdgeBottom).weight = 1
    Cells(1, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeLeft).color = 0
    Cells(1, 2).Borders(xlEdgeLeft).weight = 1
    Cells(1, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeRight).color = 0
    Cells(1, 2).Borders(xlEdgeRight).weight = 1
    Cells(1, 3) = "名前"
    Cells(1, 3).Font.Name = "游ゴシック"
    Cells(1, 3).Interior.Color = 13431551
    Cells(1, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeTop).color = 0
    Cells(1, 3).Borders(xlEdgeTop).weight = 1
    Cells(1, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeBottom).color = 0
    Cells(1, 3).Borders(xlEdgeBottom).weight = 1
    Cells(1, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeLeft).color = 0
    Cells(1, 3).Borders(xlEdgeLeft).weight = 1
    Cells(1, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeRight).color = 0
    Cells(1, 3).Borders(xlEdgeRight).weight = 1
    Cells(1, 4) = "値"
    Cells(1, 4).Font.Name = "游ゴシック"
    Cells(1, 4).Interior.Color = 13431551
    Cells(1, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeTop).color = 0
    Cells(1, 4).Borders(xlEdgeTop).weight = 1
    Cells(1, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeBottom).color = 0
    Cells(1, 4).Borders(xlEdgeBottom).weight = 1
    Cells(1, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeLeft).color = 0
    Cells(1, 4).Borders(xlEdgeLeft).weight = 1
    Cells(1, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeRight).color = 0
    Cells(1, 4).Borders(xlEdgeRight).weight = 1
    Cells(1, 5) = "始点"
    Cells(1, 5).Font.Name = "游ゴシック"
    Cells(1, 5).Interior.Color = 13431551
    Cells(1, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeTop).color = 0
    Cells(1, 5).Borders(xlEdgeTop).weight = 1
    Cells(1, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeBottom).color = 0
    Cells(1, 5).Borders(xlEdgeBottom).weight = 1
    Cells(1, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeLeft).color = 0
    Cells(1, 5).Borders(xlEdgeLeft).weight = 1
    Cells(1, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeRight).color = 0
    Cells(1, 5).Borders(xlEdgeRight).weight = 1
    Cells(1, 6) = "終点"
    Cells(1, 6).Font.Name = "游ゴシック"
    Cells(1, 6).Interior.Color = 13431551
    Cells(1, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeTop).color = 0
    Cells(1, 6).Borders(xlEdgeTop).weight = 1
    Cells(1, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeBottom).color = 0
    Cells(1, 6).Borders(xlEdgeBottom).weight = 1
    Cells(1, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeLeft).color = 0
    Cells(1, 6).Borders(xlEdgeLeft).weight = 1
    Cells(1, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeRight).color = 0
    Cells(1, 6).Borders(xlEdgeRight).weight = 1
    Cells(1, 7) = "説明"
    Cells(1, 7).Font.Name = "游ゴシック"
    Cells(1, 7).Interior.Color = 13431551
    Cells(1, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 7).Borders(xlEdgeTop).color = 0
    Cells(1, 7).Borders(xlEdgeTop).weight = 1
    Cells(1, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 7).Borders(xlEdgeBottom).color = 0
    Cells(1, 7).Borders(xlEdgeBottom).weight = 1
    Cells(1, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 7).Borders(xlEdgeLeft).color = 0
    Cells(1, 7).Borders(xlEdgeLeft).weight = 1
    Cells(1, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 7).Borders(xlEdgeRight).color = 0
    Cells(1, 7).Borders(xlEdgeRight).weight = 1
    Cells(1, 8) = "形"
    Cells(1, 8).Font.Name = "游ゴシック"
    Cells(1, 8).Interior.Color = 13431551
    Cells(1, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 8).Borders(xlEdgeTop).color = 0
    Cells(1, 8).Borders(xlEdgeTop).weight = 1
    Cells(1, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 8).Borders(xlEdgeBottom).color = 0
    Cells(1, 8).Borders(xlEdgeBottom).weight = 1
    Cells(1, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 8).Borders(xlEdgeLeft).color = 0
    Cells(1, 8).Borders(xlEdgeLeft).weight = 1
    Cells(1, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 8).Borders(xlEdgeRight).color = 0
    Cells(1, 8).Borders(xlEdgeRight).weight = 1
    Cells(1, 9) = "フローで使いそう"
    Cells(1, 9).Font.Name = "游ゴシック"
    Cells(1, 9).Interior.Color = 13431551
    Cells(1, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 9).Borders(xlEdgeLeft).color = 0
    Cells(1, 9).Borders(xlEdgeLeft).weight = 1
    Cells(1, 9).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 9).Borders(xlEdgeRight).color = 0
    Cells(1, 9).Borders(xlEdgeRight).weight = 1
    Cells(1, 10).Font.Name = "游ゴシック"
    Cells(1, 10).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 10).Borders(xlEdgeLeft).color = 0
    Cells(1, 10).Borders(xlEdgeLeft).weight = 1
    Cells(1, 11).Font.Name = "游ゴシック"
    Cells(1, 12).Font.Name = "游ゴシック"
    Cells(1, 13).Font.Name = "游ゴシック"
    Cells(1, 14).Font.Name = "游ゴシック"
    Cells(1, 15).Font.Name = "游ゴシック"
    Cells(1, 16).Font.Name = "游ゴシック"
    Cells(1, 17).Font.Name = "游ゴシック"
    Cells(1, 18).Font.Name = "游ゴシック"
    Cells(2, 1) = "1"
    Cells(2, 1).Font.Name = "游ゴシック"
    Cells(2, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeTop).color = 0
    Cells(2, 1).Borders(xlEdgeTop).weight = 1
    Cells(2, 2) = "ロジック"
    Cells(2, 2).Font.Name = "游ゴシック"
    Cells(2, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeTop).color = 0
    Cells(2, 2).Borders(xlEdgeTop).weight = 1
    Cells(2, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeRight).color = 0
    Cells(2, 2).Borders(xlEdgeRight).weight = 1
    Cells(2, 3) = "msoShapeFlowchartProcess"
    Cells(2, 3).Font.Name = "游ゴシック"
    Cells(2, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeTop).color = 0
    Cells(2, 3).Borders(xlEdgeTop).weight = 1
    Cells(2, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeBottom).color = 0
    Cells(2, 3).Borders(xlEdgeBottom).weight = 1
    Cells(2, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeLeft).color = 0
    Cells(2, 3).Borders(xlEdgeLeft).weight = 1
    Cells(2, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeRight).color = 0
    Cells(2, 3).Borders(xlEdgeRight).weight = 1
    Cells(2, 4) = "61"
    Cells(2, 4).Font.Name = "游ゴシック"
    Cells(2, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeTop).color = 0
    Cells(2, 4).Borders(xlEdgeTop).weight = 1
    Cells(2, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeBottom).color = 0
    Cells(2, 4).Borders(xlEdgeBottom).weight = 1
    Cells(2, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeLeft).color = 0
    Cells(2, 4).Borders(xlEdgeLeft).weight = 1
    Cells(2, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeRight).color = 0
    Cells(2, 4).Borders(xlEdgeRight).weight = 1
    Cells(2, 5) = "3"
    Cells(2, 5).Font.Name = "游ゴシック"
    Cells(2, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeTop).color = 0
    Cells(2, 5).Borders(xlEdgeTop).weight = 1
    Cells(2, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeBottom).color = 0
    Cells(2, 5).Borders(xlEdgeBottom).weight = 1
    Cells(2, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeLeft).color = 0
    Cells(2, 5).Borders(xlEdgeLeft).weight = 1
    Cells(2, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeRight).color = 0
    Cells(2, 5).Borders(xlEdgeRight).weight = 1
    Cells(2, 6) = "1"
    Cells(2, 6).Font.Name = "游ゴシック"
    Cells(2, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeTop).color = 0
    Cells(2, 6).Borders(xlEdgeTop).weight = 1
    Cells(2, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeBottom).color = 0
    Cells(2, 6).Borders(xlEdgeBottom).weight = 1
    Cells(2, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeLeft).color = 0
    Cells(2, 6).Borders(xlEdgeLeft).weight = 1
    Cells(2, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeRight).color = 0
    Cells(2, 6).Borders(xlEdgeRight).weight = 1
    Cells(2, 7) = "プロセスフローチャートの記号"
    Cells(2, 7).Font.Name = "游ゴシック"
    Cells(2, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 7).Borders(xlEdgeTop).color = 0
    Cells(2, 7).Borders(xlEdgeTop).weight = 1
    Cells(2, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 7).Borders(xlEdgeBottom).color = 0
    Cells(2, 7).Borders(xlEdgeBottom).weight = 1
    Cells(2, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 7).Borders(xlEdgeLeft).color = 0
    Cells(2, 7).Borders(xlEdgeLeft).weight = 1
    Cells(2, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 7).Borders(xlEdgeRight).color = 0
    Cells(2, 7).Borders(xlEdgeRight).weight = 1
    Cells(2, 8).Font.Name = "游ゴシック"
    Cells(2, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 8).Borders(xlEdgeTop).color = 0
    Cells(2, 8).Borders(xlEdgeTop).weight = 1
    Cells(2, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 8).Borders(xlEdgeBottom).color = 0
    Cells(2, 8).Borders(xlEdgeBottom).weight = 1
    Cells(2, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 8).Borders(xlEdgeLeft).color = 0
    Cells(2, 8).Borders(xlEdgeLeft).weight = 1
    Cells(2, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 8).Borders(xlEdgeRight).color = 0
    Cells(2, 8).Borders(xlEdgeRight).weight = 1
    Cells(2, 9) = "〇"
    Cells(2, 9).Font.Name = "游ゴシック"
    Cells(2, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 9).Borders(xlEdgeLeft).color = 0
    Cells(2, 9).Borders(xlEdgeLeft).weight = 1
    Cells(2, 10).Font.Name = "游ゴシック"
    Cells(2, 11).Font.Name = "游ゴシック"
    Cells(2, 12).Font.Name = "游ゴシック"
    Cells(2, 13).Font.Name = "游ゴシック"
    Cells(2, 14).Font.Name = "游ゴシック"
    Cells(2, 15).Font.Name = "游ゴシック"
    Cells(2, 16).Font.Name = "游ゴシック"
    Cells(2, 17).Font.Name = "游ゴシック"
    Cells(2, 18).Font.Name = "游ゴシック"
    Cells(3, 1) = "2"
    Cells(3, 1).Font.Name = "游ゴシック"
    Cells(3, 2) = "分岐/Switch"
    Cells(3, 2).Font.Name = "游ゴシック"
    Cells(3, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeRight).color = 0
    Cells(3, 2).Borders(xlEdgeRight).weight = 1
    Cells(3, 3) = "msoShapeFlowchartDecision"
    Cells(3, 3).Font.Name = "游ゴシック"
    Cells(3, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeTop).color = 0
    Cells(3, 3).Borders(xlEdgeTop).weight = 1
    Cells(3, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeBottom).color = 0
    Cells(3, 3).Borders(xlEdgeBottom).weight = 1
    Cells(3, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeLeft).color = 0
    Cells(3, 3).Borders(xlEdgeLeft).weight = 1
    Cells(3, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeRight).color = 0
    Cells(3, 3).Borders(xlEdgeRight).weight = 1
    Cells(3, 4) = "63"
    Cells(3, 4).Font.Name = "游ゴシック"
    Cells(3, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeTop).color = 0
    Cells(3, 4).Borders(xlEdgeTop).weight = 1
    Cells(3, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeBottom).color = 0
    Cells(3, 4).Borders(xlEdgeBottom).weight = 1
    Cells(3, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeLeft).color = 0
    Cells(3, 4).Borders(xlEdgeLeft).weight = 1
    Cells(3, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeRight).color = 0
    Cells(3, 4).Borders(xlEdgeRight).weight = 1
    Cells(3, 5) = "3"
    Cells(3, 5).Font.Name = "游ゴシック"
    Cells(3, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeTop).color = 0
    Cells(3, 5).Borders(xlEdgeTop).weight = 1
    Cells(3, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeBottom).color = 0
    Cells(3, 5).Borders(xlEdgeBottom).weight = 1
    Cells(3, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeLeft).color = 0
    Cells(3, 5).Borders(xlEdgeLeft).weight = 1
    Cells(3, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeRight).color = 0
    Cells(3, 5).Borders(xlEdgeRight).weight = 1
    Cells(3, 6) = "1"
    Cells(3, 6).Font.Name = "游ゴシック"
    Cells(3, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeTop).color = 0
    Cells(3, 6).Borders(xlEdgeTop).weight = 1
    Cells(3, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeBottom).color = 0
    Cells(3, 6).Borders(xlEdgeBottom).weight = 1
    Cells(3, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeLeft).color = 0
    Cells(3, 6).Borders(xlEdgeLeft).weight = 1
    Cells(3, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeRight).color = 0
    Cells(3, 6).Borders(xlEdgeRight).weight = 1
    Cells(3, 7) = "決定フローチャートの記号"
    Cells(3, 7).Font.Name = "游ゴシック"
    Cells(3, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 7).Borders(xlEdgeTop).color = 0
    Cells(3, 7).Borders(xlEdgeTop).weight = 1
    Cells(3, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 7).Borders(xlEdgeBottom).color = 0
    Cells(3, 7).Borders(xlEdgeBottom).weight = 1
    Cells(3, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 7).Borders(xlEdgeLeft).color = 0
    Cells(3, 7).Borders(xlEdgeLeft).weight = 1
    Cells(3, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 7).Borders(xlEdgeRight).color = 0
    Cells(3, 7).Borders(xlEdgeRight).weight = 1
    Cells(3, 8).Font.Name = "游ゴシック"
    Cells(3, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 8).Borders(xlEdgeTop).color = 0
    Cells(3, 8).Borders(xlEdgeTop).weight = 1
    Cells(3, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 8).Borders(xlEdgeBottom).color = 0
    Cells(3, 8).Borders(xlEdgeBottom).weight = 1
    Cells(3, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 8).Borders(xlEdgeLeft).color = 0
    Cells(3, 8).Borders(xlEdgeLeft).weight = 1
    Cells(3, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 8).Borders(xlEdgeRight).color = 0
    Cells(3, 8).Borders(xlEdgeRight).weight = 1
    Cells(3, 9) = "〇"
    Cells(3, 9).Font.Name = "游ゴシック"
    Cells(3, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 9).Borders(xlEdgeLeft).color = 0
    Cells(3, 9).Borders(xlEdgeLeft).weight = 1
    Cells(3, 10).Font.Name = "游ゴシック"
    Cells(3, 11).Font.Name = "游ゴシック"
    Cells(3, 12).Font.Name = "游ゴシック"
    Cells(3, 13).Font.Name = "游ゴシック"
    Cells(3, 14).Font.Name = "游ゴシック"
    Cells(3, 15).Font.Name = "游ゴシック"
    Cells(3, 16).Font.Name = "游ゴシック"
    Cells(3, 17).Font.Name = "游ゴシック"
    Cells(3, 18).Font.Name = "游ゴシック"
    Cells(4, 1) = "3"
    Cells(4, 1).Font.Name = "游ゴシック"
    Cells(4, 2) = "入力/出力"
    Cells(4, 2).Font.Name = "游ゴシック"
    Cells(4, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeRight).color = 0
    Cells(4, 2).Borders(xlEdgeRight).weight = 1
    Cells(4, 3) = "msoShapeFlowchartData"
    Cells(4, 3).Font.Name = "游ゴシック"
    Cells(4, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeTop).color = 0
    Cells(4, 3).Borders(xlEdgeTop).weight = 1
    Cells(4, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeBottom).color = 0
    Cells(4, 3).Borders(xlEdgeBottom).weight = 1
    Cells(4, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeLeft).color = 0
    Cells(4, 3).Borders(xlEdgeLeft).weight = 1
    Cells(4, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeRight).color = 0
    Cells(4, 3).Borders(xlEdgeRight).weight = 1
    Cells(4, 4) = "64"
    Cells(4, 4).Font.Name = "游ゴシック"
    Cells(4, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeTop).color = 0
    Cells(4, 4).Borders(xlEdgeTop).weight = 1
    Cells(4, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeBottom).color = 0
    Cells(4, 4).Borders(xlEdgeBottom).weight = 1
    Cells(4, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeLeft).color = 0
    Cells(4, 4).Borders(xlEdgeLeft).weight = 1
    Cells(4, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeRight).color = 0
    Cells(4, 4).Borders(xlEdgeRight).weight = 1
    Cells(4, 5) = "5"
    Cells(4, 5).Font.Name = "游ゴシック"
    Cells(4, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeTop).color = 0
    Cells(4, 5).Borders(xlEdgeTop).weight = 1
    Cells(4, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeBottom).color = 0
    Cells(4, 5).Borders(xlEdgeBottom).weight = 1
    Cells(4, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeLeft).color = 0
    Cells(4, 5).Borders(xlEdgeLeft).weight = 1
    Cells(4, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeRight).color = 0
    Cells(4, 5).Borders(xlEdgeRight).weight = 1
    Cells(4, 6) = "2"
    Cells(4, 6).Font.Name = "游ゴシック"
    Cells(4, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeTop).color = 0
    Cells(4, 6).Borders(xlEdgeTop).weight = 1
    Cells(4, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeBottom).color = 0
    Cells(4, 6).Borders(xlEdgeBottom).weight = 1
    Cells(4, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeLeft).color = 0
    Cells(4, 6).Borders(xlEdgeLeft).weight = 1
    Cells(4, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeRight).color = 0
    Cells(4, 6).Borders(xlEdgeRight).weight = 1
    Cells(4, 7) = "データ フローチャートの記号"
    Cells(4, 7).Font.Name = "游ゴシック"
    Cells(4, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 7).Borders(xlEdgeTop).color = 0
    Cells(4, 7).Borders(xlEdgeTop).weight = 1
    Cells(4, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 7).Borders(xlEdgeBottom).color = 0
    Cells(4, 7).Borders(xlEdgeBottom).weight = 1
    Cells(4, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 7).Borders(xlEdgeLeft).color = 0
    Cells(4, 7).Borders(xlEdgeLeft).weight = 1
    Cells(4, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 7).Borders(xlEdgeRight).color = 0
    Cells(4, 7).Borders(xlEdgeRight).weight = 1
end Function
Function revival1()
    Cells(4, 8).Font.Name = "游ゴシック"
    Cells(4, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 8).Borders(xlEdgeTop).color = 0
    Cells(4, 8).Borders(xlEdgeTop).weight = 1
    Cells(4, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 8).Borders(xlEdgeBottom).color = 0
    Cells(4, 8).Borders(xlEdgeBottom).weight = 1
    Cells(4, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 8).Borders(xlEdgeLeft).color = 0
    Cells(4, 8).Borders(xlEdgeLeft).weight = 1
    Cells(4, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 8).Borders(xlEdgeRight).color = 0
    Cells(4, 8).Borders(xlEdgeRight).weight = 1
    Cells(4, 9) = "〇"
    Cells(4, 9).Font.Name = "游ゴシック"
    Cells(4, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 9).Borders(xlEdgeLeft).color = 0
    Cells(4, 9).Borders(xlEdgeLeft).weight = 1
    Cells(4, 10).Font.Name = "游ゴシック"
    Cells(4, 11).Font.Name = "游ゴシック"
    Cells(4, 12).Font.Name = "游ゴシック"
    Cells(4, 13).Font.Name = "游ゴシック"
    Cells(4, 14).Font.Name = "游ゴシック"
    Cells(4, 15).Font.Name = "游ゴシック"
    Cells(4, 16).Font.Name = "游ゴシック"
    Cells(4, 17).Font.Name = "游ゴシック"
    Cells(4, 18).Font.Name = "游ゴシック"
    Cells(5, 1) = "4"
    Cells(5, 1).Font.Name = "游ゴシック"
    Cells(5, 2) = "サブルーチン"
    Cells(5, 2).Font.Name = "游ゴシック"
    Cells(5, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeRight).color = 0
    Cells(5, 2).Borders(xlEdgeRight).weight = 1
    Cells(5, 3) = "msoShapeFlowchartPredefinedProcess"
    Cells(5, 3).Font.Name = "游ゴシック"
    Cells(5, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeTop).color = 0
    Cells(5, 3).Borders(xlEdgeTop).weight = 1
    Cells(5, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeBottom).color = 0
    Cells(5, 3).Borders(xlEdgeBottom).weight = 1
    Cells(5, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeLeft).color = 0
    Cells(5, 3).Borders(xlEdgeLeft).weight = 1
    Cells(5, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeRight).color = 0
    Cells(5, 3).Borders(xlEdgeRight).weight = 1
    Cells(5, 4) = "65"
    Cells(5, 4).Font.Name = "游ゴシック"
    Cells(5, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeTop).color = 0
    Cells(5, 4).Borders(xlEdgeTop).weight = 1
    Cells(5, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeBottom).color = 0
    Cells(5, 4).Borders(xlEdgeBottom).weight = 1
    Cells(5, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeLeft).color = 0
    Cells(5, 4).Borders(xlEdgeLeft).weight = 1
    Cells(5, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeRight).color = 0
    Cells(5, 4).Borders(xlEdgeRight).weight = 1
    Cells(5, 5) = "3"
    Cells(5, 5).Font.Name = "游ゴシック"
    Cells(5, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeTop).color = 0
    Cells(5, 5).Borders(xlEdgeTop).weight = 1
    Cells(5, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeBottom).color = 0
    Cells(5, 5).Borders(xlEdgeBottom).weight = 1
    Cells(5, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeLeft).color = 0
    Cells(5, 5).Borders(xlEdgeLeft).weight = 1
    Cells(5, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeRight).color = 0
    Cells(5, 5).Borders(xlEdgeRight).weight = 1
    Cells(5, 6) = "1"
    Cells(5, 6).Font.Name = "游ゴシック"
    Cells(5, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeTop).color = 0
    Cells(5, 6).Borders(xlEdgeTop).weight = 1
    Cells(5, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeBottom).color = 0
    Cells(5, 6).Borders(xlEdgeBottom).weight = 1
    Cells(5, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeLeft).color = 0
    Cells(5, 6).Borders(xlEdgeLeft).weight = 1
    Cells(5, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeRight).color = 0
    Cells(5, 6).Borders(xlEdgeRight).weight = 1
    Cells(5, 7) = "定義済みのプロセスフローチャート記号"
    Cells(5, 7).Font.Name = "游ゴシック"
    Cells(5, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 7).Borders(xlEdgeTop).color = 0
    Cells(5, 7).Borders(xlEdgeTop).weight = 1
    Cells(5, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 7).Borders(xlEdgeBottom).color = 0
    Cells(5, 7).Borders(xlEdgeBottom).weight = 1
    Cells(5, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 7).Borders(xlEdgeLeft).color = 0
    Cells(5, 7).Borders(xlEdgeLeft).weight = 1
    Cells(5, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 7).Borders(xlEdgeRight).color = 0
    Cells(5, 7).Borders(xlEdgeRight).weight = 1
    Cells(5, 8).Font.Name = "游ゴシック"
    Cells(5, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 8).Borders(xlEdgeTop).color = 0
    Cells(5, 8).Borders(xlEdgeTop).weight = 1
    Cells(5, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 8).Borders(xlEdgeBottom).color = 0
    Cells(5, 8).Borders(xlEdgeBottom).weight = 1
    Cells(5, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 8).Borders(xlEdgeLeft).color = 0
    Cells(5, 8).Borders(xlEdgeLeft).weight = 1
    Cells(5, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 8).Borders(xlEdgeRight).color = 0
    Cells(5, 8).Borders(xlEdgeRight).weight = 1
    Cells(5, 9) = "〇"
    Cells(5, 9).Font.Name = "游ゴシック"
    Cells(5, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 9).Borders(xlEdgeLeft).color = 0
    Cells(5, 9).Borders(xlEdgeLeft).weight = 1
    Cells(5, 10).Font.Name = "游ゴシック"
    Cells(5, 11).Font.Name = "游ゴシック"
    Cells(5, 12).Font.Name = "游ゴシック"
    Cells(5, 13).Font.Name = "游ゴシック"
    Cells(5, 14).Font.Name = "游ゴシック"
    Cells(5, 15).Font.Name = "游ゴシック"
    Cells(5, 16).Font.Name = "游ゴシック"
    Cells(5, 17).Font.Name = "游ゴシック"
    Cells(5, 18).Font.Name = "游ゴシック"
    Cells(6, 1) = "5"
    Cells(6, 1).Font.Name = "游ゴシック"
end Function
Function revival2()
    Cells(6, 2) = "開始/終了"
    Cells(6, 2).Font.Name = "游ゴシック"
    Cells(6, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeRight).color = 0
    Cells(6, 2).Borders(xlEdgeRight).weight = 1
    Cells(6, 3) = "msoShapeFlowchartTerminator"
    Cells(6, 3).Font.Name = "游ゴシック"
    Cells(6, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeTop).color = 0
    Cells(6, 3).Borders(xlEdgeTop).weight = 1
    Cells(6, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeBottom).color = 0
    Cells(6, 3).Borders(xlEdgeBottom).weight = 1
    Cells(6, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeLeft).color = 0
    Cells(6, 3).Borders(xlEdgeLeft).weight = 1
    Cells(6, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeRight).color = 0
    Cells(6, 3).Borders(xlEdgeRight).weight = 1
    Cells(6, 4) = "69"
    Cells(6, 4).Font.Name = "游ゴシック"
    Cells(6, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeTop).color = 0
    Cells(6, 4).Borders(xlEdgeTop).weight = 1
    Cells(6, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeBottom).color = 0
    Cells(6, 4).Borders(xlEdgeBottom).weight = 1
    Cells(6, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeLeft).color = 0
    Cells(6, 4).Borders(xlEdgeLeft).weight = 1
    Cells(6, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeRight).color = 0
    Cells(6, 4).Borders(xlEdgeRight).weight = 1
    Cells(6, 5) = "3"
    Cells(6, 5).Font.Name = "游ゴシック"
    Cells(6, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeTop).color = 0
    Cells(6, 5).Borders(xlEdgeTop).weight = 1
    Cells(6, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeBottom).color = 0
    Cells(6, 5).Borders(xlEdgeBottom).weight = 1
    Cells(6, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeLeft).color = 0
    Cells(6, 5).Borders(xlEdgeLeft).weight = 1
    Cells(6, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeRight).color = 0
    Cells(6, 5).Borders(xlEdgeRight).weight = 1
    Cells(6, 6) = "1"
    Cells(6, 6).Font.Name = "游ゴシック"
    Cells(6, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeTop).color = 0
    Cells(6, 6).Borders(xlEdgeTop).weight = 1
    Cells(6, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeBottom).color = 0
    Cells(6, 6).Borders(xlEdgeBottom).weight = 1
    Cells(6, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeLeft).color = 0
    Cells(6, 6).Borders(xlEdgeLeft).weight = 1
    Cells(6, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeRight).color = 0
    Cells(6, 6).Borders(xlEdgeRight).weight = 1
    Cells(6, 7) = "ターミネーターフローチャート記号"
    Cells(6, 7).Font.Name = "游ゴシック"
    Cells(6, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 7).Borders(xlEdgeTop).color = 0
    Cells(6, 7).Borders(xlEdgeTop).weight = 1
    Cells(6, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 7).Borders(xlEdgeBottom).color = 0
    Cells(6, 7).Borders(xlEdgeBottom).weight = 1
    Cells(6, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 7).Borders(xlEdgeLeft).color = 0
    Cells(6, 7).Borders(xlEdgeLeft).weight = 1
    Cells(6, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 7).Borders(xlEdgeRight).color = 0
    Cells(6, 7).Borders(xlEdgeRight).weight = 1
    Cells(6, 8).Font.Name = "游ゴシック"
    Cells(6, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 8).Borders(xlEdgeTop).color = 0
    Cells(6, 8).Borders(xlEdgeTop).weight = 1
    Cells(6, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 8).Borders(xlEdgeBottom).color = 0
    Cells(6, 8).Borders(xlEdgeBottom).weight = 1
    Cells(6, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 8).Borders(xlEdgeLeft).color = 0
    Cells(6, 8).Borders(xlEdgeLeft).weight = 1
    Cells(6, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 8).Borders(xlEdgeRight).color = 0
    Cells(6, 8).Borders(xlEdgeRight).weight = 1
    Cells(6, 9) = "〇"
    Cells(6, 9).Font.Name = "游ゴシック"
    Cells(6, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 9).Borders(xlEdgeLeft).color = 0
    Cells(6, 9).Borders(xlEdgeLeft).weight = 1
    Cells(6, 10).Font.Name = "游ゴシック"
    Cells(6, 11).Font.Name = "游ゴシック"
    Cells(6, 12).Font.Name = "游ゴシック"
    Cells(6, 13).Font.Name = "游ゴシック"
    Cells(6, 14).Font.Name = "游ゴシック"
    Cells(6, 15).Font.Name = "游ゴシック"
    Cells(6, 16).Font.Name = "游ゴシック"
    Cells(6, 17).Font.Name = "游ゴシック"
    Cells(6, 18).Font.Name = "游ゴシック"
    Cells(7, 1) = "6"
    Cells(7, 1).Font.Name = "游ゴシック"
    Cells(7, 2) = "参照"
    Cells(7, 2).Font.Name = "游ゴシック"
    Cells(7, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeRight).color = 0
    Cells(7, 2).Borders(xlEdgeRight).weight = 1
    Cells(7, 3) = "msoShapeFlowchartConnector"
    Cells(7, 3).Font.Name = "游ゴシック"
    Cells(7, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeTop).color = 0
    Cells(7, 3).Borders(xlEdgeTop).weight = 1
    Cells(7, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeBottom).color = 0
    Cells(7, 3).Borders(xlEdgeBottom).weight = 1
    Cells(7, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeLeft).color = 0
    Cells(7, 3).Borders(xlEdgeLeft).weight = 1
    Cells(7, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeRight).color = 0
    Cells(7, 3).Borders(xlEdgeRight).weight = 1
    Cells(7, 4) = "73"
    Cells(7, 4).Font.Name = "游ゴシック"
    Cells(7, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeTop).color = 0
    Cells(7, 4).Borders(xlEdgeTop).weight = 1
    Cells(7, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeBottom).color = 0
    Cells(7, 4).Borders(xlEdgeBottom).weight = 1
    Cells(7, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeLeft).color = 0
    Cells(7, 4).Borders(xlEdgeLeft).weight = 1
    Cells(7, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeRight).color = 0
    Cells(7, 4).Borders(xlEdgeRight).weight = 1
    Cells(7, 5) = "5"
    Cells(7, 5).Font.Name = "游ゴシック"
    Cells(7, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeTop).color = 0
    Cells(7, 5).Borders(xlEdgeTop).weight = 1
    Cells(7, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeBottom).color = 0
    Cells(7, 5).Borders(xlEdgeBottom).weight = 1
    Cells(7, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeLeft).color = 0
    Cells(7, 5).Borders(xlEdgeLeft).weight = 1
    Cells(7, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeRight).color = 0
    Cells(7, 5).Borders(xlEdgeRight).weight = 1
    Cells(7, 6) = "1"
    Cells(7, 6).Font.Name = "游ゴシック"
    Cells(7, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeTop).color = 0
    Cells(7, 6).Borders(xlEdgeTop).weight = 1
    Cells(7, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeBottom).color = 0
    Cells(7, 6).Borders(xlEdgeBottom).weight = 1
    Cells(7, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeLeft).color = 0
    Cells(7, 6).Borders(xlEdgeLeft).weight = 1
    Cells(7, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeRight).color = 0
    Cells(7, 6).Borders(xlEdgeRight).weight = 1
    Cells(7, 7) = "コネクタフローチャート記号"
    Cells(7, 7).Font.Name = "游ゴシック"
    Cells(7, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 7).Borders(xlEdgeTop).color = 0
    Cells(7, 7).Borders(xlEdgeTop).weight = 1
    Cells(7, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 7).Borders(xlEdgeBottom).color = 0
    Cells(7, 7).Borders(xlEdgeBottom).weight = 1
    Cells(7, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 7).Borders(xlEdgeLeft).color = 0
    Cells(7, 7).Borders(xlEdgeLeft).weight = 1
    Cells(7, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 7).Borders(xlEdgeRight).color = 0
    Cells(7, 7).Borders(xlEdgeRight).weight = 1
    Cells(7, 8).Font.Name = "游ゴシック"
    Cells(7, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 8).Borders(xlEdgeTop).color = 0
    Cells(7, 8).Borders(xlEdgeTop).weight = 1
    Cells(7, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 8).Borders(xlEdgeBottom).color = 0
    Cells(7, 8).Borders(xlEdgeBottom).weight = 1
    Cells(7, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 8).Borders(xlEdgeLeft).color = 0
    Cells(7, 8).Borders(xlEdgeLeft).weight = 1
    Cells(7, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 8).Borders(xlEdgeRight).color = 0
    Cells(7, 8).Borders(xlEdgeRight).weight = 1
    Cells(7, 9) = "〇"
    Cells(7, 9).Font.Name = "游ゴシック"
    Cells(7, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 9).Borders(xlEdgeLeft).color = 0
    Cells(7, 9).Borders(xlEdgeLeft).weight = 1
    Cells(7, 10).Font.Name = "游ゴシック"
    Cells(7, 11).Font.Name = "游ゴシック"
    Cells(7, 12).Font.Name = "游ゴシック"
    Cells(7, 13).Font.Name = "游ゴシック"
end Function
Function revival3()
    Cells(7, 14).Font.Name = "游ゴシック"
    Cells(7, 15).Font.Name = "游ゴシック"
    Cells(7, 16).Font.Name = "游ゴシック"
    Cells(7, 17).Font.Name = "游ゴシック"
    Cells(7, 18).Font.Name = "游ゴシック"
    Cells(8, 1) = "7"
    Cells(8, 1).Font.Name = "游ゴシック"
    Cells(8, 2) = "DBアクセス"
    Cells(8, 2).Font.Name = "游ゴシック"
    Cells(8, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeRight).color = 0
    Cells(8, 2).Borders(xlEdgeRight).weight = 1
    Cells(8, 3) = "msoShapeFlowchartMagneticDisk"
    Cells(8, 3).Font.Name = "游ゴシック"
    Cells(8, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeTop).color = 0
    Cells(8, 3).Borders(xlEdgeTop).weight = 1
    Cells(8, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeBottom).color = 0
    Cells(8, 3).Borders(xlEdgeBottom).weight = 1
    Cells(8, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeLeft).color = 0
    Cells(8, 3).Borders(xlEdgeLeft).weight = 1
    Cells(8, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeRight).color = 0
    Cells(8, 3).Borders(xlEdgeRight).weight = 1
    Cells(8, 4) = "86"
    Cells(8, 4).Font.Name = "游ゴシック"
    Cells(8, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeTop).color = 0
    Cells(8, 4).Borders(xlEdgeTop).weight = 1
    Cells(8, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeBottom).color = 0
    Cells(8, 4).Borders(xlEdgeBottom).weight = 1
    Cells(8, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeLeft).color = 0
    Cells(8, 4).Borders(xlEdgeLeft).weight = 1
    Cells(8, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeRight).color = 0
    Cells(8, 4).Borders(xlEdgeRight).weight = 1
    Cells(8, 5) = "4"
    Cells(8, 5).Font.Name = "游ゴシック"
    Cells(8, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeTop).color = 0
    Cells(8, 5).Borders(xlEdgeTop).weight = 1
    Cells(8, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeBottom).color = 0
    Cells(8, 5).Borders(xlEdgeBottom).weight = 1
    Cells(8, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeLeft).color = 0
    Cells(8, 5).Borders(xlEdgeLeft).weight = 1
    Cells(8, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeRight).color = 0
    Cells(8, 5).Borders(xlEdgeRight).weight = 1
    Cells(8, 6) = "2"
    Cells(8, 6).Font.Name = "游ゴシック"
    Cells(8, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeTop).color = 0
    Cells(8, 6).Borders(xlEdgeTop).weight = 1
    Cells(8, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeBottom).color = 0
    Cells(8, 6).Borders(xlEdgeBottom).weight = 1
    Cells(8, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeLeft).color = 0
    Cells(8, 6).Borders(xlEdgeLeft).weight = 1
    Cells(8, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeRight).color = 0
    Cells(8, 6).Borders(xlEdgeRight).weight = 1
    Cells(8, 7) = "磁気ディスクフローチャート記号"
    Cells(8, 7).Font.Name = "游ゴシック"
    Cells(8, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 7).Borders(xlEdgeTop).color = 0
    Cells(8, 7).Borders(xlEdgeTop).weight = 1
    Cells(8, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 7).Borders(xlEdgeBottom).color = 0
    Cells(8, 7).Borders(xlEdgeBottom).weight = 1
    Cells(8, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 7).Borders(xlEdgeLeft).color = 0
    Cells(8, 7).Borders(xlEdgeLeft).weight = 1
    Cells(8, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 7).Borders(xlEdgeRight).color = 0
    Cells(8, 7).Borders(xlEdgeRight).weight = 1
    Cells(8, 8).Font.Name = "游ゴシック"
    Cells(8, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 8).Borders(xlEdgeTop).color = 0
    Cells(8, 8).Borders(xlEdgeTop).weight = 1
    Cells(8, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 8).Borders(xlEdgeBottom).color = 0
    Cells(8, 8).Borders(xlEdgeBottom).weight = 1
    Cells(8, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 8).Borders(xlEdgeLeft).color = 0
    Cells(8, 8).Borders(xlEdgeLeft).weight = 1
    Cells(8, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 8).Borders(xlEdgeRight).color = 0
    Cells(8, 8).Borders(xlEdgeRight).weight = 1
    Cells(8, 9) = "〇"
    Cells(8, 9).Font.Name = "游ゴシック"
    Cells(8, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 9).Borders(xlEdgeLeft).color = 0
    Cells(8, 9).Borders(xlEdgeLeft).weight = 1
    Cells(8, 10).Font.Name = "游ゴシック"
    Cells(8, 11).Font.Name = "游ゴシック"
    Cells(8, 12).Font.Name = "游ゴシック"
    Cells(8, 13).Font.Name = "游ゴシック"
    Cells(8, 14).Font.Name = "游ゴシック"
    Cells(8, 15).Font.Name = "游ゴシック"
    Cells(8, 16).Font.Name = "游ゴシック"
    Cells(8, 17).Font.Name = "游ゴシック"
    Cells(8, 18).Font.Name = "游ゴシック"
    Cells(9, 1) = "8"
    Cells(9, 1).Font.Name = "游ゴシック"
    Cells(9, 2) = "ループ開始/ループ終了"
    Cells(9, 2).Font.Name = "游ゴシック"
    Cells(9, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeRight).color = 0
    Cells(9, 2).Borders(xlEdgeRight).weight = 1
    Cells(9, 3) = "msoShapeSnip2SameRectangle"
    Cells(9, 3).Font.Name = "游ゴシック"
    Cells(9, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeTop).color = 0
    Cells(9, 3).Borders(xlEdgeTop).weight = 1
    Cells(9, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeBottom).color = 0
    Cells(9, 3).Borders(xlEdgeBottom).weight = 1
    Cells(9, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeLeft).color = 0
    Cells(9, 3).Borders(xlEdgeLeft).weight = 1
    Cells(9, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeRight).color = 0
    Cells(9, 3).Borders(xlEdgeRight).weight = 1
    Cells(9, 4) = "156"
    Cells(9, 4).Font.Name = "游ゴシック"
    Cells(9, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeTop).color = 0
    Cells(9, 4).Borders(xlEdgeTop).weight = 1
    Cells(9, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeBottom).color = 0
    Cells(9, 4).Borders(xlEdgeBottom).weight = 1
    Cells(9, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeLeft).color = 0
    Cells(9, 4).Borders(xlEdgeLeft).weight = 1
    Cells(9, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeRight).color = 0
    Cells(9, 4).Borders(xlEdgeRight).weight = 1
    Cells(9, 5) = "2"
    Cells(9, 5).Font.Name = "游ゴシック"
    Cells(9, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeTop).color = 0
    Cells(9, 5).Borders(xlEdgeTop).weight = 1
    Cells(9, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeBottom).color = 0
    Cells(9, 5).Borders(xlEdgeBottom).weight = 1
    Cells(9, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeLeft).color = 0
    Cells(9, 5).Borders(xlEdgeLeft).weight = 1
    Cells(9, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeRight).color = 0
    Cells(9, 5).Borders(xlEdgeRight).weight = 1
    Cells(9, 6) = "4"
    Cells(9, 6).Font.Name = "游ゴシック"
    Cells(9, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeTop).color = 0
    Cells(9, 6).Borders(xlEdgeTop).weight = 1
    Cells(9, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeBottom).color = 0
    Cells(9, 6).Borders(xlEdgeBottom).weight = 1
    Cells(9, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeLeft).color = 0
    Cells(9, 6).Borders(xlEdgeLeft).weight = 1
    Cells(9, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeRight).color = 0
    Cells(9, 6).Borders(xlEdgeRight).weight = 1
    Cells(9, 7) = "側面を共有する 2 つのスニップされた角を持つ四角形"
    Cells(9, 7).Font.Name = "游ゴシック"
    Cells(9, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 7).Borders(xlEdgeTop).color = 0
    Cells(9, 7).Borders(xlEdgeTop).weight = 1
    Cells(9, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 7).Borders(xlEdgeBottom).color = 0
    Cells(9, 7).Borders(xlEdgeBottom).weight = 1
    Cells(9, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 7).Borders(xlEdgeLeft).color = 0
    Cells(9, 7).Borders(xlEdgeLeft).weight = 1
    Cells(9, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 7).Borders(xlEdgeRight).color = 0
    Cells(9, 7).Borders(xlEdgeRight).weight = 1
end Function
Function revival4()
    Cells(9, 8).Font.Name = "游ゴシック"
    Cells(9, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 8).Borders(xlEdgeTop).color = 0
    Cells(9, 8).Borders(xlEdgeTop).weight = 1
    Cells(9, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 8).Borders(xlEdgeBottom).color = 0
    Cells(9, 8).Borders(xlEdgeBottom).weight = 1
    Cells(9, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 8).Borders(xlEdgeLeft).color = 0
    Cells(9, 8).Borders(xlEdgeLeft).weight = 1
    Cells(9, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 8).Borders(xlEdgeRight).color = 0
    Cells(9, 8).Borders(xlEdgeRight).weight = 1
    Cells(9, 9) = "〇"
    Cells(9, 9).Font.Name = "游ゴシック"
    Cells(9, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 9).Borders(xlEdgeLeft).color = 0
    Cells(9, 9).Borders(xlEdgeLeft).weight = 1
    Cells(9, 10).Font.Name = "游ゴシック"
    Cells(9, 11).Font.Name = "游ゴシック"
    Cells(9, 12).Font.Name = "游ゴシック"
    Cells(9, 13).Font.Name = "游ゴシック"
    Cells(9, 14).Font.Name = "游ゴシック"
    Cells(9, 15).Font.Name = "游ゴシック"
    Cells(9, 16).Font.Name = "游ゴシック"
    Cells(9, 17).Font.Name = "游ゴシック"
    Cells(9, 18).Font.Name = "游ゴシック"
    Cells(10, 1).Font.Name = "游ゴシック"
    Cells(10, 2).Font.Name = "游ゴシック"
    Cells(10, 3).Font.Name = "游ゴシック"
    Cells(10, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeTop).color = 0
    Cells(10, 3).Borders(xlEdgeTop).weight = 1
    Cells(10, 4).Font.Name = "游ゴシック"
    Cells(10, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeTop).color = 0
    Cells(10, 4).Borders(xlEdgeTop).weight = 1
    Cells(10, 5).Font.Name = "游ゴシック"
    Cells(10, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeTop).color = 0
    Cells(10, 5).Borders(xlEdgeTop).weight = 1
    Cells(10, 6).Font.Name = "游ゴシック"
    Cells(10, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeTop).color = 0
    Cells(10, 6).Borders(xlEdgeTop).weight = 1
    Cells(10, 7).Font.Name = "游ゴシック"
    Cells(10, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 7).Borders(xlEdgeTop).color = 0
    Cells(10, 7).Borders(xlEdgeTop).weight = 1
    Cells(10, 8).Font.Name = "游ゴシック"
    Cells(10, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 8).Borders(xlEdgeTop).color = 0
    Cells(10, 8).Borders(xlEdgeTop).weight = 1
    Cells(10, 9).Font.Name = "游ゴシック"
    Cells(10, 10).Font.Name = "游ゴシック"
    Cells(10, 11).Font.Name = "游ゴシック"
    Cells(10, 12).Font.Name = "游ゴシック"
    Cells(10, 13).Font.Name = "游ゴシック"
    Cells(10, 14).Font.Name = "游ゴシック"
    Cells(10, 15).Font.Name = "游ゴシック"
    Cells(10, 16).Font.Name = "游ゴシック"
    Cells(10, 17).Font.Name = "游ゴシック"
    Cells(10, 18).Font.Name = "游ゴシック"
    Cells(11, 1) = "▼これを[詳細]シートの1行目に設定"
    Cells(11, 1).Font.Name = "游ゴシック"
    Cells(11, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 1).Borders(xlEdgeBottom).color = 0
    Cells(11, 1).Borders(xlEdgeBottom).weight = 2
end Function
Function revival5()
    Cells(11, 2).Font.Name = "游ゴシック"
    Cells(11, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 2).Borders(xlEdgeBottom).color = 0
    Cells(11, 2).Borders(xlEdgeBottom).weight = 2
    Cells(11, 3).Font.Name = "游ゴシック"
    Cells(11, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 3).Borders(xlEdgeBottom).color = 0
    Cells(11, 3).Borders(xlEdgeBottom).weight = 2
    Cells(11, 4).Font.Name = "游ゴシック"
    Cells(11, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 4).Borders(xlEdgeBottom).color = 0
    Cells(11, 4).Borders(xlEdgeBottom).weight = 2
    Cells(11, 5).Font.Name = "游ゴシック"
    Cells(11, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 5).Borders(xlEdgeBottom).color = 0
    Cells(11, 5).Borders(xlEdgeBottom).weight = 2
    Cells(11, 6).Font.Name = "游ゴシック"
    Cells(11, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 6).Borders(xlEdgeBottom).color = 0
    Cells(11, 6).Borders(xlEdgeBottom).weight = 2
    Cells(11, 7).Font.Name = "游ゴシック"
    Cells(11, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 7).Borders(xlEdgeBottom).color = 0
    Cells(11, 7).Borders(xlEdgeBottom).weight = 2
    Cells(11, 8).Font.Name = "游ゴシック"
    Cells(11, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 8).Borders(xlEdgeBottom).color = 0
    Cells(11, 8).Borders(xlEdgeBottom).weight = 2
    Cells(11, 9).Font.Name = "游ゴシック"
    Cells(11, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 9).Borders(xlEdgeBottom).color = 0
    Cells(11, 9).Borders(xlEdgeBottom).weight = 2
    Cells(11, 10).Font.Name = "游ゴシック"
    Cells(11, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 10).Borders(xlEdgeBottom).color = 0
    Cells(11, 10).Borders(xlEdgeBottom).weight = 2
    Cells(11, 11).Font.Name = "游ゴシック"
    Cells(11, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 11).Borders(xlEdgeBottom).color = 0
    Cells(11, 11).Borders(xlEdgeBottom).weight = 2
    Cells(11, 12).Font.Name = "游ゴシック"
    Cells(11, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 12).Borders(xlEdgeBottom).color = 0
    Cells(11, 12).Borders(xlEdgeBottom).weight = 2
    Cells(11, 13).Font.Name = "游ゴシック"
    Cells(11, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 13).Borders(xlEdgeBottom).color = 0
    Cells(11, 13).Borders(xlEdgeBottom).weight = 2
    Cells(11, 14).Font.Name = "游ゴシック"
    Cells(11, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 14).Borders(xlEdgeBottom).color = 0
    Cells(11, 14).Borders(xlEdgeBottom).weight = 2
    Cells(11, 15).Font.Name = "游ゴシック"
    Cells(11, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 15).Borders(xlEdgeBottom).color = 0
    Cells(11, 15).Borders(xlEdgeBottom).weight = 2
    Cells(11, 16).Font.Name = "游ゴシック"
    Cells(11, 16).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 16).Borders(xlEdgeBottom).color = 0
    Cells(11, 16).Borders(xlEdgeBottom).weight = 2
    Cells(11, 17).Font.Name = "游ゴシック"
    Cells(11, 17).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 17).Borders(xlEdgeBottom).color = 0
    Cells(11, 17).Borders(xlEdgeBottom).weight = 2
    Cells(11, 18).Font.Name = "游ゴシック"
    Cells(11, 18).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 18).Borders(xlEdgeBottom).color = 0
    Cells(11, 18).Borders(xlEdgeBottom).weight = 2
    Cells(12, 1) = "処理No"
    Cells(12, 1).Font.Name = "Meiryo UI"
    Cells(12, 1).Interior.Color = 13431551
    Cells(12, 1).Font.Bold = True
    Cells(12, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeTop).color = 0
    Cells(12, 1).Borders(xlEdgeTop).weight = 2
    Cells(12, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeBottom).color = 0
    Cells(12, 1).Borders(xlEdgeBottom).weight = 2
    Cells(12, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeLeft).color = 0
    Cells(12, 1).Borders(xlEdgeLeft).weight = 2
    Cells(12, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeRight).color = 0
    Cells(12, 1).Borders(xlEdgeRight).weight = 2
    Cells(12, 2) = "フローNo"
    Cells(12, 2).Font.Name = "Meiryo UI"
    Cells(12, 2).Interior.Color = 13431551
    Cells(12, 2).Font.Bold = True
    Cells(12, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeTop).color = 0
    Cells(12, 2).Borders(xlEdgeTop).weight = 2
    Cells(12, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeBottom).color = 0
    Cells(12, 2).Borders(xlEdgeBottom).weight = 2
    Cells(12, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeLeft).color = 0
    Cells(12, 2).Borders(xlEdgeLeft).weight = 2
    Cells(12, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeRight).color = 0
    Cells(12, 2).Borders(xlEdgeRight).weight = 2
    Cells(12, 3) = "遷移先"
    Cells(12, 3).Font.Name = "Meiryo UI"
    Cells(12, 3).Interior.Color = 13431551
    Cells(12, 3).Font.Bold = True
    Cells(12, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeTop).color = 0
    Cells(12, 3).Borders(xlEdgeTop).weight = 2
    Cells(12, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeBottom).color = 0
    Cells(12, 3).Borders(xlEdgeBottom).weight = 2
    Cells(12, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeLeft).color = 0
    Cells(12, 3).Borders(xlEdgeLeft).weight = 2
    Cells(12, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeRight).color = 0
    Cells(12, 3).Borders(xlEdgeRight).weight = 2
    Cells(12, 4) = "種別"
    Cells(12, 4).Font.Name = "Meiryo UI"
    Cells(12, 4).Interior.Color = 13431551
    Cells(12, 4).Font.Bold = True
    Cells(12, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeTop).color = 0
    Cells(12, 4).Borders(xlEdgeTop).weight = 2
    Cells(12, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeBottom).color = 0
    Cells(12, 4).Borders(xlEdgeBottom).weight = 2
    Cells(12, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeLeft).color = 0
    Cells(12, 4).Borders(xlEdgeLeft).weight = 2
    Cells(12, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeRight).color = 0
    Cells(12, 4).Borders(xlEdgeRight).weight = 2
    Cells(12, 5) = "フローテキスト"
    Cells(12, 5).Font.Name = "Meiryo UI"
    Cells(12, 5).Interior.Color = 13431551
    Cells(12, 5).Font.Bold = True
    Range("E12:G12").Merge
    Cells(12, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeTop).color = 0
    Cells(12, 5).Borders(xlEdgeTop).weight = 2
    Cells(12, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeBottom).color = 0
    Cells(12, 5).Borders(xlEdgeBottom).weight = 2
    Cells(12, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeLeft).color = 0
    Cells(12, 5).Borders(xlEdgeLeft).weight = 2
    Cells(12, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeRight).color = 0
    Cells(12, 5).Borders(xlEdgeRight).weight = 2
    Cells(12, 6).Font.Name = "Meiryo UI"
    Cells(12, 6).Interior.Color = 13431551
    Cells(12, 6).Font.Bold = True
    Range("E12:G12").Merge
    Cells(12, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeTop).color = 0
    Cells(12, 6).Borders(xlEdgeTop).weight = 2
    Cells(12, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeBottom).color = 0
    Cells(12, 6).Borders(xlEdgeBottom).weight = 2
    Cells(12, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeLeft).color = 0
    Cells(12, 6).Borders(xlEdgeLeft).weight = 2
    Cells(12, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeRight).color = 0
    Cells(12, 6).Borders(xlEdgeRight).weight = 2
    Cells(12, 7).Font.Name = "Meiryo UI"
    Cells(12, 7).Interior.Color = 13431551
    Cells(12, 7).Font.Bold = True
    Range("E12:G12").Merge
    Cells(12, 7).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 7).Borders(xlEdgeTop).color = 0
    Cells(12, 7).Borders(xlEdgeTop).weight = 2
    Cells(12, 7).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 7).Borders(xlEdgeBottom).color = 0
    Cells(12, 7).Borders(xlEdgeBottom).weight = 2
    Cells(12, 7).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 7).Borders(xlEdgeLeft).color = 0
    Cells(12, 7).Borders(xlEdgeLeft).weight = 2
    Cells(12, 7).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 7).Borders(xlEdgeRight).color = 0
    Cells(12, 7).Borders(xlEdgeRight).weight = 2
    Cells(12, 8) = "説明"
    Cells(12, 8).Font.Name = "Meiryo UI"
    Cells(12, 8).Interior.Color = 13431551
    Cells(12, 8).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 8).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 8).Borders(xlEdgeTop).color = 0
    Cells(12, 8).Borders(xlEdgeTop).weight = 2
    Cells(12, 8).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 8).Borders(xlEdgeBottom).color = 0
    Cells(12, 8).Borders(xlEdgeBottom).weight = 2
    Cells(12, 8).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 8).Borders(xlEdgeLeft).color = 0
    Cells(12, 8).Borders(xlEdgeLeft).weight = 2
    Cells(12, 8).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 8).Borders(xlEdgeRight).color = 0
    Cells(12, 8).Borders(xlEdgeRight).weight = 2
    Cells(12, 9).Font.Name = "Meiryo UI"
    Cells(12, 9).Interior.Color = 13431551
    Cells(12, 9).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 9).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 9).Borders(xlEdgeTop).color = 0
    Cells(12, 9).Borders(xlEdgeTop).weight = 2
    Cells(12, 9).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 9).Borders(xlEdgeBottom).color = 0
    Cells(12, 9).Borders(xlEdgeBottom).weight = 2
    Cells(12, 9).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 9).Borders(xlEdgeLeft).color = 0
    Cells(12, 9).Borders(xlEdgeLeft).weight = 2
    Cells(12, 9).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 9).Borders(xlEdgeRight).color = 0
    Cells(12, 9).Borders(xlEdgeRight).weight = 2
    Cells(12, 10).Font.Name = "Meiryo UI"
    Cells(12, 10).Interior.Color = 13431551
    Cells(12, 10).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 10).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 10).Borders(xlEdgeTop).color = 0
    Cells(12, 10).Borders(xlEdgeTop).weight = 2
    Cells(12, 10).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 10).Borders(xlEdgeBottom).color = 0
    Cells(12, 10).Borders(xlEdgeBottom).weight = 2
    Cells(12, 10).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 10).Borders(xlEdgeLeft).color = 0
    Cells(12, 10).Borders(xlEdgeLeft).weight = 2
    Cells(12, 10).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 10).Borders(xlEdgeRight).color = 0
    Cells(12, 10).Borders(xlEdgeRight).weight = 2
    Cells(12, 11).Font.Name = "Meiryo UI"
    Cells(12, 11).Interior.Color = 13431551
    Cells(12, 11).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 11).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 11).Borders(xlEdgeTop).color = 0
    Cells(12, 11).Borders(xlEdgeTop).weight = 2
    Cells(12, 11).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 11).Borders(xlEdgeBottom).color = 0
    Cells(12, 11).Borders(xlEdgeBottom).weight = 2
    Cells(12, 11).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 11).Borders(xlEdgeLeft).color = 0
    Cells(12, 11).Borders(xlEdgeLeft).weight = 2
    Cells(12, 11).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 11).Borders(xlEdgeRight).color = 0
    Cells(12, 11).Borders(xlEdgeRight).weight = 2
    Cells(12, 12).Font.Name = "Meiryo UI"
    Cells(12, 12).Interior.Color = 13431551
    Cells(12, 12).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 12).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 12).Borders(xlEdgeTop).color = 0
    Cells(12, 12).Borders(xlEdgeTop).weight = 2
    Cells(12, 12).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 12).Borders(xlEdgeBottom).color = 0
    Cells(12, 12).Borders(xlEdgeBottom).weight = 2
    Cells(12, 12).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 12).Borders(xlEdgeLeft).color = 0
    Cells(12, 12).Borders(xlEdgeLeft).weight = 2
    Cells(12, 12).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 12).Borders(xlEdgeRight).color = 0
    Cells(12, 12).Borders(xlEdgeRight).weight = 2
    Cells(12, 13).Font.Name = "Meiryo UI"
    Cells(12, 13).Interior.Color = 13431551
    Cells(12, 13).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 13).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 13).Borders(xlEdgeTop).color = 0
    Cells(12, 13).Borders(xlEdgeTop).weight = 2
    Cells(12, 13).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 13).Borders(xlEdgeBottom).color = 0
    Cells(12, 13).Borders(xlEdgeBottom).weight = 2
    Cells(12, 13).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 13).Borders(xlEdgeLeft).color = 0
    Cells(12, 13).Borders(xlEdgeLeft).weight = 2
    Cells(12, 13).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 13).Borders(xlEdgeRight).color = 0
    Cells(12, 13).Borders(xlEdgeRight).weight = 2
end Function
Function revival6()
    Cells(12, 14).Font.Name = "Meiryo UI"
    Cells(12, 14).Interior.Color = 13431551
    Cells(12, 14).Font.Bold = True
    Range("H12:N12").Merge
    Cells(12, 14).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 14).Borders(xlEdgeTop).color = 0
    Cells(12, 14).Borders(xlEdgeTop).weight = 2
    Cells(12, 14).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 14).Borders(xlEdgeBottom).color = 0
    Cells(12, 14).Borders(xlEdgeBottom).weight = 2
    Cells(12, 14).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 14).Borders(xlEdgeLeft).color = 0
    Cells(12, 14).Borders(xlEdgeLeft).weight = 2
    Cells(12, 14).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 14).Borders(xlEdgeRight).color = 0
    Cells(12, 14).Borders(xlEdgeRight).weight = 2
    Cells(12, 15) = "ファイル名"
    Cells(12, 15).Font.Name = "Meiryo UI"
    Cells(12, 15).Interior.Color = 13431551
    Cells(12, 15).Font.Bold = True
    Cells(12, 15).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 15).Borders(xlEdgeTop).color = 0
    Cells(12, 15).Borders(xlEdgeTop).weight = 2
    Cells(12, 15).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 15).Borders(xlEdgeBottom).color = 0
    Cells(12, 15).Borders(xlEdgeBottom).weight = 2
    Cells(12, 15).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 15).Borders(xlEdgeLeft).color = 0
    Cells(12, 15).Borders(xlEdgeLeft).weight = 2
    Cells(12, 15).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 15).Borders(xlEdgeRight).color = 0
    Cells(12, 15).Borders(xlEdgeRight).weight = 2
    Cells(12, 16) = "テーブル名"
    Cells(12, 16).Font.Name = "Meiryo UI"
    Cells(12, 16).Interior.Color = 13431551
    Cells(12, 16).Font.Bold = True
    Cells(12, 16).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 16).Borders(xlEdgeTop).color = 0
    Cells(12, 16).Borders(xlEdgeTop).weight = 2
    Cells(12, 16).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 16).Borders(xlEdgeBottom).color = 0
    Cells(12, 16).Borders(xlEdgeBottom).weight = 2
    Cells(12, 16).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 16).Borders(xlEdgeLeft).color = 0
    Cells(12, 16).Borders(xlEdgeLeft).weight = 2
    Cells(12, 16).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 16).Borders(xlEdgeRight).color = 0
    Cells(12, 16).Borders(xlEdgeRight).weight = 2
    Cells(12, 17) = "言語"
    Cells(12, 17).Font.Name = "Meiryo UI"
    Cells(12, 17).Interior.Color = 13431551
    Cells(12, 17).Font.Bold = True
    Cells(12, 17).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 17).Borders(xlEdgeTop).color = 0
    Cells(12, 17).Borders(xlEdgeTop).weight = 2
    Cells(12, 17).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 17).Borders(xlEdgeBottom).color = 0
    Cells(12, 17).Borders(xlEdgeBottom).weight = 2
    Cells(12, 17).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 17).Borders(xlEdgeLeft).color = 0
    Cells(12, 17).Borders(xlEdgeLeft).weight = 2
    Cells(12, 17).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 17).Borders(xlEdgeRight).color = 0
    Cells(12, 17).Borders(xlEdgeRight).weight = 2
    Cells(12, 18) = "CRUD"
    Cells(12, 18).Font.Name = "Meiryo UI"
    Cells(12, 18).Interior.Color = 13431551
    Cells(12, 18).Font.Bold = True
    Cells(12, 18).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 18).Borders(xlEdgeTop).color = 0
    Cells(12, 18).Borders(xlEdgeTop).weight = 2
    Cells(12, 18).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 18).Borders(xlEdgeBottom).color = 0
    Cells(12, 18).Borders(xlEdgeBottom).weight = 2
    Cells(12, 18).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 18).Borders(xlEdgeLeft).color = 0
    Cells(12, 18).Borders(xlEdgeLeft).weight = 2
    Cells(12, 18).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 18).Borders(xlEdgeRight).color = 0
    Cells(12, 18).Borders(xlEdgeRight).weight = 2
    Rows(1).RowHeight = 18.75
    Rows(2).RowHeight = 32.25
    Rows(3).RowHeight = 32.25
    Rows(4).RowHeight = 32.25
    Rows(5).RowHeight = 32.25
    Rows(6).RowHeight = 32.25
    Rows(7).RowHeight = 32.25
    Rows(8).RowHeight = 32.25
    Rows(9).RowHeight = 32.25
    Rows(10).RowHeight = 32.25
    Rows(11).RowHeight = 32.25
    Rows(12).RowHeight = 32.25
    Columns(1).ColumnWidth = 8.38
    Columns(2).ColumnWidth = 8.38
    Columns(3).ColumnWidth = 36.38
    Columns(4).ColumnWidth = 3.75
    Columns(5).ColumnWidth = 8.63
    Columns(6).ColumnWidth = 8.63
    Columns(7).ColumnWidth = 89.38
    Columns(8).ColumnWidth = 8.38
    Columns(9).ColumnWidth = 8.38
    Columns(10).ColumnWidth = 8.38
    Columns(11).ColumnWidth = 8.38
    Columns(12).ColumnWidth = 8.38
    Columns(13).ColumnWidth = 8.38
    Columns(14).ColumnWidth = 8.38
    Columns(15).ColumnWidth = 8.38
    Columns(16).ColumnWidth = 8.38
    Columns(17).ColumnWidth = 8.38
    Columns(18).ColumnWidth = 8.38
    Dim onShape As Object
    Set onShape = ActiveSheet.Shapes.AddShape(61,1012.25,23.75,44,22.25)
    onShape.Name = "Flowchart: Process 61"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(63,1012.25,56,44,22.25)
    onShape.Name = "Flowchart: Decision 63"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(64,1012.25,88.25,44,22.25)
    onShape.Name = "Flowchart: Data 64"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(65,1012.25,120.5,44,22.25)
    onShape.Name = "Flowchart: Predefined Process 65"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(69,1012.25,152.75,44,22.25)
    onShape.Name = "Flowchart: Terminator 69"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(73,1012.25,185,44,22.25)
    onShape.Name = "Flowchart: Connector 73"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(86,1012.25,217.25,44,22.25)
    onShape.Name = "Flowchart: Magnetic Disk 86"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Shapes.AddShape(156,1012.25,249.5,44,22.25)
    onShape.Name = "Snip Same Side Corner Rectangle 156"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 3289605
    onShape.TextFrame2.WordArtformat = -2
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = ""
    onShape.Fill.ForeColor.RGB = 16777215
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 1
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
End Function
sub revival()
    CALL revival0()
    CALL revival1()
    CALL revival2()
    CALL revival3()
    CALL revival4()
    CALL revival5()
    CALL revival6()
end sub