Attribute VB_Name = "setup7"
Function revival0()
    ActiveWindow.DisplayGridlines = False
    ActiveWindow.Zoom = 85
    ActiveSheet.Name = "Error定義"
    Cells(1, 1) = "No"
    Cells(1, 1).Font.Name = "BIZ UDPゴシック"
    Cells(1, 1).Interior.Color = 16247773
    Cells(1, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeTop).color = 0
    Cells(1, 1).Borders(xlEdgeTop).weight = 2
    Cells(1, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeBottom).color = 0
    Cells(1, 1).Borders(xlEdgeBottom).weight = 2
    Cells(1, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeLeft).color = 0
    Cells(1, 1).Borders(xlEdgeLeft).weight = 2
    Cells(1, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 1).Borders(xlEdgeRight).color = 0
    Cells(1, 1).Borders(xlEdgeRight).weight = 2
    Cells(1, 2) = "データ型"
    Cells(1, 2).Font.Name = "BIZ UDPゴシック"
    Cells(1, 2).Interior.Color = 16247773
    Cells(1, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeTop).color = 0
    Cells(1, 2).Borders(xlEdgeTop).weight = 2
    Cells(1, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeBottom).color = 0
    Cells(1, 2).Borders(xlEdgeBottom).weight = 2
    Cells(1, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeLeft).color = 0
    Cells(1, 2).Borders(xlEdgeLeft).weight = 2
    Cells(1, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 2).Borders(xlEdgeRight).color = 0
    Cells(1, 2).Borders(xlEdgeRight).weight = 2
    Cells(1, 3) = "属性"
    Cells(1, 3).Font.Name = "BIZ UDPゴシック"
    Cells(1, 3).Interior.Color = 16247773
    Cells(1, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeTop).color = 0
    Cells(1, 3).Borders(xlEdgeTop).weight = 2
    Cells(1, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeBottom).color = 0
    Cells(1, 3).Borders(xlEdgeBottom).weight = 2
    Cells(1, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeLeft).color = 0
    Cells(1, 3).Borders(xlEdgeLeft).weight = 2
    Cells(1, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 3).Borders(xlEdgeRight).color = 0
    Cells(1, 3).Borders(xlEdgeRight).weight = 2
    Cells(1, 4) = "指定列"
    Cells(1, 4).Font.Name = "BIZ UDPゴシック"
    Cells(1, 4).Interior.Color = 16247773
    Cells(1, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeTop).color = 0
    Cells(1, 4).Borders(xlEdgeTop).weight = 2
    Cells(1, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeBottom).color = 0
    Cells(1, 4).Borders(xlEdgeBottom).weight = 2
    Cells(1, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeLeft).color = 0
    Cells(1, 4).Borders(xlEdgeLeft).weight = 2
    Cells(1, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 4).Borders(xlEdgeRight).color = 0
    Cells(1, 4).Borders(xlEdgeRight).weight = 2
    Cells(1, 5) = "内容"
    Cells(1, 5).Font.Name = "BIZ UDPゴシック"
    Cells(1, 5).Interior.Color = 16247773
    Cells(1, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeTop).color = 0
    Cells(1, 5).Borders(xlEdgeTop).weight = 2
    Cells(1, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeBottom).color = 0
    Cells(1, 5).Borders(xlEdgeBottom).weight = 2
    Cells(1, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeLeft).color = 0
    Cells(1, 5).Borders(xlEdgeLeft).weight = 2
    Cells(1, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 5).Borders(xlEdgeRight).color = 0
    Cells(1, 5).Borders(xlEdgeRight).weight = 2
    Cells(1, 6) = "条件"
    Cells(1, 6).Font.Name = "BIZ UDPゴシック"
    Cells(1, 6).Interior.Color = 16247773
    Cells(1, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeTop).color = 0
    Cells(1, 6).Borders(xlEdgeTop).weight = 2
    Cells(1, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeBottom).color = 0
    Cells(1, 6).Borders(xlEdgeBottom).weight = 2
    Cells(1, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeLeft).color = 0
    Cells(1, 6).Borders(xlEdgeLeft).weight = 2
    Cells(1, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(1, 6).Borders(xlEdgeRight).color = 0
    Cells(1, 6).Borders(xlEdgeRight).weight = 2
    Cells(2, 1) = "1"
    Cells(2, 1).Font.Name = "BIZ UDPゴシック"
    Cells(2, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeTop).color = 0
    Cells(2, 1).Borders(xlEdgeTop).weight = 2
    Cells(2, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeBottom).color = 0
    Cells(2, 1).Borders(xlEdgeBottom).weight = 2
    Cells(2, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeLeft).color = 0
    Cells(2, 1).Borders(xlEdgeLeft).weight = 2
    Cells(2, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 1).Borders(xlEdgeRight).color = 0
    Cells(2, 1).Borders(xlEdgeRight).weight = 2
    Cells(2, 2) = "数値"
    Cells(2, 2).Font.Name = "BIZ UDPゴシック"
    Cells(2, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeTop).color = 0
    Cells(2, 2).Borders(xlEdgeTop).weight = 2
    Cells(2, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeBottom).color = 0
    Cells(2, 2).Borders(xlEdgeBottom).weight = 2
    Cells(2, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeLeft).color = 0
    Cells(2, 2).Borders(xlEdgeLeft).weight = 2
    Cells(2, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 2).Borders(xlEdgeRight).color = 0
    Cells(2, 2).Borders(xlEdgeRight).weight = 2
    Cells(2, 3) = "有効桁数"
    Cells(2, 3).Font.Name = "BIZ UDPゴシック"
    Cells(2, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeTop).color = 0
    Cells(2, 3).Borders(xlEdgeTop).weight = 2
    Cells(2, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeBottom).color = 0
    Cells(2, 3).Borders(xlEdgeBottom).weight = 2
    Cells(2, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeLeft).color = 0
    Cells(2, 3).Borders(xlEdgeLeft).weight = 2
    Cells(2, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 3).Borders(xlEdgeRight).color = 0
    Cells(2, 3).Borders(xlEdgeRight).weight = 2
    Cells(2, 4) = "11"
    Cells(2, 4).Font.Name = "BIZ UDPゴシック"
    Cells(2, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeTop).color = 0
    Cells(2, 4).Borders(xlEdgeTop).weight = 2
    Cells(2, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeBottom).color = 0
    Cells(2, 4).Borders(xlEdgeBottom).weight = 2
    Cells(2, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeLeft).color = 0
    Cells(2, 4).Borders(xlEdgeLeft).weight = 2
    Cells(2, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 4).Borders(xlEdgeRight).color = 0
    Cells(2, 4).Borders(xlEdgeRight).weight = 2
    Cells(2, 5) = "1"
    Cells(2, 5).Font.Name = "BIZ UDPゴシック"
    Cells(2, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeTop).color = 0
    Cells(2, 5).Borders(xlEdgeTop).weight = 2
    Cells(2, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeBottom).color = 0
    Cells(2, 5).Borders(xlEdgeBottom).weight = 2
    Cells(2, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeLeft).color = 0
    Cells(2, 5).Borders(xlEdgeLeft).weight = 2
    Cells(2, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 5).Borders(xlEdgeRight).color = 0
    Cells(2, 5).Borders(xlEdgeRight).weight = 2
    Cells(2, 6) = "以上"
    Cells(2, 6).Font.Name = "BIZ UDPゴシック"
    Cells(2, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeTop).color = 0
    Cells(2, 6).Borders(xlEdgeTop).weight = 2
    Cells(2, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeBottom).color = 0
    Cells(2, 6).Borders(xlEdgeBottom).weight = 2
    Cells(2, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeLeft).color = 0
    Cells(2, 6).Borders(xlEdgeLeft).weight = 2
    Cells(2, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(2, 6).Borders(xlEdgeRight).color = 0
    Cells(2, 6).Borders(xlEdgeRight).weight = 2
    Cells(3, 1) = "2"
    Cells(3, 1).Font.Name = "BIZ UDPゴシック"
    Cells(3, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeTop).color = 0
    Cells(3, 1).Borders(xlEdgeTop).weight = 2
    Cells(3, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeBottom).color = 0
    Cells(3, 1).Borders(xlEdgeBottom).weight = 2
    Cells(3, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeLeft).color = 0
    Cells(3, 1).Borders(xlEdgeLeft).weight = 2
    Cells(3, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 1).Borders(xlEdgeRight).color = 0
    Cells(3, 1).Borders(xlEdgeRight).weight = 2
    Cells(3, 2) = "数値"
    Cells(3, 2).Font.Name = "BIZ UDPゴシック"
    Cells(3, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeTop).color = 0
    Cells(3, 2).Borders(xlEdgeTop).weight = 2
    Cells(3, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeBottom).color = 0
    Cells(3, 2).Borders(xlEdgeBottom).weight = 2
    Cells(3, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeLeft).color = 0
    Cells(3, 2).Borders(xlEdgeLeft).weight = 2
    Cells(3, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 2).Borders(xlEdgeRight).color = 0
    Cells(3, 2).Borders(xlEdgeRight).weight = 2
    Cells(3, 3) = "有効桁数"
    Cells(3, 3).Font.Name = "BIZ UDPゴシック"
    Cells(3, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeTop).color = 0
    Cells(3, 3).Borders(xlEdgeTop).weight = 2
    Cells(3, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeBottom).color = 0
    Cells(3, 3).Borders(xlEdgeBottom).weight = 2
    Cells(3, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeLeft).color = 0
    Cells(3, 3).Borders(xlEdgeLeft).weight = 2
    Cells(3, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 3).Borders(xlEdgeRight).color = 0
    Cells(3, 3).Borders(xlEdgeRight).weight = 2
    Cells(3, 4) = "11"
    Cells(3, 4).Font.Name = "BIZ UDPゴシック"
    Cells(3, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeTop).color = 0
    Cells(3, 4).Borders(xlEdgeTop).weight = 2
    Cells(3, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeBottom).color = 0
    Cells(3, 4).Borders(xlEdgeBottom).weight = 2
    Cells(3, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeLeft).color = 0
    Cells(3, 4).Borders(xlEdgeLeft).weight = 2
    Cells(3, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 4).Borders(xlEdgeRight).color = 0
    Cells(3, 4).Borders(xlEdgeRight).weight = 2
    Cells(3, 5) = "18"
    Cells(3, 5).Font.Name = "BIZ UDPゴシック"
    Cells(3, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeTop).color = 0
    Cells(3, 5).Borders(xlEdgeTop).weight = 2
    Cells(3, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeBottom).color = 0
    Cells(3, 5).Borders(xlEdgeBottom).weight = 2
    Cells(3, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeLeft).color = 0
    Cells(3, 5).Borders(xlEdgeLeft).weight = 2
    Cells(3, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 5).Borders(xlEdgeRight).color = 0
    Cells(3, 5).Borders(xlEdgeRight).weight = 2
    Cells(3, 6) = "以下"
    Cells(3, 6).Font.Name = "BIZ UDPゴシック"
    Cells(3, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeTop).color = 0
    Cells(3, 6).Borders(xlEdgeTop).weight = 2
    Cells(3, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeBottom).color = 0
    Cells(3, 6).Borders(xlEdgeBottom).weight = 2
    Cells(3, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeLeft).color = 0
    Cells(3, 6).Borders(xlEdgeLeft).weight = 2
    Cells(3, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(3, 6).Borders(xlEdgeRight).color = 0
    Cells(3, 6).Borders(xlEdgeRight).weight = 2
    Cells(4, 1) = "3"
    Cells(4, 1).Font.Name = "BIZ UDPゴシック"
    Cells(4, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeTop).color = 0
    Cells(4, 1).Borders(xlEdgeTop).weight = 2
    Cells(4, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeBottom).color = 0
    Cells(4, 1).Borders(xlEdgeBottom).weight = 2
    Cells(4, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeLeft).color = 0
    Cells(4, 1).Borders(xlEdgeLeft).weight = 2
    Cells(4, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 1).Borders(xlEdgeRight).color = 0
    Cells(4, 1).Borders(xlEdgeRight).weight = 2
    Cells(4, 2) = "数値"
    Cells(4, 2).Font.Name = "BIZ UDPゴシック"
    Cells(4, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeTop).color = 0
    Cells(4, 2).Borders(xlEdgeTop).weight = 2
    Cells(4, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeBottom).color = 0
    Cells(4, 2).Borders(xlEdgeBottom).weight = 2
    Cells(4, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeLeft).color = 0
    Cells(4, 2).Borders(xlEdgeLeft).weight = 2
    Cells(4, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 2).Borders(xlEdgeRight).color = 0
    Cells(4, 2).Borders(xlEdgeRight).weight = 2
    Cells(4, 3) = "少数桁数"
    Cells(4, 3).Font.Name = "BIZ UDPゴシック"
    Cells(4, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeTop).color = 0
    Cells(4, 3).Borders(xlEdgeTop).weight = 2
    Cells(4, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeBottom).color = 0
    Cells(4, 3).Borders(xlEdgeBottom).weight = 2
    Cells(4, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeLeft).color = 0
    Cells(4, 3).Borders(xlEdgeLeft).weight = 2
    Cells(4, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 3).Borders(xlEdgeRight).color = 0
    Cells(4, 3).Borders(xlEdgeRight).weight = 2
    Cells(4, 4) = "12"
    Cells(4, 4).Font.Name = "BIZ UDPゴシック"
    Cells(4, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeTop).color = 0
    Cells(4, 4).Borders(xlEdgeTop).weight = 2
    Cells(4, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeBottom).color = 0
    Cells(4, 4).Borders(xlEdgeBottom).weight = 2
    Cells(4, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeLeft).color = 0
    Cells(4, 4).Borders(xlEdgeLeft).weight = 2
    Cells(4, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 4).Borders(xlEdgeRight).color = 0
    Cells(4, 4).Borders(xlEdgeRight).weight = 2
    Cells(4, 5) = "0"
    Cells(4, 5).Font.Name = "BIZ UDPゴシック"
    Cells(4, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeTop).color = 0
    Cells(4, 5).Borders(xlEdgeTop).weight = 2
    Cells(4, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeBottom).color = 0
    Cells(4, 5).Borders(xlEdgeBottom).weight = 2
    Cells(4, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeLeft).color = 0
    Cells(4, 5).Borders(xlEdgeLeft).weight = 2
    Cells(4, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 5).Borders(xlEdgeRight).color = 0
    Cells(4, 5).Borders(xlEdgeRight).weight = 2
    Cells(4, 6) = "以上"
    Cells(4, 6).Font.Name = "BIZ UDPゴシック"
    Cells(4, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeTop).color = 0
    Cells(4, 6).Borders(xlEdgeTop).weight = 2
    Cells(4, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeBottom).color = 0
    Cells(4, 6).Borders(xlEdgeBottom).weight = 2
    Cells(4, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeLeft).color = 0
    Cells(4, 6).Borders(xlEdgeLeft).weight = 2
    Cells(4, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(4, 6).Borders(xlEdgeRight).color = 0
    Cells(4, 6).Borders(xlEdgeRight).weight = 2
    Cells(5, 1) = "4"
    Cells(5, 1).Font.Name = "BIZ UDPゴシック"
    Cells(5, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeTop).color = 0
    Cells(5, 1).Borders(xlEdgeTop).weight = 2
    Cells(5, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeBottom).color = 0
    Cells(5, 1).Borders(xlEdgeBottom).weight = 2
    Cells(5, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeLeft).color = 0
    Cells(5, 1).Borders(xlEdgeLeft).weight = 2
    Cells(5, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 1).Borders(xlEdgeRight).color = 0
    Cells(5, 1).Borders(xlEdgeRight).weight = 2
    Cells(5, 2) = "数値"
    Cells(5, 2).Font.Name = "BIZ UDPゴシック"
    Cells(5, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeTop).color = 0
    Cells(5, 2).Borders(xlEdgeTop).weight = 2
    Cells(5, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeBottom).color = 0
    Cells(5, 2).Borders(xlEdgeBottom).weight = 2
    Cells(5, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeLeft).color = 0
    Cells(5, 2).Borders(xlEdgeLeft).weight = 2
    Cells(5, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 2).Borders(xlEdgeRight).color = 0
    Cells(5, 2).Borders(xlEdgeRight).weight = 2
    Cells(5, 3) = "少数桁数"
    Cells(5, 3).Font.Name = "BIZ UDPゴシック"
    Cells(5, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeTop).color = 0
    Cells(5, 3).Borders(xlEdgeTop).weight = 2
    Cells(5, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeBottom).color = 0
    Cells(5, 3).Borders(xlEdgeBottom).weight = 2
    Cells(5, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeLeft).color = 0
    Cells(5, 3).Borders(xlEdgeLeft).weight = 2
    Cells(5, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 3).Borders(xlEdgeRight).color = 0
    Cells(5, 3).Borders(xlEdgeRight).weight = 2
    Cells(5, 4) = "12"
    Cells(5, 4).Font.Name = "BIZ UDPゴシック"
    Cells(5, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeTop).color = 0
    Cells(5, 4).Borders(xlEdgeTop).weight = 2
    Cells(5, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeBottom).color = 0
    Cells(5, 4).Borders(xlEdgeBottom).weight = 2
    Cells(5, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeLeft).color = 0
    Cells(5, 4).Borders(xlEdgeLeft).weight = 2
    Cells(5, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 4).Borders(xlEdgeRight).color = 0
    Cells(5, 4).Borders(xlEdgeRight).weight = 2
    Cells(5, 5) = "18"
    Cells(5, 5).Font.Name = "BIZ UDPゴシック"
    Cells(5, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeTop).color = 0
    Cells(5, 5).Borders(xlEdgeTop).weight = 2
    Cells(5, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeBottom).color = 0
    Cells(5, 5).Borders(xlEdgeBottom).weight = 2
    Cells(5, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeLeft).color = 0
    Cells(5, 5).Borders(xlEdgeLeft).weight = 2
    Cells(5, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 5).Borders(xlEdgeRight).color = 0
    Cells(5, 5).Borders(xlEdgeRight).weight = 2
    Cells(5, 6) = "以下"
    Cells(5, 6).Font.Name = "BIZ UDPゴシック"
    Cells(5, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeTop).color = 0
    Cells(5, 6).Borders(xlEdgeTop).weight = 2
    Cells(5, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeBottom).color = 0
    Cells(5, 6).Borders(xlEdgeBottom).weight = 2
    Cells(5, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeLeft).color = 0
    Cells(5, 6).Borders(xlEdgeLeft).weight = 2
    Cells(5, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(5, 6).Borders(xlEdgeRight).color = 0
    Cells(5, 6).Borders(xlEdgeRight).weight = 2
    Cells(6, 1) = "5"
    Cells(6, 1).Font.Name = "BIZ UDPゴシック"
    Cells(6, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeTop).color = 0
    Cells(6, 1).Borders(xlEdgeTop).weight = 2
    Cells(6, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeBottom).color = 0
    Cells(6, 1).Borders(xlEdgeBottom).weight = 2
    Cells(6, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeLeft).color = 0
    Cells(6, 1).Borders(xlEdgeLeft).weight = 2
    Cells(6, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 1).Borders(xlEdgeRight).color = 0
    Cells(6, 1).Borders(xlEdgeRight).weight = 2
    Cells(6, 2) = "通貨"
    Cells(6, 2).Font.Name = "BIZ UDPゴシック"
    Cells(6, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeTop).color = 0
    Cells(6, 2).Borders(xlEdgeTop).weight = 2
    Cells(6, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeBottom).color = 0
    Cells(6, 2).Borders(xlEdgeBottom).weight = 2
    Cells(6, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeLeft).color = 0
    Cells(6, 2).Borders(xlEdgeLeft).weight = 2
    Cells(6, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 2).Borders(xlEdgeRight).color = 0
    Cells(6, 2).Borders(xlEdgeRight).weight = 2
    Cells(6, 3) = "有効桁数"
    Cells(6, 3).Font.Name = "BIZ UDPゴシック"
    Cells(6, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeTop).color = 0
    Cells(6, 3).Borders(xlEdgeTop).weight = 2
    Cells(6, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeBottom).color = 0
    Cells(6, 3).Borders(xlEdgeBottom).weight = 2
    Cells(6, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeLeft).color = 0
    Cells(6, 3).Borders(xlEdgeLeft).weight = 2
    Cells(6, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 3).Borders(xlEdgeRight).color = 0
    Cells(6, 3).Borders(xlEdgeRight).weight = 2
    Cells(6, 4) = "11"
    Cells(6, 4).Font.Name = "BIZ UDPゴシック"
    Cells(6, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeTop).color = 0
    Cells(6, 4).Borders(xlEdgeTop).weight = 2
    Cells(6, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeBottom).color = 0
    Cells(6, 4).Borders(xlEdgeBottom).weight = 2
    Cells(6, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeLeft).color = 0
    Cells(6, 4).Borders(xlEdgeLeft).weight = 2
    Cells(6, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 4).Borders(xlEdgeRight).color = 0
    Cells(6, 4).Borders(xlEdgeRight).weight = 2
    Cells(6, 5) = "1"
    Cells(6, 5).Font.Name = "BIZ UDPゴシック"
    Cells(6, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeTop).color = 0
    Cells(6, 5).Borders(xlEdgeTop).weight = 2
    Cells(6, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeBottom).color = 0
    Cells(6, 5).Borders(xlEdgeBottom).weight = 2
    Cells(6, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeLeft).color = 0
    Cells(6, 5).Borders(xlEdgeLeft).weight = 2
    Cells(6, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 5).Borders(xlEdgeRight).color = 0
    Cells(6, 5).Borders(xlEdgeRight).weight = 2
    Cells(6, 6) = "以上"
    Cells(6, 6).Font.Name = "BIZ UDPゴシック"
    Cells(6, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeTop).color = 0
    Cells(6, 6).Borders(xlEdgeTop).weight = 2
    Cells(6, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeBottom).color = 0
    Cells(6, 6).Borders(xlEdgeBottom).weight = 2
    Cells(6, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeLeft).color = 0
    Cells(6, 6).Borders(xlEdgeLeft).weight = 2
    Cells(6, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(6, 6).Borders(xlEdgeRight).color = 0
    Cells(6, 6).Borders(xlEdgeRight).weight = 2
    Cells(7, 1) = "6"
    Cells(7, 1).Font.Name = "BIZ UDPゴシック"
    Cells(7, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeTop).color = 0
    Cells(7, 1).Borders(xlEdgeTop).weight = 2
    Cells(7, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeBottom).color = 0
    Cells(7, 1).Borders(xlEdgeBottom).weight = 2
    Cells(7, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeLeft).color = 0
    Cells(7, 1).Borders(xlEdgeLeft).weight = 2
    Cells(7, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 1).Borders(xlEdgeRight).color = 0
    Cells(7, 1).Borders(xlEdgeRight).weight = 2
    Cells(7, 2) = "通貨"
    Cells(7, 2).Font.Name = "BIZ UDPゴシック"
    Cells(7, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeTop).color = 0
    Cells(7, 2).Borders(xlEdgeTop).weight = 2
    Cells(7, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeBottom).color = 0
    Cells(7, 2).Borders(xlEdgeBottom).weight = 2
    Cells(7, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeLeft).color = 0
    Cells(7, 2).Borders(xlEdgeLeft).weight = 2
    Cells(7, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 2).Borders(xlEdgeRight).color = 0
    Cells(7, 2).Borders(xlEdgeRight).weight = 2
    Cells(7, 3) = "有効桁数"
    Cells(7, 3).Font.Name = "BIZ UDPゴシック"
    Cells(7, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeTop).color = 0
    Cells(7, 3).Borders(xlEdgeTop).weight = 2
    Cells(7, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeBottom).color = 0
    Cells(7, 3).Borders(xlEdgeBottom).weight = 2
    Cells(7, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeLeft).color = 0
    Cells(7, 3).Borders(xlEdgeLeft).weight = 2
    Cells(7, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 3).Borders(xlEdgeRight).color = 0
    Cells(7, 3).Borders(xlEdgeRight).weight = 2
    Cells(7, 4) = "11"
    Cells(7, 4).Font.Name = "BIZ UDPゴシック"
    Cells(7, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeTop).color = 0
    Cells(7, 4).Borders(xlEdgeTop).weight = 2
    Cells(7, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeBottom).color = 0
    Cells(7, 4).Borders(xlEdgeBottom).weight = 2
    Cells(7, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeLeft).color = 0
    Cells(7, 4).Borders(xlEdgeLeft).weight = 2
    Cells(7, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 4).Borders(xlEdgeRight).color = 0
    Cells(7, 4).Borders(xlEdgeRight).weight = 2
    Cells(7, 5) = "18"
    Cells(7, 5).Font.Name = "BIZ UDPゴシック"
    Cells(7, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeTop).color = 0
    Cells(7, 5).Borders(xlEdgeTop).weight = 2
    Cells(7, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeBottom).color = 0
    Cells(7, 5).Borders(xlEdgeBottom).weight = 2
    Cells(7, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeLeft).color = 0
    Cells(7, 5).Borders(xlEdgeLeft).weight = 2
    Cells(7, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 5).Borders(xlEdgeRight).color = 0
    Cells(7, 5).Borders(xlEdgeRight).weight = 2
    Cells(7, 6) = "以下"
    Cells(7, 6).Font.Name = "BIZ UDPゴシック"
    Cells(7, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeTop).color = 0
    Cells(7, 6).Borders(xlEdgeTop).weight = 2
    Cells(7, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeBottom).color = 0
    Cells(7, 6).Borders(xlEdgeBottom).weight = 2
    Cells(7, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeLeft).color = 0
    Cells(7, 6).Borders(xlEdgeLeft).weight = 2
    Cells(7, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(7, 6).Borders(xlEdgeRight).color = 0
    Cells(7, 6).Borders(xlEdgeRight).weight = 2
    Cells(8, 1) = "7"
    Cells(8, 1).Font.Name = "BIZ UDPゴシック"
    Cells(8, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeTop).color = 0
    Cells(8, 1).Borders(xlEdgeTop).weight = 2
    Cells(8, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeBottom).color = 0
    Cells(8, 1).Borders(xlEdgeBottom).weight = 2
    Cells(8, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeLeft).color = 0
    Cells(8, 1).Borders(xlEdgeLeft).weight = 2
    Cells(8, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 1).Borders(xlEdgeRight).color = 0
    Cells(8, 1).Borders(xlEdgeRight).weight = 2
    Cells(8, 2) = "通貨"
    Cells(8, 2).Font.Name = "BIZ UDPゴシック"
    Cells(8, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeTop).color = 0
    Cells(8, 2).Borders(xlEdgeTop).weight = 2
    Cells(8, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeBottom).color = 0
    Cells(8, 2).Borders(xlEdgeBottom).weight = 2
    Cells(8, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeLeft).color = 0
    Cells(8, 2).Borders(xlEdgeLeft).weight = 2
    Cells(8, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 2).Borders(xlEdgeRight).color = 0
    Cells(8, 2).Borders(xlEdgeRight).weight = 2
    Cells(8, 3) = "少数桁数"
    Cells(8, 3).Font.Name = "BIZ UDPゴシック"
    Cells(8, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeTop).color = 0
    Cells(8, 3).Borders(xlEdgeTop).weight = 2
    Cells(8, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeBottom).color = 0
    Cells(8, 3).Borders(xlEdgeBottom).weight = 2
    Cells(8, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeLeft).color = 0
    Cells(8, 3).Borders(xlEdgeLeft).weight = 2
    Cells(8, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 3).Borders(xlEdgeRight).color = 0
    Cells(8, 3).Borders(xlEdgeRight).weight = 2
    Cells(8, 4) = "12"
    Cells(8, 4).Font.Name = "BIZ UDPゴシック"
    Cells(8, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeTop).color = 0
    Cells(8, 4).Borders(xlEdgeTop).weight = 2
    Cells(8, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeBottom).color = 0
    Cells(8, 4).Borders(xlEdgeBottom).weight = 2
    Cells(8, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeLeft).color = 0
    Cells(8, 4).Borders(xlEdgeLeft).weight = 2
    Cells(8, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 4).Borders(xlEdgeRight).color = 0
    Cells(8, 4).Borders(xlEdgeRight).weight = 2
    Cells(8, 5) = "0"
    Cells(8, 5).Font.Name = "BIZ UDPゴシック"
    Cells(8, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeTop).color = 0
    Cells(8, 5).Borders(xlEdgeTop).weight = 2
    Cells(8, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeBottom).color = 0
    Cells(8, 5).Borders(xlEdgeBottom).weight = 2
    Cells(8, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeLeft).color = 0
    Cells(8, 5).Borders(xlEdgeLeft).weight = 2
    Cells(8, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 5).Borders(xlEdgeRight).color = 0
    Cells(8, 5).Borders(xlEdgeRight).weight = 2
    Cells(8, 6) = "以上"
    Cells(8, 6).Font.Name = "BIZ UDPゴシック"
    Cells(8, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeTop).color = 0
    Cells(8, 6).Borders(xlEdgeTop).weight = 2
    Cells(8, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeBottom).color = 0
    Cells(8, 6).Borders(xlEdgeBottom).weight = 2
    Cells(8, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeLeft).color = 0
    Cells(8, 6).Borders(xlEdgeLeft).weight = 2
    Cells(8, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(8, 6).Borders(xlEdgeRight).color = 0
    Cells(8, 6).Borders(xlEdgeRight).weight = 2
    Cells(9, 1) = "8"
    Cells(9, 1).Font.Name = "BIZ UDPゴシック"
    Cells(9, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeTop).color = 0
    Cells(9, 1).Borders(xlEdgeTop).weight = 2
    Cells(9, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeBottom).color = 0
    Cells(9, 1).Borders(xlEdgeBottom).weight = 2
    Cells(9, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeLeft).color = 0
    Cells(9, 1).Borders(xlEdgeLeft).weight = 2
    Cells(9, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 1).Borders(xlEdgeRight).color = 0
    Cells(9, 1).Borders(xlEdgeRight).weight = 2
    Cells(9, 2) = "通貨"
    Cells(9, 2).Font.Name = "BIZ UDPゴシック"
    Cells(9, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeTop).color = 0
    Cells(9, 2).Borders(xlEdgeTop).weight = 2
    Cells(9, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeBottom).color = 0
    Cells(9, 2).Borders(xlEdgeBottom).weight = 2
    Cells(9, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeLeft).color = 0
    Cells(9, 2).Borders(xlEdgeLeft).weight = 2
    Cells(9, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 2).Borders(xlEdgeRight).color = 0
    Cells(9, 2).Borders(xlEdgeRight).weight = 2
    Cells(9, 3) = "少数桁数"
    Cells(9, 3).Font.Name = "BIZ UDPゴシック"
    Cells(9, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeTop).color = 0
    Cells(9, 3).Borders(xlEdgeTop).weight = 2
    Cells(9, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeBottom).color = 0
    Cells(9, 3).Borders(xlEdgeBottom).weight = 2
    Cells(9, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeLeft).color = 0
    Cells(9, 3).Borders(xlEdgeLeft).weight = 2
    Cells(9, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 3).Borders(xlEdgeRight).color = 0
    Cells(9, 3).Borders(xlEdgeRight).weight = 2
    Cells(9, 4) = "12"
    Cells(9, 4).Font.Name = "BIZ UDPゴシック"
    Cells(9, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeTop).color = 0
    Cells(9, 4).Borders(xlEdgeTop).weight = 2
    Cells(9, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeBottom).color = 0
    Cells(9, 4).Borders(xlEdgeBottom).weight = 2
    Cells(9, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeLeft).color = 0
    Cells(9, 4).Borders(xlEdgeLeft).weight = 2
    Cells(9, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 4).Borders(xlEdgeRight).color = 0
    Cells(9, 4).Borders(xlEdgeRight).weight = 2
    Cells(9, 5) = "18"
    Cells(9, 5).Font.Name = "BIZ UDPゴシック"
    Cells(9, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeTop).color = 0
    Cells(9, 5).Borders(xlEdgeTop).weight = 2
    Cells(9, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeBottom).color = 0
    Cells(9, 5).Borders(xlEdgeBottom).weight = 2
    Cells(9, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeLeft).color = 0
    Cells(9, 5).Borders(xlEdgeLeft).weight = 2
    Cells(9, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 5).Borders(xlEdgeRight).color = 0
    Cells(9, 5).Borders(xlEdgeRight).weight = 2
    Cells(9, 6) = "以下"
    Cells(9, 6).Font.Name = "BIZ UDPゴシック"
    Cells(9, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeTop).color = 0
    Cells(9, 6).Borders(xlEdgeTop).weight = 2
    Cells(9, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeBottom).color = 0
    Cells(9, 6).Borders(xlEdgeBottom).weight = 2
    Cells(9, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeLeft).color = 0
    Cells(9, 6).Borders(xlEdgeLeft).weight = 2
    Cells(9, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(9, 6).Borders(xlEdgeRight).color = 0
    Cells(9, 6).Borders(xlEdgeRight).weight = 2
    Cells(10, 1) = "9"
    Cells(10, 1).Font.Name = "BIZ UDPゴシック"
    Cells(10, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 1).Borders(xlEdgeTop).color = 0
    Cells(10, 1).Borders(xlEdgeTop).weight = 2
    Cells(10, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 1).Borders(xlEdgeBottom).color = 0
    Cells(10, 1).Borders(xlEdgeBottom).weight = 2
    Cells(10, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(10, 1).Borders(xlEdgeLeft).color = 0
    Cells(10, 1).Borders(xlEdgeLeft).weight = 2
    Cells(10, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(10, 1).Borders(xlEdgeRight).color = 0
    Cells(10, 1).Borders(xlEdgeRight).weight = 2
    Cells(10, 2) = "(数式)数値"
    Cells(10, 2).Font.Name = "BIZ UDPゴシック"
    Cells(10, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 2).Borders(xlEdgeTop).color = 0
    Cells(10, 2).Borders(xlEdgeTop).weight = 2
    Cells(10, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 2).Borders(xlEdgeBottom).color = 0
    Cells(10, 2).Borders(xlEdgeBottom).weight = 2
    Cells(10, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(10, 2).Borders(xlEdgeLeft).color = 0
    Cells(10, 2).Borders(xlEdgeLeft).weight = 2
    Cells(10, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(10, 2).Borders(xlEdgeRight).color = 0
    Cells(10, 2).Borders(xlEdgeRight).weight = 2
    Cells(10, 3) = "少数桁数"
    Cells(10, 3).Font.Name = "BIZ UDPゴシック"
    Cells(10, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeTop).color = 0
    Cells(10, 3).Borders(xlEdgeTop).weight = 2
    Cells(10, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeBottom).color = 0
    Cells(10, 3).Borders(xlEdgeBottom).weight = 2
    Cells(10, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeLeft).color = 0
    Cells(10, 3).Borders(xlEdgeLeft).weight = 2
    Cells(10, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(10, 3).Borders(xlEdgeRight).color = 0
    Cells(10, 3).Borders(xlEdgeRight).weight = 2
    Cells(10, 4) = "12"
    Cells(10, 4).Font.Name = "BIZ UDPゴシック"
    Cells(10, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeTop).color = 0
    Cells(10, 4).Borders(xlEdgeTop).weight = 2
    Cells(10, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeBottom).color = 0
    Cells(10, 4).Borders(xlEdgeBottom).weight = 2
    Cells(10, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeLeft).color = 0
    Cells(10, 4).Borders(xlEdgeLeft).weight = 2
    Cells(10, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(10, 4).Borders(xlEdgeRight).color = 0
    Cells(10, 4).Borders(xlEdgeRight).weight = 2
    Cells(10, 5) = "0"
    Cells(10, 5).Font.Name = "BIZ UDPゴシック"
    Cells(10, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeTop).color = 0
    Cells(10, 5).Borders(xlEdgeTop).weight = 2
    Cells(10, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeBottom).color = 0
    Cells(10, 5).Borders(xlEdgeBottom).weight = 2
    Cells(10, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeLeft).color = 0
    Cells(10, 5).Borders(xlEdgeLeft).weight = 2
    Cells(10, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(10, 5).Borders(xlEdgeRight).color = 0
    Cells(10, 5).Borders(xlEdgeRight).weight = 2
    Cells(10, 6) = "以上"
    Cells(10, 6).Font.Name = "BIZ UDPゴシック"
    Cells(10, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeTop).color = 0
    Cells(10, 6).Borders(xlEdgeTop).weight = 2
    Cells(10, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeBottom).color = 0
    Cells(10, 6).Borders(xlEdgeBottom).weight = 2
    Cells(10, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeLeft).color = 0
    Cells(10, 6).Borders(xlEdgeLeft).weight = 2
    Cells(10, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(10, 6).Borders(xlEdgeRight).color = 0
    Cells(10, 6).Borders(xlEdgeRight).weight = 2
    Cells(11, 1) = "10"
    Cells(11, 1).Font.Name = "BIZ UDPゴシック"
    Cells(11, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 1).Borders(xlEdgeTop).color = 0
    Cells(11, 1).Borders(xlEdgeTop).weight = 2
    Cells(11, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 1).Borders(xlEdgeBottom).color = 0
    Cells(11, 1).Borders(xlEdgeBottom).weight = 2
    Cells(11, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(11, 1).Borders(xlEdgeLeft).color = 0
    Cells(11, 1).Borders(xlEdgeLeft).weight = 2
    Cells(11, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(11, 1).Borders(xlEdgeRight).color = 0
    Cells(11, 1).Borders(xlEdgeRight).weight = 2
end Function
Function revival1()
    Cells(11, 2) = "(数式)数値"
    Cells(11, 2).Font.Name = "BIZ UDPゴシック"
    Cells(11, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 2).Borders(xlEdgeTop).color = 0
    Cells(11, 2).Borders(xlEdgeTop).weight = 2
    Cells(11, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 2).Borders(xlEdgeBottom).color = 0
    Cells(11, 2).Borders(xlEdgeBottom).weight = 2
    Cells(11, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(11, 2).Borders(xlEdgeLeft).color = 0
    Cells(11, 2).Borders(xlEdgeLeft).weight = 2
    Cells(11, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(11, 2).Borders(xlEdgeRight).color = 0
    Cells(11, 2).Borders(xlEdgeRight).weight = 2
    Cells(11, 3) = "少数桁数"
    Cells(11, 3).Font.Name = "BIZ UDPゴシック"
    Cells(11, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 3).Borders(xlEdgeTop).color = 0
    Cells(11, 3).Borders(xlEdgeTop).weight = 2
    Cells(11, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 3).Borders(xlEdgeBottom).color = 0
    Cells(11, 3).Borders(xlEdgeBottom).weight = 2
    Cells(11, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(11, 3).Borders(xlEdgeLeft).color = 0
    Cells(11, 3).Borders(xlEdgeLeft).weight = 2
    Cells(11, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(11, 3).Borders(xlEdgeRight).color = 0
    Cells(11, 3).Borders(xlEdgeRight).weight = 2
    Cells(11, 4) = "12"
    Cells(11, 4).Font.Name = "BIZ UDPゴシック"
    Cells(11, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 4).Borders(xlEdgeTop).color = 0
    Cells(11, 4).Borders(xlEdgeTop).weight = 2
    Cells(11, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 4).Borders(xlEdgeBottom).color = 0
    Cells(11, 4).Borders(xlEdgeBottom).weight = 2
    Cells(11, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(11, 4).Borders(xlEdgeLeft).color = 0
    Cells(11, 4).Borders(xlEdgeLeft).weight = 2
    Cells(11, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(11, 4).Borders(xlEdgeRight).color = 0
    Cells(11, 4).Borders(xlEdgeRight).weight = 2
    Cells(11, 5) = "18"
    Cells(11, 5).Font.Name = "BIZ UDPゴシック"
    Cells(11, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 5).Borders(xlEdgeTop).color = 0
    Cells(11, 5).Borders(xlEdgeTop).weight = 2
    Cells(11, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 5).Borders(xlEdgeBottom).color = 0
    Cells(11, 5).Borders(xlEdgeBottom).weight = 2
    Cells(11, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(11, 5).Borders(xlEdgeLeft).color = 0
    Cells(11, 5).Borders(xlEdgeLeft).weight = 2
    Cells(11, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(11, 5).Borders(xlEdgeRight).color = 0
    Cells(11, 5).Borders(xlEdgeRight).weight = 2
    Cells(11, 6) = "以下"
    Cells(11, 6).Font.Name = "BIZ UDPゴシック"
    Cells(11, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(11, 6).Borders(xlEdgeTop).color = 0
    Cells(11, 6).Borders(xlEdgeTop).weight = 2
    Cells(11, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(11, 6).Borders(xlEdgeBottom).color = 0
    Cells(11, 6).Borders(xlEdgeBottom).weight = 2
    Cells(11, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(11, 6).Borders(xlEdgeLeft).color = 0
    Cells(11, 6).Borders(xlEdgeLeft).weight = 2
    Cells(11, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(11, 6).Borders(xlEdgeRight).color = 0
    Cells(11, 6).Borders(xlEdgeRight).weight = 2
    Cells(12, 1) = "11"
    Cells(12, 1).Font.Name = "BIZ UDPゴシック"
    Cells(12, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeTop).color = 0
    Cells(12, 1).Borders(xlEdgeTop).weight = 2
    Cells(12, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeBottom).color = 0
    Cells(12, 1).Borders(xlEdgeBottom).weight = 2
    Cells(12, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeLeft).color = 0
    Cells(12, 1).Borders(xlEdgeLeft).weight = 2
    Cells(12, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 1).Borders(xlEdgeRight).color = 0
    Cells(12, 1).Borders(xlEdgeRight).weight = 2
    Cells(12, 2) = "(数式)通貨"
    Cells(12, 2).Font.Name = "BIZ UDPゴシック"
    Cells(12, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeTop).color = 0
    Cells(12, 2).Borders(xlEdgeTop).weight = 2
    Cells(12, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeBottom).color = 0
    Cells(12, 2).Borders(xlEdgeBottom).weight = 2
    Cells(12, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeLeft).color = 0
    Cells(12, 2).Borders(xlEdgeLeft).weight = 2
    Cells(12, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 2).Borders(xlEdgeRight).color = 0
    Cells(12, 2).Borders(xlEdgeRight).weight = 2
    Cells(12, 3) = "少数桁数"
    Cells(12, 3).Font.Name = "BIZ UDPゴシック"
    Cells(12, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeTop).color = 0
    Cells(12, 3).Borders(xlEdgeTop).weight = 2
    Cells(12, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeBottom).color = 0
    Cells(12, 3).Borders(xlEdgeBottom).weight = 2
    Cells(12, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeLeft).color = 0
    Cells(12, 3).Borders(xlEdgeLeft).weight = 2
    Cells(12, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 3).Borders(xlEdgeRight).color = 0
    Cells(12, 3).Borders(xlEdgeRight).weight = 2
    Cells(12, 4) = "12"
    Cells(12, 4).Font.Name = "BIZ UDPゴシック"
    Cells(12, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeTop).color = 0
    Cells(12, 4).Borders(xlEdgeTop).weight = 2
    Cells(12, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeBottom).color = 0
    Cells(12, 4).Borders(xlEdgeBottom).weight = 2
    Cells(12, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeLeft).color = 0
    Cells(12, 4).Borders(xlEdgeLeft).weight = 2
    Cells(12, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 4).Borders(xlEdgeRight).color = 0
    Cells(12, 4).Borders(xlEdgeRight).weight = 2
    Cells(12, 5) = "0"
    Cells(12, 5).Font.Name = "BIZ UDPゴシック"
    Cells(12, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeTop).color = 0
    Cells(12, 5).Borders(xlEdgeTop).weight = 2
    Cells(12, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeBottom).color = 0
    Cells(12, 5).Borders(xlEdgeBottom).weight = 2
    Cells(12, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeLeft).color = 0
    Cells(12, 5).Borders(xlEdgeLeft).weight = 2
    Cells(12, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 5).Borders(xlEdgeRight).color = 0
    Cells(12, 5).Borders(xlEdgeRight).weight = 2
    Cells(12, 6) = "以上"
    Cells(12, 6).Font.Name = "BIZ UDPゴシック"
    Cells(12, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeTop).color = 0
    Cells(12, 6).Borders(xlEdgeTop).weight = 2
    Cells(12, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeBottom).color = 0
    Cells(12, 6).Borders(xlEdgeBottom).weight = 2
    Cells(12, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeLeft).color = 0
    Cells(12, 6).Borders(xlEdgeLeft).weight = 2
    Cells(12, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(12, 6).Borders(xlEdgeRight).color = 0
    Cells(12, 6).Borders(xlEdgeRight).weight = 2
    Cells(13, 1) = "12"
    Cells(13, 1).Font.Name = "BIZ UDPゴシック"
    Cells(13, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 1).Borders(xlEdgeTop).color = 0
    Cells(13, 1).Borders(xlEdgeTop).weight = 2
    Cells(13, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 1).Borders(xlEdgeBottom).color = 0
    Cells(13, 1).Borders(xlEdgeBottom).weight = 2
    Cells(13, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 1).Borders(xlEdgeLeft).color = 0
    Cells(13, 1).Borders(xlEdgeLeft).weight = 2
    Cells(13, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 1).Borders(xlEdgeRight).color = 0
    Cells(13, 1).Borders(xlEdgeRight).weight = 2
    Cells(13, 2) = "(数式)通貨"
    Cells(13, 2).Font.Name = "BIZ UDPゴシック"
    Cells(13, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 2).Borders(xlEdgeTop).color = 0
    Cells(13, 2).Borders(xlEdgeTop).weight = 2
    Cells(13, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 2).Borders(xlEdgeBottom).color = 0
    Cells(13, 2).Borders(xlEdgeBottom).weight = 2
    Cells(13, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 2).Borders(xlEdgeLeft).color = 0
    Cells(13, 2).Borders(xlEdgeLeft).weight = 2
    Cells(13, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 2).Borders(xlEdgeRight).color = 0
    Cells(13, 2).Borders(xlEdgeRight).weight = 2
    Cells(13, 3) = "少数桁数"
    Cells(13, 3).Font.Name = "BIZ UDPゴシック"
    Cells(13, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 3).Borders(xlEdgeTop).color = 0
    Cells(13, 3).Borders(xlEdgeTop).weight = 2
    Cells(13, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 3).Borders(xlEdgeBottom).color = 0
    Cells(13, 3).Borders(xlEdgeBottom).weight = 2
    Cells(13, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 3).Borders(xlEdgeLeft).color = 0
    Cells(13, 3).Borders(xlEdgeLeft).weight = 2
    Cells(13, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 3).Borders(xlEdgeRight).color = 0
    Cells(13, 3).Borders(xlEdgeRight).weight = 2
    Cells(13, 4) = "12"
    Cells(13, 4).Font.Name = "BIZ UDPゴシック"
    Cells(13, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeTop).color = 0
    Cells(13, 4).Borders(xlEdgeTop).weight = 2
    Cells(13, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeBottom).color = 0
    Cells(13, 4).Borders(xlEdgeBottom).weight = 2
    Cells(13, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeLeft).color = 0
    Cells(13, 4).Borders(xlEdgeLeft).weight = 2
    Cells(13, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 4).Borders(xlEdgeRight).color = 0
    Cells(13, 4).Borders(xlEdgeRight).weight = 2
    Cells(13, 5) = "18"
    Cells(13, 5).Font.Name = "BIZ UDPゴシック"
    Cells(13, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 5).Borders(xlEdgeTop).color = 0
    Cells(13, 5).Borders(xlEdgeTop).weight = 2
    Cells(13, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 5).Borders(xlEdgeBottom).color = 0
    Cells(13, 5).Borders(xlEdgeBottom).weight = 2
    Cells(13, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 5).Borders(xlEdgeLeft).color = 0
    Cells(13, 5).Borders(xlEdgeLeft).weight = 2
    Cells(13, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 5).Borders(xlEdgeRight).color = 0
    Cells(13, 5).Borders(xlEdgeRight).weight = 2
    Cells(13, 6) = "以下"
    Cells(13, 6).Font.Name = "BIZ UDPゴシック"
    Cells(13, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(13, 6).Borders(xlEdgeTop).color = 0
    Cells(13, 6).Borders(xlEdgeTop).weight = 2
    Cells(13, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(13, 6).Borders(xlEdgeBottom).color = 0
    Cells(13, 6).Borders(xlEdgeBottom).weight = 2
    Cells(13, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(13, 6).Borders(xlEdgeLeft).color = 0
    Cells(13, 6).Borders(xlEdgeLeft).weight = 2
    Cells(13, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(13, 6).Borders(xlEdgeRight).color = 0
    Cells(13, 6).Borders(xlEdgeRight).weight = 2
    Cells(14, 1) = "13"
    Cells(14, 1).Font.Name = "BIZ UDPゴシック"
    Cells(14, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 1).Borders(xlEdgeTop).color = 0
    Cells(14, 1).Borders(xlEdgeTop).weight = 2
    Cells(14, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 1).Borders(xlEdgeBottom).color = 0
    Cells(14, 1).Borders(xlEdgeBottom).weight = 2
    Cells(14, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 1).Borders(xlEdgeLeft).color = 0
    Cells(14, 1).Borders(xlEdgeLeft).weight = 2
    Cells(14, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 1).Borders(xlEdgeRight).color = 0
    Cells(14, 1).Borders(xlEdgeRight).weight = 2
    Cells(14, 2) = "テキストエリア (リッチ)"
    Cells(14, 2).Font.Name = "BIZ UDPゴシック"
    Cells(14, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 2).Borders(xlEdgeTop).color = 0
    Cells(14, 2).Borders(xlEdgeTop).weight = 2
    Cells(14, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 2).Borders(xlEdgeBottom).color = 0
    Cells(14, 2).Borders(xlEdgeBottom).weight = 2
    Cells(14, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 2).Borders(xlEdgeLeft).color = 0
    Cells(14, 2).Borders(xlEdgeLeft).weight = 2
    Cells(14, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 2).Borders(xlEdgeRight).color = 0
    Cells(14, 2).Borders(xlEdgeRight).weight = 2
    Cells(14, 3) = "表示行数"
    Cells(14, 3).Font.Name = "BIZ UDPゴシック"
    Cells(14, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 3).Borders(xlEdgeTop).color = 0
    Cells(14, 3).Borders(xlEdgeTop).weight = 2
    Cells(14, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 3).Borders(xlEdgeBottom).color = 0
    Cells(14, 3).Borders(xlEdgeBottom).weight = 2
    Cells(14, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 3).Borders(xlEdgeLeft).color = 0
    Cells(14, 3).Borders(xlEdgeLeft).weight = 2
    Cells(14, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 3).Borders(xlEdgeRight).color = 0
    Cells(14, 3).Borders(xlEdgeRight).weight = 2
    Cells(14, 4) = "13"
    Cells(14, 4).Font.Name = "BIZ UDPゴシック"
    Cells(14, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeTop).color = 0
    Cells(14, 4).Borders(xlEdgeTop).weight = 2
    Cells(14, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeBottom).color = 0
    Cells(14, 4).Borders(xlEdgeBottom).weight = 2
    Cells(14, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeLeft).color = 0
    Cells(14, 4).Borders(xlEdgeLeft).weight = 2
    Cells(14, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 4).Borders(xlEdgeRight).color = 0
    Cells(14, 4).Borders(xlEdgeRight).weight = 2
    Cells(14, 5) = "10"
    Cells(14, 5).Font.Name = "BIZ UDPゴシック"
    Cells(14, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 5).Borders(xlEdgeTop).color = 0
    Cells(14, 5).Borders(xlEdgeTop).weight = 2
    Cells(14, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 5).Borders(xlEdgeBottom).color = 0
    Cells(14, 5).Borders(xlEdgeBottom).weight = 2
    Cells(14, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 5).Borders(xlEdgeLeft).color = 0
    Cells(14, 5).Borders(xlEdgeLeft).weight = 2
    Cells(14, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 5).Borders(xlEdgeRight).color = 0
    Cells(14, 5).Borders(xlEdgeRight).weight = 2
    Cells(14, 6) = "以上"
    Cells(14, 6).Font.Name = "BIZ UDPゴシック"
    Cells(14, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(14, 6).Borders(xlEdgeTop).color = 0
    Cells(14, 6).Borders(xlEdgeTop).weight = 2
    Cells(14, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(14, 6).Borders(xlEdgeBottom).color = 0
    Cells(14, 6).Borders(xlEdgeBottom).weight = 2
    Cells(14, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(14, 6).Borders(xlEdgeLeft).color = 0
    Cells(14, 6).Borders(xlEdgeLeft).weight = 2
    Cells(14, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(14, 6).Borders(xlEdgeRight).color = 0
    Cells(14, 6).Borders(xlEdgeRight).weight = 2
    Cells(15, 1) = "14"
    Cells(15, 1).Font.Name = "BIZ UDPゴシック"
    Cells(15, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 1).Borders(xlEdgeTop).color = 0
    Cells(15, 1).Borders(xlEdgeTop).weight = 2
    Cells(15, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 1).Borders(xlEdgeBottom).color = 0
    Cells(15, 1).Borders(xlEdgeBottom).weight = 2
    Cells(15, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(15, 1).Borders(xlEdgeLeft).color = 0
    Cells(15, 1).Borders(xlEdgeLeft).weight = 2
    Cells(15, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(15, 1).Borders(xlEdgeRight).color = 0
    Cells(15, 1).Borders(xlEdgeRight).weight = 2
    Cells(15, 2) = "ロングテキストエリア"
    Cells(15, 2).Font.Name = "BIZ UDPゴシック"
    Cells(15, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 2).Borders(xlEdgeTop).color = 0
    Cells(15, 2).Borders(xlEdgeTop).weight = 2
    Cells(15, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 2).Borders(xlEdgeBottom).color = 0
    Cells(15, 2).Borders(xlEdgeBottom).weight = 2
    Cells(15, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(15, 2).Borders(xlEdgeLeft).color = 0
    Cells(15, 2).Borders(xlEdgeLeft).weight = 2
    Cells(15, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(15, 2).Borders(xlEdgeRight).color = 0
    Cells(15, 2).Borders(xlEdgeRight).weight = 2
    Cells(15, 3) = "表示行数"
    Cells(15, 3).Font.Name = "BIZ UDPゴシック"
    Cells(15, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 3).Borders(xlEdgeTop).color = 0
    Cells(15, 3).Borders(xlEdgeTop).weight = 2
    Cells(15, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 3).Borders(xlEdgeBottom).color = 0
    Cells(15, 3).Borders(xlEdgeBottom).weight = 2
    Cells(15, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(15, 3).Borders(xlEdgeLeft).color = 0
    Cells(15, 3).Borders(xlEdgeLeft).weight = 2
    Cells(15, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(15, 3).Borders(xlEdgeRight).color = 0
    Cells(15, 3).Borders(xlEdgeRight).weight = 2
    Cells(15, 4) = "13"
    Cells(15, 4).Font.Name = "BIZ UDPゴシック"
    Cells(15, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 4).Borders(xlEdgeTop).color = 0
    Cells(15, 4).Borders(xlEdgeTop).weight = 2
    Cells(15, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 4).Borders(xlEdgeBottom).color = 0
    Cells(15, 4).Borders(xlEdgeBottom).weight = 2
    Cells(15, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(15, 4).Borders(xlEdgeLeft).color = 0
    Cells(15, 4).Borders(xlEdgeLeft).weight = 2
    Cells(15, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(15, 4).Borders(xlEdgeRight).color = 0
    Cells(15, 4).Borders(xlEdgeRight).weight = 2
    Cells(15, 5) = "2"
    Cells(15, 5).Font.Name = "BIZ UDPゴシック"
    Cells(15, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 5).Borders(xlEdgeTop).color = 0
    Cells(15, 5).Borders(xlEdgeTop).weight = 2
    Cells(15, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 5).Borders(xlEdgeBottom).color = 0
    Cells(15, 5).Borders(xlEdgeBottom).weight = 2
    Cells(15, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(15, 5).Borders(xlEdgeLeft).color = 0
    Cells(15, 5).Borders(xlEdgeLeft).weight = 2
    Cells(15, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(15, 5).Borders(xlEdgeRight).color = 0
    Cells(15, 5).Borders(xlEdgeRight).weight = 2
    Cells(15, 6) = "以上"
    Cells(15, 6).Font.Name = "BIZ UDPゴシック"
    Cells(15, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(15, 6).Borders(xlEdgeTop).color = 0
    Cells(15, 6).Borders(xlEdgeTop).weight = 2
    Cells(15, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(15, 6).Borders(xlEdgeBottom).color = 0
    Cells(15, 6).Borders(xlEdgeBottom).weight = 2
    Cells(15, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(15, 6).Borders(xlEdgeLeft).color = 0
    Cells(15, 6).Borders(xlEdgeLeft).weight = 2
    Cells(15, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(15, 6).Borders(xlEdgeRight).color = 0
    Cells(15, 6).Borders(xlEdgeRight).weight = 2
    Cells(16, 1) = "15"
    Cells(16, 1).Font.Name = "BIZ UDPゴシック"
    Cells(16, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 1).Borders(xlEdgeTop).color = 0
    Cells(16, 1).Borders(xlEdgeTop).weight = 2
    Cells(16, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 1).Borders(xlEdgeBottom).color = 0
    Cells(16, 1).Borders(xlEdgeBottom).weight = 2
    Cells(16, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(16, 1).Borders(xlEdgeLeft).color = 0
    Cells(16, 1).Borders(xlEdgeLeft).weight = 2
    Cells(16, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(16, 1).Borders(xlEdgeRight).color = 0
    Cells(16, 1).Borders(xlEdgeRight).weight = 2
end Function
Function revival2()
    Cells(16, 2) = "選択リスト (複数選択)"
    Cells(16, 2).Font.Name = "BIZ UDPゴシック"
    Cells(16, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 2).Borders(xlEdgeTop).color = 0
    Cells(16, 2).Borders(xlEdgeTop).weight = 2
    Cells(16, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 2).Borders(xlEdgeBottom).color = 0
    Cells(16, 2).Borders(xlEdgeBottom).weight = 2
    Cells(16, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(16, 2).Borders(xlEdgeLeft).color = 0
    Cells(16, 2).Borders(xlEdgeLeft).weight = 2
    Cells(16, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(16, 2).Borders(xlEdgeRight).color = 0
    Cells(16, 2).Borders(xlEdgeRight).weight = 2
    Cells(16, 3) = "表示行数"
    Cells(16, 3).Font.Name = "BIZ UDPゴシック"
    Cells(16, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 3).Borders(xlEdgeTop).color = 0
    Cells(16, 3).Borders(xlEdgeTop).weight = 2
    Cells(16, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 3).Borders(xlEdgeBottom).color = 0
    Cells(16, 3).Borders(xlEdgeBottom).weight = 2
    Cells(16, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(16, 3).Borders(xlEdgeLeft).color = 0
    Cells(16, 3).Borders(xlEdgeLeft).weight = 2
    Cells(16, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(16, 3).Borders(xlEdgeRight).color = 0
    Cells(16, 3).Borders(xlEdgeRight).weight = 2
    Cells(16, 4) = "13"
    Cells(16, 4).Font.Name = "BIZ UDPゴシック"
    Cells(16, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 4).Borders(xlEdgeTop).color = 0
    Cells(16, 4).Borders(xlEdgeTop).weight = 2
    Cells(16, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 4).Borders(xlEdgeBottom).color = 0
    Cells(16, 4).Borders(xlEdgeBottom).weight = 2
    Cells(16, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(16, 4).Borders(xlEdgeLeft).color = 0
    Cells(16, 4).Borders(xlEdgeLeft).weight = 2
    Cells(16, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(16, 4).Borders(xlEdgeRight).color = 0
    Cells(16, 4).Borders(xlEdgeRight).weight = 2
    Cells(16, 5) = "3"
    Cells(16, 5).Font.Name = "BIZ UDPゴシック"
    Cells(16, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 5).Borders(xlEdgeTop).color = 0
    Cells(16, 5).Borders(xlEdgeTop).weight = 2
    Cells(16, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 5).Borders(xlEdgeBottom).color = 0
    Cells(16, 5).Borders(xlEdgeBottom).weight = 2
    Cells(16, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(16, 5).Borders(xlEdgeLeft).color = 0
    Cells(16, 5).Borders(xlEdgeLeft).weight = 2
    Cells(16, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(16, 5).Borders(xlEdgeRight).color = 0
    Cells(16, 5).Borders(xlEdgeRight).weight = 2
    Cells(16, 6) = "以上"
    Cells(16, 6).Font.Name = "BIZ UDPゴシック"
    Cells(16, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(16, 6).Borders(xlEdgeTop).color = 0
    Cells(16, 6).Borders(xlEdgeTop).weight = 2
    Cells(16, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(16, 6).Borders(xlEdgeBottom).color = 0
    Cells(16, 6).Borders(xlEdgeBottom).weight = 2
    Cells(16, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(16, 6).Borders(xlEdgeLeft).color = 0
    Cells(16, 6).Borders(xlEdgeLeft).weight = 2
    Cells(16, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(16, 6).Borders(xlEdgeRight).color = 0
    Cells(16, 6).Borders(xlEdgeRight).weight = 2
    Cells(17, 1) = "16"
    Cells(17, 1).Font.Name = "BIZ UDPゴシック"
    Cells(17, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 1).Borders(xlEdgeTop).color = 0
    Cells(17, 1).Borders(xlEdgeTop).weight = 2
    Cells(17, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 1).Borders(xlEdgeBottom).color = 0
    Cells(17, 1).Borders(xlEdgeBottom).weight = 2
    Cells(17, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 1).Borders(xlEdgeLeft).color = 0
    Cells(17, 1).Borders(xlEdgeLeft).weight = 2
    Cells(17, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 1).Borders(xlEdgeRight).color = 0
    Cells(17, 1).Borders(xlEdgeRight).weight = 2
    Cells(17, 2) = "テキストエリア (リッチ)"
    Cells(17, 2).Font.Name = "BIZ UDPゴシック"
    Cells(17, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 2).Borders(xlEdgeTop).color = 0
    Cells(17, 2).Borders(xlEdgeTop).weight = 2
    Cells(17, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 2).Borders(xlEdgeBottom).color = 0
    Cells(17, 2).Borders(xlEdgeBottom).weight = 2
    Cells(17, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 2).Borders(xlEdgeLeft).color = 0
    Cells(17, 2).Borders(xlEdgeLeft).weight = 2
    Cells(17, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 2).Borders(xlEdgeRight).color = 0
    Cells(17, 2).Borders(xlEdgeRight).weight = 2
    Cells(17, 3) = "文字数"
    Cells(17, 3).Font.Name = "BIZ UDPゴシック"
    Cells(17, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 3).Borders(xlEdgeTop).color = 0
    Cells(17, 3).Borders(xlEdgeTop).weight = 2
    Cells(17, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 3).Borders(xlEdgeBottom).color = 0
    Cells(17, 3).Borders(xlEdgeBottom).weight = 2
    Cells(17, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 3).Borders(xlEdgeLeft).color = 0
    Cells(17, 3).Borders(xlEdgeLeft).weight = 2
    Cells(17, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 3).Borders(xlEdgeRight).color = 0
    Cells(17, 3).Borders(xlEdgeRight).weight = 2
    Cells(17, 4) = "10"
    Cells(17, 4).Font.Name = "BIZ UDPゴシック"
    Cells(17, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeTop).color = 0
    Cells(17, 4).Borders(xlEdgeTop).weight = 2
    Cells(17, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeBottom).color = 0
    Cells(17, 4).Borders(xlEdgeBottom).weight = 2
    Cells(17, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeLeft).color = 0
    Cells(17, 4).Borders(xlEdgeLeft).weight = 2
    Cells(17, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 4).Borders(xlEdgeRight).color = 0
    Cells(17, 4).Borders(xlEdgeRight).weight = 2
    Cells(17, 5) = "256"
    Cells(17, 5).Font.Name = "BIZ UDPゴシック"
    Cells(17, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 5).Borders(xlEdgeTop).color = 0
    Cells(17, 5).Borders(xlEdgeTop).weight = 2
    Cells(17, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 5).Borders(xlEdgeBottom).color = 0
    Cells(17, 5).Borders(xlEdgeBottom).weight = 2
    Cells(17, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 5).Borders(xlEdgeLeft).color = 0
    Cells(17, 5).Borders(xlEdgeLeft).weight = 2
    Cells(17, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 5).Borders(xlEdgeRight).color = 0
    Cells(17, 5).Borders(xlEdgeRight).weight = 2
    Cells(17, 6) = "以上"
    Cells(17, 6).Font.Name = "BIZ UDPゴシック"
    Cells(17, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(17, 6).Borders(xlEdgeTop).color = 0
    Cells(17, 6).Borders(xlEdgeTop).weight = 2
    Cells(17, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(17, 6).Borders(xlEdgeBottom).color = 0
    Cells(17, 6).Borders(xlEdgeBottom).weight = 2
    Cells(17, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(17, 6).Borders(xlEdgeLeft).color = 0
    Cells(17, 6).Borders(xlEdgeLeft).weight = 2
    Cells(17, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(17, 6).Borders(xlEdgeRight).color = 0
    Cells(17, 6).Borders(xlEdgeRight).weight = 2
    Cells(18, 1) = "17"
    Cells(18, 1).Font.Name = "BIZ UDPゴシック"
    Cells(18, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 1).Borders(xlEdgeTop).color = 0
    Cells(18, 1).Borders(xlEdgeTop).weight = 2
    Cells(18, 1).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 1).Borders(xlEdgeBottom).color = 0
    Cells(18, 1).Borders(xlEdgeBottom).weight = 2
    Cells(18, 1).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 1).Borders(xlEdgeLeft).color = 0
    Cells(18, 1).Borders(xlEdgeLeft).weight = 2
    Cells(18, 1).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 1).Borders(xlEdgeRight).color = 0
    Cells(18, 1).Borders(xlEdgeRight).weight = 2
    Cells(18, 2) = "ロングテキストエリア"
    Cells(18, 2).Font.Name = "BIZ UDPゴシック"
    Cells(18, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 2).Borders(xlEdgeTop).color = 0
    Cells(18, 2).Borders(xlEdgeTop).weight = 2
    Cells(18, 2).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 2).Borders(xlEdgeBottom).color = 0
    Cells(18, 2).Borders(xlEdgeBottom).weight = 2
    Cells(18, 2).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 2).Borders(xlEdgeLeft).color = 0
    Cells(18, 2).Borders(xlEdgeLeft).weight = 2
    Cells(18, 2).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 2).Borders(xlEdgeRight).color = 0
    Cells(18, 2).Borders(xlEdgeRight).weight = 2
    Cells(18, 3) = "文字数"
    Cells(18, 3).Font.Name = "BIZ UDPゴシック"
    Cells(18, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 3).Borders(xlEdgeTop).color = 0
    Cells(18, 3).Borders(xlEdgeTop).weight = 2
    Cells(18, 3).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 3).Borders(xlEdgeBottom).color = 0
    Cells(18, 3).Borders(xlEdgeBottom).weight = 2
    Cells(18, 3).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 3).Borders(xlEdgeLeft).color = 0
    Cells(18, 3).Borders(xlEdgeLeft).weight = 2
    Cells(18, 3).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 3).Borders(xlEdgeRight).color = 0
    Cells(18, 3).Borders(xlEdgeRight).weight = 2
    Cells(18, 4) = "10"
    Cells(18, 4).Font.Name = "BIZ UDPゴシック"
    Cells(18, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeTop).color = 0
    Cells(18, 4).Borders(xlEdgeTop).weight = 2
    Cells(18, 4).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeBottom).color = 0
    Cells(18, 4).Borders(xlEdgeBottom).weight = 2
    Cells(18, 4).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeLeft).color = 0
    Cells(18, 4).Borders(xlEdgeLeft).weight = 2
    Cells(18, 4).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 4).Borders(xlEdgeRight).color = 0
    Cells(18, 4).Borders(xlEdgeRight).weight = 2
    Cells(18, 5) = "256"
    Cells(18, 5).Font.Name = "BIZ UDPゴシック"
    Cells(18, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 5).Borders(xlEdgeTop).color = 0
    Cells(18, 5).Borders(xlEdgeTop).weight = 2
    Cells(18, 5).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 5).Borders(xlEdgeBottom).color = 0
    Cells(18, 5).Borders(xlEdgeBottom).weight = 2
    Cells(18, 5).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 5).Borders(xlEdgeLeft).color = 0
    Cells(18, 5).Borders(xlEdgeLeft).weight = 2
    Cells(18, 5).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 5).Borders(xlEdgeRight).color = 0
    Cells(18, 5).Borders(xlEdgeRight).weight = 2
    Cells(18, 6) = "以上"
    Cells(18, 6).Font.Name = "BIZ UDPゴシック"
    Cells(18, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(18, 6).Borders(xlEdgeTop).color = 0
    Cells(18, 6).Borders(xlEdgeTop).weight = 2
    Cells(18, 6).Borders(xlEdgeBottom).LineStyle = 1
    Cells(18, 6).Borders(xlEdgeBottom).color = 0
    Cells(18, 6).Borders(xlEdgeBottom).weight = 2
    Cells(18, 6).Borders(xlEdgeLeft).LineStyle = 1
    Cells(18, 6).Borders(xlEdgeLeft).color = 0
    Cells(18, 6).Borders(xlEdgeLeft).weight = 2
    Cells(18, 6).Borders(xlEdgeRight).LineStyle = 1
    Cells(18, 6).Borders(xlEdgeRight).color = 0
    Cells(18, 6).Borders(xlEdgeRight).weight = 2
    Cells(19, 1) = "18"
    Cells(19, 1).Font.Name = "BIZ UDPゴシック"
    Cells(19, 1).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 1).Borders(xlEdgeTop).color = 0
    Cells(19, 1).Borders(xlEdgeTop).weight = 2
    Cells(19, 2) = "チェックボックス"
    Cells(19, 2).Font.Name = "BIZ UDPゴシック"
    Cells(19, 2).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 2).Borders(xlEdgeTop).color = 0
    Cells(19, 2).Borders(xlEdgeTop).weight = 2
    Cells(19, 3) = "初期値"
    Cells(19, 3).Font.Name = "BIZ UDPゴシック"
    Cells(19, 3).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 3).Borders(xlEdgeTop).color = 0
    Cells(19, 3).Borders(xlEdgeTop).weight = 2
    Cells(19, 4) = "32"
    Cells(19, 4).Font.Name = "BIZ UDPゴシック"
    Cells(19, 4).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 4).Borders(xlEdgeTop).color = 0
    Cells(19, 4).Borders(xlEdgeTop).weight = 2
    Cells(19, 5).Font.Name = "BIZ UDPゴシック"
    Cells(19, 5).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 5).Borders(xlEdgeTop).color = 0
    Cells(19, 5).Borders(xlEdgeTop).weight = 2
    Cells(19, 6) = "必須"
    Cells(19, 6).Font.Name = "BIZ UDPゴシック"
    Cells(19, 6).Borders(xlEdgeTop).LineStyle = 1
    Cells(19, 6).Borders(xlEdgeTop).color = 0
    Cells(19, 6).Borders(xlEdgeTop).weight = 2
    Cells(20, 1) = "19"
    Cells(20, 1).Font.Name = "BIZ UDPゴシック"
    Cells(20, 2) = "-"
    Cells(20, 2).Font.Name = "BIZ UDPゴシック"
    Cells(20, 3) = "ラベル名"
    Cells(20, 3).Font.Name = "BIZ UDPゴシック"
    Cells(20, 4) = "3"
    Cells(20, 4).Font.Name = "BIZ UDPゴシック"
    Cells(20, 5) = "改行文字"
    Cells(20, 5).Font.Name = "BIZ UDPゴシック"
    Cells(20, 6) = "含まない"
    Cells(20, 6).Font.Name = "BIZ UDPゴシック"
    Rows(1).RowHeight = 19.5
    Rows(2).RowHeight = 19.5
    Rows(3).RowHeight = 19.5
    Rows(4).RowHeight = 19.5
    Rows(5).RowHeight = 19.5
    Rows(6).RowHeight = 19.5
    Rows(7).RowHeight = 19.5
    Rows(8).RowHeight = 19.5
    Rows(9).RowHeight = 19.5
    Rows(10).RowHeight = 19.5
    Rows(11).RowHeight = 19.5
    Rows(12).RowHeight = 19.5
    Rows(13).RowHeight = 19.5
    Rows(14).RowHeight = 19.5
    Rows(15).RowHeight = 19.5
    Rows(16).RowHeight = 19.5
    Rows(17).RowHeight = 19.5
    Rows(18).RowHeight = 19.5
    Rows(19).RowHeight = 19.5
    Rows(20).RowHeight = 19.5
    Columns(1).ColumnWidth = 6
    Columns(2).ColumnWidth = 26.38
    Columns(3).ColumnWidth = 8.38
    Columns(4).ColumnWidth = 8.38
    Columns(5).ColumnWidth = 8.38
    Columns(6).ColumnWidth = 8.38
    Dim onShape As Object
End Function
Sub revival()
    Worksheets.Add After:=Worksheets(Worksheets.Count)
    CALL revival0()
    CALL revival1()
    CALL revival2()
    Worksheets(1).select
end sub