Attribute VB_Name = "setup"
Function revival0()
    ActiveWindow.DisplayGridlines = False
    ActiveWindow.Zoom = 100
    ActiveSheet.Name = "実行機能一覧"
    Cells(5, 2) = "フォルダ作成"
    Cells(5, 2).Font.Name = "游ゴシック"
    Cells(5, 2).Font.Bold = True
    Cells(5, 3).Font.Name = "游ゴシック"
    Cells(5, 4).Font.Name = "游ゴシック"
    Cells(5, 5).Font.Name = "游ゴシック"
    Cells(5, 6).Font.Name = "游ゴシック"
    Cells(5, 7).Font.Name = "游ゴシック"
    Cells(5, 8).Font.Name = "游ゴシック"
    Cells(5, 9).Font.Name = "游ゴシック"
    Cells(5, 10).Font.Name = "游ゴシック"
    Cells(5, 11).Font.Name = "游ゴシック"
    Cells(6, 2) = "以下の構成でフォルダを作成します。"
    Cells(6, 2).Font.Name = "游ゴシック"
    Cells(6, 2).HorizontalAlignment = -4131
    Cells(6, 2).IndentLevel = 1
    Cells(6, 3).Font.Name = "游ゴシック"
    Cells(6, 4).Font.Name = "游ゴシック"
    Cells(6, 5).Font.Name = "游ゴシック"
    Cells(6, 6).Font.Name = "游ゴシック"
    Cells(6, 7).Font.Name = "游ゴシック"
    Cells(6, 8).Font.Name = "游ゴシック"
    Cells(6, 9).Font.Name = "游ゴシック"
    Cells(6, 10).Font.Name = "游ゴシック"
    Cells(6, 11).Font.Name = "游ゴシック"
    Cells(7, 2) = "ルートフォルダは[オブジェクト]シートに記載したオブジェクト名に依存します。"
    Cells(7, 2).Font.Name = "游ゴシック"
    Cells(7, 2).HorizontalAlignment = -4131
    Cells(7, 2).IndentLevel = 1
    Cells(7, 3).Font.Name = "游ゴシック"
    Cells(7, 4).Font.Name = "游ゴシック"
    Cells(7, 5).Font.Name = "游ゴシック"
    Cells(7, 6).Font.Name = "游ゴシック"
    Cells(7, 7).Font.Name = "游ゴシック"
    Cells(7, 8).Font.Name = "游ゴシック"
    Cells(7, 9).Font.Name = "游ゴシック"
    Cells(7, 10).Font.Name = "游ゴシック"
    Cells(7, 11).Font.Name = "游ゴシック"
    Cells(8, 2) = "[オブジェクト名]"
    Cells(8, 2).Font.Name = "游ゴシック"
    Cells(8, 3).Font.Name = "游ゴシック"
    Cells(8, 4).Font.Name = "游ゴシック"
    Cells(8, 5).Font.Name = "游ゴシック"
    Cells(8, 6).Font.Name = "游ゴシック"
    Cells(8, 7).Font.Name = "游ゴシック"
    Cells(8, 8).Font.Name = "游ゴシック"
    Cells(8, 9).Font.Name = "游ゴシック"
    Cells(8, 10).Font.Name = "游ゴシック"
    Cells(8, 11).Font.Name = "游ゴシック"
    Cells(9, 2) = "  ├─compactLayouts"
    Cells(9, 2).Font.Name = "游ゴシック"
    Cells(9, 3).Font.Name = "游ゴシック"
    Cells(9, 4).Font.Name = "游ゴシック"
    Cells(9, 5).Font.Name = "游ゴシック"
    Cells(9, 6).Font.Name = "游ゴシック"
    Cells(9, 7).Font.Name = "游ゴシック"
    Cells(9, 8).Font.Name = "游ゴシック"
    Cells(9, 9).Font.Name = "游ゴシック"
    Cells(9, 10).Font.Name = "游ゴシック"
    Cells(9, 11).Font.Name = "游ゴシック"
    Cells(10, 2) = "  ├─fields"
    Cells(10, 2).Font.Name = "游ゴシック"
    Cells(10, 3).Font.Name = "游ゴシック"
    Cells(10, 4).Font.Name = "游ゴシック"
    Cells(10, 5).Font.Name = "游ゴシック"
    Cells(10, 6).Font.Name = "游ゴシック"
    Cells(10, 7).Font.Name = "游ゴシック"
    Cells(10, 8).Font.Name = "游ゴシック"
    Cells(10, 9).Font.Name = "游ゴシック"
    Cells(10, 10).Font.Name = "游ゴシック"
    Cells(10, 11).Font.Name = "游ゴシック"
    Cells(11, 2) = "  ├─listViews"
    Cells(11, 2).Font.Name = "游ゴシック"
end Function
Function revival1()
    Cells(11, 3).Font.Name = "游ゴシック"
    Cells(11, 4).Font.Name = "游ゴシック"
    Cells(11, 5).Font.Name = "游ゴシック"
    Cells(11, 6).Font.Name = "游ゴシック"
    Cells(11, 7).Font.Name = "游ゴシック"
    Cells(11, 8).Font.Name = "游ゴシック"
    Cells(11, 9).Font.Name = "游ゴシック"
    Cells(11, 10).Font.Name = "游ゴシック"
    Cells(11, 11).Font.Name = "游ゴシック"
    Cells(12, 2) = "  ├─validationRules"
    Cells(12, 2).Font.Name = "游ゴシック"
    Cells(12, 3).Font.Name = "游ゴシック"
    Cells(12, 4).Font.Name = "游ゴシック"
    Cells(12, 5).Font.Name = "游ゴシック"
    Cells(12, 6).Font.Name = "游ゴシック"
    Cells(12, 7).Font.Name = "游ゴシック"
    Cells(12, 8).Font.Name = "游ゴシック"
    Cells(12, 9).Font.Name = "游ゴシック"
    Cells(12, 10).Font.Name = "游ゴシック"
    Cells(12, 11).Font.Name = "游ゴシック"
    Cells(13, 2) = "  └─recordTypes"
    Cells(13, 2).Font.Name = "游ゴシック"
    Cells(13, 3).Font.Name = "游ゴシック"
    Cells(13, 4).Font.Name = "游ゴシック"
    Cells(13, 5).Font.Name = "游ゴシック"
    Cells(13, 6).Font.Name = "游ゴシック"
    Cells(13, 7).Font.Name = "游ゴシック"
    Cells(13, 8).Font.Name = "游ゴシック"
    Cells(13, 9).Font.Name = "游ゴシック"
    Cells(13, 10).Font.Name = "游ゴシック"
    Cells(13, 11).Font.Name = "游ゴシック"
    Cells(14, 2).Font.Name = "游ゴシック"
end Function
Function revival2()
    Cells(14, 3).Font.Name = "游ゴシック"
    Cells(14, 4).Font.Name = "游ゴシック"
    Cells(14, 5).Font.Name = "游ゴシック"
    Cells(14, 6).Font.Name = "游ゴシック"
    Cells(14, 7).Font.Name = "游ゴシック"
    Cells(14, 8).Font.Name = "游ゴシック"
    Cells(14, 9).Font.Name = "游ゴシック"
    Cells(14, 10).Font.Name = "游ゴシック"
    Cells(14, 11).Font.Name = "游ゴシック"
    Cells(15, 2).Font.Name = "游ゴシック"
    Cells(15, 3).Font.Name = "游ゴシック"
    Cells(15, 4).Font.Name = "游ゴシック"
    Cells(15, 5).Font.Name = "游ゴシック"
    Cells(15, 6).Font.Name = "游ゴシック"
    Cells(15, 7).Font.Name = "游ゴシック"
    Cells(15, 8).Font.Name = "游ゴシック"
    Cells(15, 9).Font.Name = "游ゴシック"
    Cells(15, 10).Font.Name = "游ゴシック"
    Cells(15, 11).Font.Name = "游ゴシック"
    Cells(16, 2) = "オブジェクトmetaDataファイル作成"
    Cells(16, 2).Font.Name = "游ゴシック"
    Cells(16, 2).Font.Bold = True
    Cells(16, 3).Font.Name = "游ゴシック"
    Cells(16, 4).Font.Name = "游ゴシック"
    Cells(16, 5).Font.Name = "游ゴシック"
    Cells(16, 6).Font.Name = "游ゴシック"
    Cells(16, 7).Font.Name = "游ゴシック"
    Cells(16, 8).Font.Name = "游ゴシック"
    Cells(16, 9).Font.Name = "游ゴシック"
    Cells(16, 10).Font.Name = "游ゴシック"
    Cells(16, 11).Font.Name = "游ゴシック"
    Cells(17, 2) = "ルートフォルダ配下に置くオブジェクトのmetaDataファイルを作成します。"
    Cells(17, 2).Font.Name = "游ゴシック"
    Cells(17, 2).HorizontalAlignment = -4131
    Cells(17, 2).IndentLevel = 1
end Function
Function revival3()
    Cells(17, 3).Font.Name = "游ゴシック"
    Cells(17, 4).Font.Name = "游ゴシック"
    Cells(17, 5).Font.Name = "游ゴシック"
    Cells(17, 6).Font.Name = "游ゴシック"
    Cells(17, 7).Font.Name = "游ゴシック"
    Cells(17, 8).Font.Name = "游ゴシック"
    Cells(17, 9).Font.Name = "游ゴシック"
    Cells(17, 10).Font.Name = "游ゴシック"
    Cells(17, 11).Font.Name = "游ゴシック"
    Cells(18, 2) = "ファイルの内容は[オブジェクト]シートに記載した内容に依存します。"
    Cells(18, 2).Font.Name = "游ゴシック"
    Cells(18, 2).HorizontalAlignment = -4131
    Cells(18, 2).IndentLevel = 1
    Cells(18, 3).Font.Name = "游ゴシック"
    Cells(18, 4).Font.Name = "游ゴシック"
    Cells(18, 5).Font.Name = "游ゴシック"
    Cells(18, 6).Font.Name = "游ゴシック"
    Cells(18, 7).Font.Name = "游ゴシック"
    Cells(18, 8).Font.Name = "游ゴシック"
    Cells(18, 9).Font.Name = "游ゴシック"
    Cells(18, 10).Font.Name = "游ゴシック"
    Cells(18, 11) = "ここまで完了"
    Cells(18, 11).Font.Name = "游ゴシック"
    Cells(18, 11).Font.Color = 255
    Cells(18, 11).Font.Bold = True
    Cells(19, 2) = "タブ設定のmetaDataファイルもtabフォルダ内に作成します。"
    Cells(19, 2).Font.Name = "游ゴシック"
    Cells(19, 2).HorizontalAlignment = -4131
    Cells(19, 2).IndentLevel = 1
    Cells(19, 3).Font.Name = "游ゴシック"
    Cells(19, 4).Font.Name = "游ゴシック"
    Cells(19, 5).Font.Name = "游ゴシック"
    Cells(19, 6).Font.Name = "游ゴシック"
    Cells(19, 7).Font.Name = "游ゴシック"
    Cells(19, 8).Font.Name = "游ゴシック"
    Cells(19, 9).Font.Name = "游ゴシック"
    Cells(19, 10).Font.Name = "游ゴシック"
    Cells(19, 11) = "次回、カスタム項目のところからやろう"
    Cells(19, 11).Font.Name = "游ゴシック"
    Cells(20, 2).Font.Name = "游ゴシック"
end Function
Function revival4()
    Cells(20, 3).Font.Name = "游ゴシック"
    Cells(20, 4).Font.Name = "游ゴシック"
    Cells(20, 5).Font.Name = "游ゴシック"
    Cells(20, 6).Font.Name = "游ゴシック"
    Cells(20, 7).Font.Name = "游ゴシック"
    Cells(20, 8).Font.Name = "游ゴシック"
    Cells(20, 9).Font.Name = "游ゴシック"
    Cells(20, 10).Font.Name = "游ゴシック"
    Cells(20, 11).Font.Name = "游ゴシック"
    Cells(21, 2) = "カスタム項目metaDataファイル作成"
    Cells(21, 2).Font.Name = "游ゴシック"
    Cells(21, 2).Font.Bold = True
    Cells(21, 3).Font.Name = "游ゴシック"
    Cells(21, 4).Font.Name = "游ゴシック"
    Cells(21, 5).Font.Name = "游ゴシック"
    Cells(21, 6).Font.Name = "游ゴシック"
    Cells(21, 7).Font.Name = "游ゴシック"
    Cells(21, 8).Font.Name = "游ゴシック"
    Cells(21, 9).Font.Name = "游ゴシック"
    Cells(21, 10).Font.Name = "游ゴシック"
    Cells(21, 11).Font.Name = "游ゴシック"
    Cells(22, 2) = "fieldsフォルダ配下に置くカスタム項目のmetaDataファイルを作成します。"
    Cells(22, 2).Font.Name = "游ゴシック"
    Cells(22, 2).HorizontalAlignment = -4131
    Cells(22, 2).IndentLevel = 1
    Cells(22, 3).Font.Name = "游ゴシック"
    Cells(22, 4).Font.Name = "游ゴシック"
    Cells(22, 5).Font.Name = "游ゴシック"
    Cells(22, 6).Font.Name = "游ゴシック"
    Cells(22, 7).Font.Name = "游ゴシック"
    Cells(22, 8).Font.Name = "游ゴシック"
    Cells(22, 9).Font.Name = "游ゴシック"
    Cells(22, 10).Font.Name = "游ゴシック"
    Cells(22, 11).Font.Name = "游ゴシック"
    Cells(22, 11).Font.Color = 255
    Cells(22, 11).Font.Bold = True
    Cells(23, 2) = "ファイルの内容は[項目]シートに記載した内容に依存します。"
    Cells(23, 2).Font.Name = "游ゴシック"
    Cells(23, 2).HorizontalAlignment = -4131
    Cells(23, 2).IndentLevel = 1
end Function
Function revival5()
    Cells(23, 3).Font.Name = "游ゴシック"
    Cells(23, 4).Font.Name = "游ゴシック"
    Cells(23, 5).Font.Name = "游ゴシック"
    Cells(23, 6).Font.Name = "游ゴシック"
    Cells(23, 7).Font.Name = "游ゴシック"
    Cells(23, 8).Font.Name = "游ゴシック"
    Cells(23, 9).Font.Name = "游ゴシック"
    Cells(23, 10).Font.Name = "游ゴシック"
    Cells(23, 11).Font.Name = "游ゴシック"
    Cells(24, 2) = "↑課題がありつつも8割程度は完成。"
    Cells(24, 2).Font.Name = "游ゴシック"
    Cells(24, 3).Font.Name = "游ゴシック"
    Cells(24, 4).Font.Name = "游ゴシック"
    Cells(24, 5).Font.Name = "游ゴシック"
    Cells(24, 6).Font.Name = "游ゴシック"
    Cells(24, 7).Font.Name = "游ゴシック"
    Cells(24, 8).Font.Name = "游ゴシック"
    Cells(24, 9).Font.Name = "游ゴシック"
    Cells(24, 10).Font.Name = "游ゴシック"
    Cells(24, 11).Font.Name = "游ゴシック"
    Cells(25, 2).Font.Name = "游ゴシック"
    Cells(25, 3).Font.Name = "游ゴシック"
    Cells(25, 4).Font.Name = "游ゴシック"
    Cells(25, 5).Font.Name = "游ゴシック"
    Cells(25, 6).Font.Name = "游ゴシック"
    Cells(25, 7).Font.Name = "游ゴシック"
    Cells(25, 8).Font.Name = "游ゴシック"
    Cells(25, 9).Font.Name = "游ゴシック"
    Cells(25, 10).Font.Name = "游ゴシック"
    Cells(25, 11).Font.Name = "游ゴシック"
    Cells(26, 2) = "プロファイルmetaDataファイル作成"
    Cells(26, 2).Font.Name = "游ゴシック"
    Cells(26, 2).Font.Bold = True
end Function
Function revival6()
    Cells(26, 3).Font.Name = "游ゴシック"
    Cells(26, 4).Font.Name = "游ゴシック"
    Cells(26, 5).Font.Name = "游ゴシック"
    Cells(26, 6).Font.Name = "游ゴシック"
    Cells(26, 7).Font.Name = "游ゴシック"
    Cells(26, 8).Font.Name = "游ゴシック"
    Cells(26, 9).Font.Name = "游ゴシック"
    Cells(26, 10).Font.Name = "游ゴシック"
    Cells(26, 11).Font.Name = "游ゴシック"
    Cells(27, 2) = "プロファイルごとに各項目の参照・編集権限とタブの設定について"
    Cells(27, 2).Font.Name = "游ゴシック"
    Cells(27, 2).HorizontalAlignment = -4131
    Cells(27, 2).IndentLevel = 1
    Cells(27, 3).Font.Name = "游ゴシック"
    Cells(27, 4).Font.Name = "游ゴシック"
    Cells(27, 5).Font.Name = "游ゴシック"
    Cells(27, 6).Font.Name = "游ゴシック"
    Cells(27, 7).Font.Name = "游ゴシック"
    Cells(27, 8).Font.Name = "游ゴシック"
    Cells(27, 9).Font.Name = "游ゴシック"
    Cells(27, 10).Font.Name = "游ゴシック"
    Cells(27, 11).Font.Name = "游ゴシック"
    Cells(28, 2) = "記載したプロファイルのmetaDataファイルを作成します。"
    Cells(28, 2).Font.Name = "游ゴシック"
    Cells(28, 2).HorizontalAlignment = -4131
    Cells(28, 2).IndentLevel = 1
    Cells(28, 3).Font.Name = "游ゴシック"
    Cells(28, 4).Font.Name = "游ゴシック"
    Cells(28, 5).Font.Name = "游ゴシック"
    Cells(28, 6).Font.Name = "游ゴシック"
    Cells(28, 7).Font.Name = "游ゴシック"
    Cells(28, 8).Font.Name = "游ゴシック"
    Cells(28, 9).Font.Name = "游ゴシック"
    Cells(28, 10).Font.Name = "游ゴシック"
    Cells(28, 11).Font.Name = "游ゴシック"
    Cells(29, 2).Font.Name = "游ゴシック"
end Function
Function revival7()
    Cells(29, 3).Font.Name = "游ゴシック"
    Cells(29, 4).Font.Name = "游ゴシック"
    Cells(29, 5).Font.Name = "游ゴシック"
    Cells(29, 6).Font.Name = "游ゴシック"
    Cells(29, 7).Font.Name = "游ゴシック"
    Cells(29, 8).Font.Name = "游ゴシック"
    Cells(29, 9).Font.Name = "游ゴシック"
    Cells(29, 10).Font.Name = "游ゴシック"
    Cells(29, 11).Font.Name = "游ゴシック"
    Cells(30, 2) = "ページレイアウトmetaDataファイル作成"
    Cells(30, 2).Font.Name = "游ゴシック"
    Cells(30, 2).Font.Bold = True
    Cells(30, 3).Font.Name = "游ゴシック"
    Cells(30, 4).Font.Name = "游ゴシック"
    Cells(30, 5).Font.Name = "游ゴシック"
    Cells(30, 6).Font.Name = "游ゴシック"
    Cells(30, 7).Font.Name = "游ゴシック"
    Cells(30, 8).Font.Name = "游ゴシック"
    Cells(30, 9).Font.Name = "游ゴシック"
    Cells(30, 10).Font.Name = "游ゴシック"
    Cells(30, 11).Font.Name = "游ゴシック"
    Cells(31, 2).Font.Name = "游ゴシック"
    Cells(31, 3).Font.Name = "游ゴシック"
    Cells(31, 4).Font.Name = "游ゴシック"
    Cells(31, 5).Font.Name = "游ゴシック"
    Cells(31, 6).Font.Name = "游ゴシック"
    Cells(31, 7).Font.Name = "游ゴシック"
    Cells(31, 8).Font.Name = "游ゴシック"
    Cells(31, 9).Font.Name = "游ゴシック"
    Cells(31, 10).Font.Name = "游ゴシック"
    Cells(31, 11).Font.Name = "游ゴシック"
    Cells(32, 2).Font.Name = "游ゴシック"
end Function
Function revival8()
    Cells(32, 3).Font.Name = "游ゴシック"
    Cells(32, 4).Font.Name = "游ゴシック"
    Cells(32, 5).Font.Name = "游ゴシック"
    Cells(32, 6).Font.Name = "游ゴシック"
    Cells(32, 7).Font.Name = "游ゴシック"
    Cells(32, 8).Font.Name = "游ゴシック"
    Cells(32, 9).Font.Name = "游ゴシック"
    Cells(32, 10).Font.Name = "游ゴシック"
    Cells(32, 11).Font.Name = "游ゴシック"
    Cells(33, 2).Font.Name = "游ゴシック"
    Cells(33, 3).Font.Name = "游ゴシック"
    Cells(33, 4).Font.Name = "游ゴシック"
    Cells(33, 5).Font.Name = "游ゴシック"
    Cells(33, 6).Font.Name = "游ゴシック"
    Cells(33, 7).Font.Name = "游ゴシック"
    Cells(33, 8).Font.Name = "游ゴシック"
    Cells(33, 9).Font.Name = "游ゴシック"
    Cells(33, 10).Font.Name = "游ゴシック"
    Cells(33, 11).Font.Name = "游ゴシック"
    Cells(34, 2) = "データローダ用CSVファイル出力"
    Cells(34, 2).Font.Name = "游ゴシック"
    Cells(34, 2).Font.Bold = True
    Cells(34, 3).Font.Name = "游ゴシック"
    Cells(34, 4).Font.Name = "游ゴシック"
    Cells(34, 5).Font.Name = "游ゴシック"
    Cells(34, 6).Font.Name = "游ゴシック"
    Cells(34, 7).Font.Name = "游ゴシック"
    Cells(34, 8).Font.Name = "游ゴシック"
    Cells(34, 9).Font.Name = "游ゴシック"
    Cells(34, 10).Font.Name = "游ゴシック"
    Cells(34, 11).Font.Name = "游ゴシック"
    Cells(35, 2) = "データローダ用を使用したINSERT処理として使えるcsv形式の"
    Cells(35, 2).Font.Name = "游ゴシック"
    Cells(35, 2).HorizontalAlignment = -4131
    Cells(35, 2).IndentLevel = 1
end Function
Function revival9()
    Cells(35, 3).Font.Name = "游ゴシック"
    Cells(35, 4).Font.Name = "游ゴシック"
    Cells(35, 5).Font.Name = "游ゴシック"
    Cells(35, 6).Font.Name = "游ゴシック"
    Cells(35, 7).Font.Name = "游ゴシック"
    Cells(35, 8).Font.Name = "游ゴシック"
    Cells(35, 9).Font.Name = "游ゴシック"
    Cells(35, 10).Font.Name = "游ゴシック"
    Cells(35, 11).Font.Name = "游ゴシック"
    Cells(36, 2) = "フォーマットを出力します。"
    Cells(36, 2).Font.Name = "游ゴシック"
    Cells(36, 2).HorizontalAlignment = -4131
    Cells(36, 2).IndentLevel = 1
    Cells(36, 3).Font.Name = "游ゴシック"
    Cells(36, 4).Font.Name = "游ゴシック"
    Cells(36, 5).Font.Name = "游ゴシック"
    Cells(36, 6).Font.Name = "游ゴシック"
    Cells(36, 7).Font.Name = "游ゴシック"
    Cells(36, 8).Font.Name = "游ゴシック"
    Cells(36, 9).Font.Name = "游ゴシック"
    Cells(36, 10).Font.Name = "游ゴシック"
    Cells(36, 11).Font.Name = "游ゴシック"
    Cells(37, 2).Font.Name = "游ゴシック"
    Cells(37, 3).Font.Name = "游ゴシック"
    Cells(37, 4).Font.Name = "游ゴシック"
    Cells(37, 5).Font.Name = "游ゴシック"
    Cells(37, 6).Font.Name = "游ゴシック"
    Cells(37, 7).Font.Name = "游ゴシック"
    Cells(37, 8).Font.Name = "游ゴシック"
    Cells(37, 9).Font.Name = "游ゴシック"
    Cells(37, 10).Font.Name = "游ゴシック"
    Cells(37, 11).Font.Name = "游ゴシック"
    Cells(38, 2).Font.Name = "游ゴシック"
end Function
Function revival10()
    Cells(38, 3).Font.Name = "游ゴシック"
    Cells(38, 4).Font.Name = "游ゴシック"
    Cells(38, 5).Font.Name = "游ゴシック"
    Cells(38, 6).Font.Name = "游ゴシック"
    Cells(38, 7).Font.Name = "游ゴシック"
    Cells(38, 8).Font.Name = "游ゴシック"
    Cells(38, 9).Font.Name = "游ゴシック"
    Cells(38, 10).Font.Name = "游ゴシック"
    Cells(38, 11).Font.Name = "游ゴシック"
    Cells(39, 2).Font.Name = "游ゴシック"
    Cells(39, 3).Font.Name = "游ゴシック"
    Cells(39, 4).Font.Name = "游ゴシック"
    Cells(39, 5).Font.Name = "游ゴシック"
    Cells(39, 6).Font.Name = "游ゴシック"
    Cells(39, 7).Font.Name = "游ゴシック"
    Cells(39, 8).Font.Name = "游ゴシック"
    Cells(39, 9).Font.Name = "游ゴシック"
    Cells(39, 10).Font.Name = "游ゴシック"
    Cells(39, 11).Font.Name = "游ゴシック"
    Cells(40, 2) = "でもここまでできたらいいだろって感じもするなあ。"
    Cells(40, 2).Font.Name = "游ゴシック"
    Cells(40, 3).Font.Name = "游ゴシック"
    Cells(40, 4).Font.Name = "游ゴシック"
    Cells(40, 5).Font.Name = "游ゴシック"
    Cells(40, 6).Font.Name = "游ゴシック"
    Cells(40, 7).Font.Name = "游ゴシック"
    Cells(40, 8).Font.Name = "游ゴシック"
    Cells(40, 9).Font.Name = "游ゴシック"
    Cells(40, 10).Font.Name = "游ゴシック"
    Cells(40, 11).Font.Name = "游ゴシック"
    Cells(41, 2) = "とりあえず、自分用の開発を効率よく進めるための土台はできた感じがする。"
    Cells(41, 2).Font.Name = "游ゴシック"
end Function
Function revival11()
    Cells(41, 3).Font.Name = "游ゴシック"
    Cells(41, 4).Font.Name = "游ゴシック"
    Cells(41, 5).Font.Name = "游ゴシック"
    Cells(41, 6).Font.Name = "游ゴシック"
    Cells(41, 7).Font.Name = "游ゴシック"
    Cells(41, 8).Font.Name = "游ゴシック"
    Cells(41, 9).Font.Name = "游ゴシック"
    Cells(41, 10).Font.Name = "游ゴシック"
    Cells(41, 11).Font.Name = "游ゴシック"
    Cells(42, 2) = "オブジェクトとか考えてやっていくかあ。"
    Cells(42, 2).Font.Name = "游ゴシック"
    Cells(42, 3).Font.Name = "游ゴシック"
    Cells(42, 4).Font.Name = "游ゴシック"
    Cells(42, 5).Font.Name = "游ゴシック"
    Cells(42, 6).Font.Name = "游ゴシック"
    Cells(42, 7).Font.Name = "游ゴシック"
    Cells(42, 8).Font.Name = "游ゴシック"
    Cells(42, 9).Font.Name = "游ゴシック"
    Cells(42, 10).Font.Name = "游ゴシック"
    Cells(42, 11).Font.Name = "游ゴシック"
    Cells(43, 2).Font.Name = "游ゴシック"
    Cells(43, 3).Font.Name = "游ゴシック"
    Cells(43, 4).Font.Name = "游ゴシック"
    Cells(43, 5).Font.Name = "游ゴシック"
    Cells(43, 6).Font.Name = "游ゴシック"
    Cells(43, 7).Font.Name = "游ゴシック"
    Cells(43, 8).Font.Name = "游ゴシック"
    Cells(43, 9).Font.Name = "游ゴシック"
    Cells(43, 10).Font.Name = "游ゴシック"
    Cells(43, 11).Font.Name = "游ゴシック"
    Cells(44, 2).Font.Name = "游ゴシック"
end Function
Function revival12()
    Cells(44, 3).Font.Name = "游ゴシック"
    Cells(44, 4).Font.Name = "游ゴシック"
    Cells(44, 5).Font.Name = "游ゴシック"
    Cells(44, 6).Font.Name = "游ゴシック"
    Cells(44, 7).Font.Name = "游ゴシック"
    Cells(44, 8).Font.Name = "游ゴシック"
    Cells(44, 9).Font.Name = "游ゴシック"
    Cells(44, 10).Font.Name = "游ゴシック"
    Cells(44, 11).Font.Name = "游ゴシック"
    Cells(45, 2).Font.Name = "游ゴシック"
    Cells(45, 3).Font.Name = "游ゴシック"
    Cells(45, 4).Font.Name = "游ゴシック"
    Cells(45, 5).Font.Name = "游ゴシック"
    Cells(45, 6).Font.Name = "游ゴシック"
    Cells(45, 7).Font.Name = "游ゴシック"
    Cells(45, 8).Font.Name = "游ゴシック"
    Cells(45, 9).Font.Name = "游ゴシック"
    Cells(45, 10).Font.Name = "游ゴシック"
    Cells(45, 11).Font.Name = "游ゴシック"
    Cells(46, 2) = "テストで使うcsvファイル"
    Cells(46, 2).Font.Name = "游ゴシック"
    Cells(46, 3).Font.Name = "游ゴシック"
    Cells(46, 4).Font.Name = "游ゴシック"
    Cells(46, 5).Font.Name = "游ゴシック"
    Cells(46, 6).Font.Name = "游ゴシック"
    Cells(46, 7).Font.Name = "游ゴシック"
    Cells(46, 8).Font.Name = "游ゴシック"
    Cells(46, 9).Font.Name = "游ゴシック"
    Cells(46, 10).Font.Name = "游ゴシック"
    Cells(46, 11).Font.Name = "游ゴシック"
    Cells(47, 2) = "api名じゃないとだめ。"
    Cells(47, 2).Font.Name = "游ゴシック"
end Function
Function revival13()
    Cells(47, 3).Font.Name = "游ゴシック"
    Cells(47, 4).Font.Name = "游ゴシック"
    Cells(47, 5).Font.Name = "游ゴシック"
    Cells(47, 6).Font.Name = "游ゴシック"
    Cells(47, 7).Font.Name = "游ゴシック"
    Cells(47, 8).Font.Name = "游ゴシック"
    Cells(47, 9).Font.Name = "游ゴシック"
    Cells(47, 10).Font.Name = "游ゴシック"
    Cells(47, 11).Font.Name = "游ゴシック"
    Cells(48, 2) = "Idは設定してもいいけど、load時にinsertされるから関係ない。"
    Cells(48, 2).Font.Name = "游ゴシック"
    Cells(48, 3).Font.Name = "游ゴシック"
    Cells(48, 4).Font.Name = "游ゴシック"
    Cells(48, 5).Font.Name = "游ゴシック"
    Cells(48, 6).Font.Name = "游ゴシック"
    Cells(48, 7).Font.Name = "游ゴシック"
    Cells(48, 8).Font.Name = "游ゴシック"
    Cells(48, 9).Font.Name = "游ゴシック"
    Cells(48, 10).Font.Name = "游ゴシック"
    Cells(48, 11).Font.Name = "游ゴシック"
    Rows(5).RowHeight = 18.75
    Rows(6).RowHeight = 18.75
    Rows(7).RowHeight = 18.75
    Rows(8).RowHeight = 18.75
    Rows(9).RowHeight = 18.75
    Rows(10).RowHeight = 18.75
    Rows(11).RowHeight = 18.75
    Rows(12).RowHeight = 18.75
    Rows(13).RowHeight = 18.75
    Rows(14).RowHeight = 18.75
    Rows(15).RowHeight = 18.75
    Rows(16).RowHeight = 18.75
    Rows(17).RowHeight = 18.75
    Rows(18).RowHeight = 18.75
    Rows(19).RowHeight = 18.75
    Rows(20).RowHeight = 18.75
    Rows(21).RowHeight = 18.75
    Rows(22).RowHeight = 18.75
    Rows(23).RowHeight = 18.75
    Rows(24).RowHeight = 18.75
    Rows(25).RowHeight = 18.75
    Rows(26).RowHeight = 18.75
    Rows(27).RowHeight = 18.75
    Rows(28).RowHeight = 18.75
    Rows(29).RowHeight = 18.75
    Rows(30).RowHeight = 18.75
    Rows(31).RowHeight = 18.75
    Rows(32).RowHeight = 18.75
    Rows(33).RowHeight = 18.75
    Rows(34).RowHeight = 18.75
    Rows(35).RowHeight = 18.75
    Rows(36).RowHeight = 18.75
    Rows(37).RowHeight = 18.75
    Rows(38).RowHeight = 18.75
    Rows(39).RowHeight = 18.75
    Rows(40).RowHeight = 18.75
    Rows(41).RowHeight = 18.75
    Rows(42).RowHeight = 18.75
    Rows(43).RowHeight = 18.75
    Rows(44).RowHeight = 18.75
    Rows(45).RowHeight = 18.75
    Rows(46).RowHeight = 18.75
    Rows(47).RowHeight = 18.75
    Rows(48).RowHeight = 18.75
    Columns(2).ColumnWidth = 8.38
    Columns(3).ColumnWidth = 8.38
    Columns(4).ColumnWidth = 8.38
    Columns(5).ColumnWidth = 8.38
    Columns(6).ColumnWidth = 8.38
    Columns(7).ColumnWidth = 8.38
    Columns(8).ColumnWidth = 8.38
    Columns(9).ColumnWidth = 8.38
    Columns(10).ColumnWidth = 8.38
    Columns(11).ColumnWidth = 8.38
    Dim onShape As Object
    Set onShape = ActiveSheet.Buttons.Add(296.25,73.5,45.75,24)
    onShape.OnAction = "A_フォルダ作成.A_フォルダ作成"
    onShape.Name = "Button 2"
    onShape.Visible = -1
    onShape.Placement = 1
    onShape.Characters.Text = ""
    Set onShape = ActiveSheet.Buttons.Add(462,297.75,45.75,24)
    onShape.OnAction = "B_オブジェクトメタデータ作成.B_オブジェクトメタデータ作成"
    onShape.Name = "Button 3"
    onShape.Visible = -1
    onShape.Placement = 1
    onShape.Characters.Text = ""
    Set onShape = ActiveSheet.Buttons.Add(461.25,396,45.75,24)
    onShape.OnAction = "C_カスタム項目メタデータ作成.C_カスタム項目メタデータ作成"
    onShape.Name = "Button 4"
    onShape.Visible = -1
    onShape.Placement = 1
    onShape.Characters.Text = ""
    Set onShape = ActiveSheet.Shapes.AddShape(106,266.25,151.5,191.25,75)
    onShape.Name = "Rounded Rectangular Callout 1"
    onShape.Visible = -1
    onShape.Line.ForeColor.RGB = 9392687
    onShape.Fill.Transparency = 0
    onShape.TextFrame.Characters.Text = "ここは後で修正。
トップがobjectsフォルダ
と、tabsフォルダ"
    onShape.Fill.ForeColor.RGB = 12874308
    onShape.TextFrame2.TextRange.Font.Size = 11
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame.Characters.Font.Color = 16777215
    onShape.TextFrame.Characters.Font.Name = "Calibri"
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.TextRange.ParagraphFormat.Alignment = 1
    onShape.Placement = 1
    onShape.LockAspectRatio = 0
    onShape.TextFrame2.AutoSize = 0
    onShape.TextFrame2.MarginLeft = 7.2
    onShape.TextFrame2.MarginRight = 7.2
    onShape.TextFrame2.MarginTop = 3.6
    onShape.TextFrame2.MarginBottom = 3.6
    onShape.TextFrame2.WordWrap = -1
    onShape.TextFrame2.VerticalAnchor = 3
    onShape.TextFrame2.HorizontalAnchor = 1
    onShape.TextFrame2.Orientation = 1
    Set onShape = ActiveSheet.Buttons.Add(461.25,486.75,45.75,24)
    onShape.OnAction = "createProfileMetaDataFile"
    onShape.Name = "Button 5"
    onShape.Visible = -1
    onShape.Placement = 1
    onShape.Characters.Text = ""
    Set onShape = ActiveSheet.Buttons.Add(460.5,576.75,45.75,24)
    onShape.OnAction = "createPageLayoutMetaDataFile"
    onShape.Name = "Button 6"
    onShape.Visible = -1
    onShape.Placement = 1
    onShape.Characters.Text = ""
    Set onShape = ActiveSheet.Buttons.Add(460.5,651.75,45.75,24)
    onShape.OnAction = "createCSVFileWithDataLoader"
    onShape.Name = "Button 7"
    onShape.Visible = -1
    onShape.Placement = 1
    onShape.Characters.Text = ""
End Function
Sub revival()
    CALL revival0()
    CALL revival1()
    CALL revival2()
    CALL revival3()
    CALL revival4()
    CALL revival5()
    CALL revival6()
    CALL revival7()
    CALL revival8()
    CALL revival9()
    CALL revival10()
    CALL revival11()
    CALL revival12()
    CALL revival13()
end sub